### ISSUE TITLE
Sharing behavior broken/strange on Collection view

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damspas#243]
On Collection views only, confirmed by @mdpeters on Chrome, FF, IE.

Current view:
<img width="1088" alt="screen shot 2016-10-06 at 9 43 40 am" src="https://cloud.githubusercontent.com/assets/67506/19161845/4b4568a2-8baa-11e6-910d-6bdfffb3752b.png">

Hover:
<img width="1061" alt="screen shot 2016-10-06 at 9 43 51 am" src="https://cloud.githubusercontent.com/assets/67506/19161864/5944e48c-8baa-11e6-852c-f1f4c5632f62.png">

**Comment by dt-ucsd** [comment]
Two things,

1) AddThis updated their widget--they updated the functionality and the look of the widget button (it didn't have a counter before)

2) The custom CSS I wrote to overwrite the style of the main button of their old widget is hiding the main button of their new widget

The solution is to modify or remove the CSS I was using to customize the old widget--depending on what folks want. Note that the default style of the AddThis widget makes it stand out on the page versus the more subdued custom styling we had before.

**Comment by dt-ucsd** [comment]
This is what it looks like now...

<img width="1081" alt="abc" src="https://cloud.githubusercontent.com/assets/2448340/19164840/6ae37e72-8bb6-11e6-9e61-073b85091738.png">

**Comment by dt-ucsd** [comment]
Before it was just a generic dark gray sharing icon. See:

https://github.com/ucsdlib/damspas/blob/3bb7eb57c071b713f7c7ad27d37a1a30bc073c96/public/images/sharing-icon.png

**Comment by mcritchlow** [comment]
Thanks @dt-ucsd !

@gamontoya and @mdpeters - deferring to you for comment.

I do wonder if we might re-position the widget to either be aligned left with the rest of the metadata, perhaps even with a label to give folks an idea of what the widget is/does. Or something similar on the right. As-is, on the desktop view at least, it seems to float between the two.

**Comment by mcritchlow** [comment]
@gamontoya - do we want to include this in the Sprint starting today?

**Comment by gamontoya** [comment]
@mcritchlow If you have David for this Sprint, definitely.

**Comment by mcritchlow** [comment]
@dt-ucsd scope of the ticket is just for fixing the code. we won't address the idea of moving it to a different position on the page at this time.

**Comment by dt-ucsd** [comment]
@mcritchlow Sounds like a plan.

**Comment by dt-ucsd** [comment]
These lines need to be deleted to fix the issue:

https://github.com/ucsdlib/damspas/blob/3bb7eb57c071b713f7c7ad27d37a1a30bc073c96/app/assets/stylesheets/custom-object-viewer.css.scss#L156-L166

**Comment by gamontoya** [comment]
@hweng So you removed "AddThis", but did you add another share widget?

**Comment by hweng** [comment]
@gamontoya This ticket was assigned to @dt that he has been working on it.

**Comment by dt** [comment]
(just a heads up, I think you cc'ed the wrong person)

**Comment by gamontoya** [comment]
@hweng Thank you!
