### ISSUE TITLE
Feature: Initiate delete from SHARE 

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damspas#251]
Please add the ability to initiate a deletion request via the SHARE Notify service for a give record.

This can be in the form of a new link that is only accessible to the group that is able to create SHARE records for Collections. 

> For the items to delete, we double-checked in the Hydra gem that there is a method to delete items from SHARE. So, the easiest thing is for you to initiate the delete requests from your end for the records you would like deleted. There is an example of doing a delete request in the README for the gem: 
> 
> - https://github.com/projecthydra-labs/share_notify/blob/master/README.md
> 
> The example references calling the delete method in push_document.rb: https://github.com/projecthydra-labs/share_notify/blob/master/lib/share_notify/push_document.rb It essentially sets a value of “status:deleted” in the otherProperties before pushing the record to SHARE. At a minimum, you will want to have the canonical uri set for any records you want to delete, but you could also send the original metadata that was sent over with the additional property set. 

Testing/QA Group: @gamontoya @hjsyoo

**Comment by hweng** [comment]
@mcritchlow Our existing working feature "Pushing to OSF staging"  seems not working as I tested yesterday.  I've emailed to Rick Johnson to ask if there is any change on OSF side that affect it and I am still waiting for his reply.

**Comment by hweng** [comment]
@gamontoya The records that i pushed recently doesn't show up in share staging.
The following is the last one posted on share staging:
https://staging-share-registration.osf.io/?page=1239&sources=UC+San+Diego

  "id": 12396,
            "updated": "2016-10-19T11:24:18.921735Z",
            "docID": "https://scholarsphere-staging.dlt.psu.edu/files/qn59q398d",
......

And I emailed to Rick Johnson about the above problem but haven't got any response yet. 
Did you have any updates from Rick?

**Comment by gamontoya** [comment]
@hweng What are you trying to do? Push records to Share and then delete them?

**Comment by gamontoya** [comment]
@hweng Also, how long ago did you contact Rick? Did you do it via email?

**Comment by hweng** [comment]
@gamontoya Could you try to push a record from dams4 staging: http://librarytest.ucsd.edu/dc/ and see if you can find it from share staging now?  This feature has been working well for quite a while in dams4, and we tested it was working after OSF updated their API in October but recently it has not been working for me.
I emailed to Rick on 11/17 and ask if there is any changes on their side but I haven't got response yet.

**Comment by gamontoya** [comment]
@hweng Okay, I just pushed one now.

![1](https://cloud.githubusercontent.com/assets/4314914/21018548/1f530296-bd22-11e6-8beb-19b08d1a3240.png)

**Comment by gamontoya** [comment]
@hweng What is the URL to check the push?

**Comment by gamontoya** [comment]
https://staging-share.osf.io/discover?sources=UC%20San%20Diego
https://staging-share-registration.osf.io/?sources=UC%20San%20Diego

**Comment by hweng** [comment]
@gamontoya The message just means it is successfully pushed out to OSF staging sever. But if OSF side doesn't show it up on their UI for some reason, we have no way to control how their application behavior.
But please let me know if you think we can updated the message to make it more sense.

**Comment by hweng** [comment]
To keep track - A email from Rick:
"Here is some background on what is likely happening...

  Chris Seto:  "Ah, chances are its just staging being wonky. The task queue generally gets bloated because staging is trying to keep up with a production load of data even though it has less than half the size. When I get some time and finish up the bug I've been working on, I'm going to clear all the data and only enable the most recent harvesters."

  I will check in with him later to see if there is a status update, but hopefully they will show up sometime later today.

Thanks!
Rick "

**Comment by hweng** [comment]
Per talking with SHARE team, they have been still working on queue issues on staging environment.
And also from SHARE team there is significant changes from SHARE API1 to API2, which the share_notify gem need to update to support for API2.
Will revisit this ticket when the above two issue/task get checked out.

**Comment by hweng** [comment]
@mcritchlow From the documentation for SHARE API V2, the deletions is not yet supported:
http://share-research.readthedocs.io/en/latest/share_api.html#push-data-directly-into-the-share-database

A question about "is the deletion supported by SHARE v2" was sent to Lauren Barker on Wednesday and I'm still waiting for her response.

**Comment by hweng** [comment]
Got “OSF | Page not found” issue when test pushing a record to OSF staging with API V2. I've sent a message to OSF developers for the issue and still wait for their response.

**Comment by hweng** [comment]
This work is "On hold" now as I was informed.
