### ISSUE TITLE
JWPlayer Upgrade

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/damspas#252]
Jwplayer is recommending an upgrade in anticipation of Chrome ending flash support.

Here is a link from jwplayer about the coming changes.

https://www.jwplayer.com/blog/deprecation-flash/

**Comment by VivianChu** [comment]
@gamontoya - I deployed the change for JWPlayer for Damspas to QA environment.

Could you please test them using your browsers, iphone, and android device?

For example,
//video
http://libraryqa.ucsd.edu/dc/object/bb8022051s

//video complex
http://libraryqa.ucsd.edu/dc/object/bb76807535

//audio
http://libraryqa.ucsd.edu/dc/object/bb23565552

//audio complex
http://libraryqa.ucsd.edu/dc/object/bb2629146f

Thanks

Vivian

**Comment by gamontoya** [comment]
@VivianChu Tested and working on IE, Firefox, Chrome, and Android phone. 

Note: Did not test on Safari.
