### ISSUE TITLE
Batch edit - attribution note - CME collection

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damspas#262]
Please update the attribution note for all the items in the [Center for Music Experiment Collection](http://library.ucsd.edu/dc/collection/bb10936072).  

Replace this:
    <dams:note rdf:resource="http://library.ucsd.edu/ark:/20775/bb3516867d"/>

With this:
    <dams:note>
      <dams:Note>
        <rdf:value>Digital Library Development Program, UC San Diego, La Jolla, 92093-0175 (http://libraries.ucsd.edu/about/digital-library/)</rdf:value>
        <dams:displayLabel>digital object made available by</dams:displayLabel>
        <dams:type>local attribution</dams:type>
      </dams:Note>
    </dams:note>

(and yeah, it looks like the records that were ingested via the input streams are creating free text notes instead of using an ark, we're going to add this to our "migration issues" list)

**Comment by lsitu** [comment]
@gamontoya @arwenhutt I've corrected the local attribution note for all 502 objects found in collection [Center for Music Experiment Collection](http://library.ucsd.edu/dc/collection/bb10936072). Could you take a look? Thanks.

**Comment by gamontoya** [comment]
@lsitu Confirming that this is fixed. Thank you!
