### ISSUE TITLE
Export DAMS collection (metadata and images)

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#263]
For Omeka evaluation (exhibits), Matt Peters needs a .csv export of all of the metadata and the masters files for the Dr. Seuss Political Cartoons collection:

- http://library.ucsd.edu/dc/collection/bb65202085

Output should be placed on digital-staging:

- lib-staging\Dr_Seuss_Exports\

**Comment by lsitu** [comment]
@rstanonik I've exported the metadata for all 390 objects in CSV format and copy the master files to \\darry.ucsd.edu\dams_staging\Dr_Seuss_Exports . But I don't think I have write access to digital-staging. Could you deliver it to digital-staging lib-staging\Dr_Seuss_Exports\? Thanks.

**Comment by gamontoya** [comment]
@lsitu It's okay to leave them where they are Longshou. Thank you!

**Comment by lsitu** [comment]
Thanks @gamontoya. 
@rstanonik: Then we don't need to move it to digital-staging for now until Gabriela orders for it. Thanks.
