### ISSUE TITLE
Ingest created duplicate objects in the DAMS - CCDB

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damspas#264]
I'm QA'ing CCDB and one batch has significant problems.  

I received two separate DAMS manager reports on the ingest (attached) - each with different (almost opposite) failure reports.  There are two basic conditions these represent 1) most of the items which are listed as "failed" in the first report, show as "successful" in the second, and vice versa.  2) There are also a handful of items which are listed as "successful" in both reports.

In the DAMS it appears that all of the items which had different results in the two reports (condition 1 above) ingested the item twice, so there are two duplicate objects with different arks in the DAMS (e.g. [product ID: 1040](http://library.ucsd.edu/dc/search?page=4&q=Microscopy+product+ID%3A+1040&spellcheck.q=Microscopy+product+ID%3A+1040&utf8=%E2%9C%93)).  From the sample I looked at, it also appears that one of the items has failed to tile the zoomify image, while the other seems to have worked.  

For those items which met condition #2 above, the item only appears once in the DAMS.  

As a result there are two things needed:
- The source of this problem should be identified to prevent future duplicate ingests
- The duplicated items should be deleted (preferably those that did not tile)

**Comment by arwenhutt** [comment]
I'm having some problems with attaching the files here.  They are located on the rdcp-staging server at: Z:\ccdb\Admin\ingest reports

I've appended the name of the batches to the system generated report names, so just look for batch-08 and you'll find all the logs

**Comment by lsitu** [comment]
@arwenhutt I think this will happen if you submit the batch twice at almost the same time from different sessions. What browse are you using? Do you see the progress report after you submitted that batch for ingest?

**Comment by arwenhutt** [comment]
Firefox, and I'm not sure what you mean by "Do you see the progress report after you submitted that batch for ingest?"

I would not have had it open in multiple browsers, so I'm not sure how I would have submitted it twice, unless the UI did not show the progress bar and instead showed a timed out session or a failure.

**Comment by arwenhutt** [comment]
Ah, wait, you probably meant the inline progress report, sorry, I don't think of it as a report so was confused.  I don't remember if I saw that or not, this was a couple of weeks ago.  If I had seen it, I would definitely not have redone the ingest.

**Comment by lsitu** [comment]
@arwenhutt Yes,  I mean a progress bar and the report message after you submitted batch 8. I think if you click the submit button twice to submit the batch, damsmanager should reject the second one with an error message like "WARNING: Another process is running. Servlet Request aborted ....". I you see this message and submit the batch again, a duplicate ingest will happen. So we may need more information regarding how batch 8 is submitted. Thanks.

**Comment by arwenhutt** [comment]
I'm not sure what additional information I can provide.  I would not resubmit a batch if the first batch showed that it was processing (progress bar).  That would be silly!

**Comment by arwenhutt** [comment]
Also, if you look at the logs, the time stamps are the same down to the second.  I wouldn't be able to replicate that through submitting an ingest twice even if I tried.

**Comment by lsitu** [comment]
@arwenhutt Do you see an error message like "WARNING: Another process is running. Servlet Request aborted ...." before you submit another one? If you do that within minutes or more, I think this will happen because some files are larger and some are small and eventually both process will be try to ingest the same file and it will be failed.

**Comment by arwenhutt** [comment]
I don't remember because it was a while ago and honestly pretty rote after 7 other batches, but it doesn't make sense that I would re-submit in the first minute if the first submission showed any signs of working and getting an explicit error message.

**Comment by lsitu** [comment]
Then it'll be a little bit hard but yes, I think I can disable the Submit button from submitting twice.

**Comment by arwenhutt** [comment]
So are you saying that if the Submit button is clicked, there may be no feedback in the UI, and so it can look like it was not submitted?  If there was no visible indication that it was submitted, then I can see clicking a second time.  Though I'm pretty sure I'd wait at least a few seconds to check for visible feedback.  Wouldn't the time stamp be different then, since it records down to the second?

**Comment by lsitu** [comment]
Yes, it possible that double clicking could be happened at almost the same time and the timestamp records down to the second. But normally an error message like "WARNING: Another process is running. Servlet Request aborted ...." will be responded back for the second resubmission. With disabling the submit button once it is click, we only can submit once within on the same UI.

**Comment by arwenhutt** [comment]
Yeah, I don't think it makes sense to keep the "Submit" button functional after it's been clicked and before the screen switches to the progress bar.  Also, if I had read that message "WARNING: Another process is running. Servlet Request aborted ...." I would assume that that the second attempt was terminated and so would not think that there would be dupe's. Just for message clarity.

I still find it unlikely that I double clicked the button (double click is just a different muscle memory), but I guess weirder things have happened.

**Comment by mcritchlow** [comment]
@arwenhutt @lsitu - I was out during this dialog, but I'm curious what the status of this ticket is? Is there work needed still?

**Comment by lsitu** [comment]
@arwenhutt Do you want me to disable the submitted button once it's been clicked as the action for this ticket for now?

**Comment by arwenhutt** [comment]
There were two parts of the ticket: 
-     The source of this problem should be identified to prevent future duplicate ingests
-     The duplicated items should be deleted (preferably those that did not tile)

For the first, yes, as we discussed in December, IMO (so you know, if someone disagrees, please say) it doesn't make sense to allow multiple submissions of the form/ingest set.  

For the second part, we still need the duplicated items deleted.

**Comment by lsitu** [comment]
@arwenhutt Do you have the list of duplicated items for me to delete?

**Comment by lsitu** [comment]
@arwenhutt I am adding support to disable the submit button once it's being click now. Do you have a list of duplicated records for me to clean up? Thanks.

**Comment by lsitu** [comment]
@arwenhutt I've updated damsmanger to disable the Submit once it's clicked (See https://github.com/ucsdlib/damsmanager/pull/132). Please let me know if we are ready to clean it up. Thanks.

**Comment by gamontoya** [comment]
@arwenhutt This too should be verified by you on staging preferably by Monday at the latest.

**Comment by arwenhutt** [comment]
Ugh, sorry guys, missed all the comments posted after mine on Feb. 1.  I think I need to adjust some settings because I appear to be getting notifications on lots of issues that I'm not involved in and I loose the wheat in the chaff.  I'll try to look at this tomorrow (thought it's a full day) or Friday.

**Comment by gamontoya** [comment]
@mcritchlow I approved the deploy to DAMS Manager, but I wasn't able to fully vet this because I couldn't replicate hitting the "submit" button twice and I tried many times.

**Comment by lsitu** [comment]
@gamontoya For this new release, yes you won't be able to hit the submit button twice. And for the earlier version, I think you may if the progress report bar delays to be showing up after you click the submit button.

**Comment by arwenhutt** [comment]
[CCDB_Duplicates.txt](https://github.com/ucsdlib/damspas/files/794611/CCDB_Duplicates.txt)

@lsitu I'm attaching a list of duplicate objects to be removed.

**Comment by lsitu** [comment]
@arwenhutt Thanks. I've deleted all 50 objects listed in the attached file CCDB_Duplicates.txt. We should have total 471 CCDB objects now, http://library.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=Cell+Centered+Database&id=bb5940732k. Could you take a look?

**Comment by arwenhutt** [comment]
This looks good, thanks @lsitu
