### ISSUE TITLE
Statistics: investigate how to expose items hit per collection

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#265]

**Comment by gamontoya** [comment]
Data provider wants to know how many times people hit items belonging to a specific collection.

Per Longshou: _we should have the stats there now just need to see how to expose it._

**Comment by lsitu** [comment]
@gamontoya Currently we count any access to thumbnails/derivatives or master files as one hit/access to an object in a collection. Do you think we need to adjust this counting rule or not? Or something more accurate like counting the items views belonging to a specific collection?

**Comment by gamontoya** [comment]
@lsitu I think we should count how many times a thumbnail is hit which accurately tells us that an item was looked at whether they clicked on zoom or downloaded it.

**Comment by lsitu** [comment]
@gamontoya Yes, we are counting for file downloads at this time, in the way we've done for RDCP stats.

**Comment by lsitu** [comment]
Another issue is that the search hits with thumbnail listed on the search result page is also included in the current items hits/item access.

**Comment by gamontoya** [comment]
@lsitu 

1. File downloads: Can this be exposed for DC collections in the stats?
2. We want hits on the actual thumbnail, not search result hits. Is the former not possible?

**Comment by lsitu** [comment]
Hi Gabriela,
For your questions above:
1. Yes.
2. I think we can update dams statistics to count on any thumbnails/derivatives. Currently, thumbnail 4.jpg is used for search hits and 3.jpg is used for views. But the counting of 3.jpg (plus master files) is close to the stats for item views. So just give me the rules regarding how to count it as hits and I can update damsmanager for it.

**Comment by gamontoya** [comment]
@lsitu Confirmed with Matt that we don't want how many times a thumbnail comes up in a search result. We want how many times a person clicks on a thumbnail to bring up the object/metadata.

**Comment by lsitu** [comment]
@gamontoya Then I think we should simply use the item views and aggregate it for a specific collection. What do you think?

**Comment by gamontoya** [comment]
@lsitu I think that's the way to go. Thanks Longshou.

**Comment by lsitu** [comment]
Hi Gabriela,
I've created a [PR](https://github.com/ucsdlib/damsmanager/pull/118) for the statistics of items hits and file downloads per collection. I've deployed it to QA:
https://libraryqa.ucsd.edu/damsmanager/statsCollection.do
https://libraryqa.ucsd.edu/damsmanager/statsCollection.do?type=downloads

It requires curator role to access the statistics above. Could you take a look to see whether it's good to fit your need? Thanks.

**Comment by lsitu** [comment]
@gamontoya I've updated the PR to exclude the curator access from both stats and should should see the difference on QA now: some collections have less counts and those test collections on the top are gone. I've merged the PR and please let me know if you need any changes.

**Comment by gamontoya** [comment]
@lsitu Thank you. Looks great. Thanks for your flexibility.

**Comment by lsitu** [comment]
@mcritchlow Suggested by Gabriela, I've created [PR](https://github.com/ucsdlib/damsmanager/pull/124) to rename the servlet to statsCollectionObjects.do and rename report title to "Object/Collection Hits by Month" and "Object/Collection Downloads by Month" respectively for collection items hits/downloads statistics.
