### ISSUE TITLE
Updating share_notify gem to add support for SHARE 2 API 

### ISSUE THREAD

**Issue by hweng** [ucsdlib/damspas#268]
Issue in Share Notify repository that @hweng is working on w/ Don Brower https://github.com/projecthydra-labs/share_notify/issues/11

**Comment by hweng** [comment]
The updates for the SHARE gem, the purpose for the version 2 support is to encapsulate the complicity for creating and serializing the Graph and Graph Nodes in the SHARE gem, which is conforming to the SHARE version 2 API .
1. Adding modules to create and serialize the Graph and GraphNodes.
2. Adding linked relationship between Graph Nodes, have been in the discussion with SHARE developer what relationships should include.
3. Including the known use case for testing, is in the discussion with SHARE developer about it.

**Comment by hweng** [comment]
@mcritchlow  The support for SHARE API 2 has been pushed to share_notify/update_v2 branch: https://github.com/projecthydra-labs/share_notify/commit/fd2cc1ade1702cc2093779c1ffd1e989df2060b1

It is not finished yet, I will work on the tests and wait for the inputs from Donald Brower, from University of Notre Dame.

**Comment by hweng** [comment]
@mcritchlow I've wrapped up the support for SHARE push and GraphNode mapping for SHARE gem V2.  The unit and feature tests has been added and passed.  And we tested the real push is working fine too which we hooked up new gem with our local app:
https://github.com/projecthydra-labs/share_notify/commit/30feec1f15c4c890206d691065f49392fdec880c

Don mentioned to me his TODO list has a few more things on it, such as implementing deleting. So I'm waiting for his inputs and I will review it as soon as he is done.

Would you like this ticket to add to icebox for now?

**Comment by mcritchlow** [comment]
@hweng great, thanks for the update.

Yes if you can add this to the Icebox that would be great. Also, if/when Don creates a PR to get both of your changes in the gem, if you could like to that here it would be great for tracking.

Thanks!

**Comment by hweng** [comment]
@mcritchlow  The PR is here: https://github.com/projecthydra-labs/share_notify/pull/12

**Comment by hweng** [comment]
Close this issue since the PR was merged into master branch.
