### ISSUE TITLE
Rewrite mapping from DAMS 4 to SHARE 2 schema.

### ISSUE THREAD

**Issue by hweng** [ucsdlib/damspas#269]

**Comment by arwenhutt** [comment]
Thanks for creating this ticket @hweng

**Comment by hweng** [comment]
@arwenhutt Created another ticket which update dams4 code to Implement new mapping and API for SHARE2: https://github.com/ucsdlib/damspas/issues/270. It will be visited after your mapping spreadsheet is done.  Thanks!

**Comment by arwenhutt** [comment]
[UCSD_SHARE_mapping_2017_01_06.xlsx](https://github.com/ucsdlib/damspas/files/691014/UCSD_SHARE_mapping_2017_01_06.xlsx)

Here you go @hweng ! 
Let me know if you have any questions :)

**Comment by hweng** [comment]
@arwenhutt  Could you give me the expected result for version 2, for example bb7305352v? What's the expected JSON result you would like to see?

**Comment by arwenhutt** [comment]
I'm not sure I can.  I don't work with the json syntax much, and only have their schema documentation to go for understanding how there schemas implemented.

**Comment by hweng** [comment]
@arwenhutt If you look at the schema example, it is exactly JSON structure. In my understanding, the purpose of mapping is to translate our dams4 data structure to the JSON output which should be conforming to SHARE V2 schema data structure so that the output metadata can be feed into SHARE repository.
So without the output metadata example, I'm wondering how can we make sure the mapping is correct? How can you do QA? 
Similar to the assembly plan we did years ago, there was the output xml example included in the assembly mapping ticket. I think if it doesn't have to be as detail as that, at least it should include the output JSON example in the mapping.

**Comment by arwenhutt** [comment]
I agree that it would be useful but I don't understand their data model or their expression of it adequately to feel qualified to do this.  Perhaps we could tackle this another way.  

What if we share our spreadsheet (possibly edited for the purpose) with Lauren and see if she can help us create a sample record.  That would help us to understand the schema and it's expression better, and possibly tease out issues with the mapping.  What do you think of that as an approach?

**Comment by hweng** [comment]
Yes, I agree. What about we pick one or a few collection records with our dams4 solr examples(input) and your spreadsheet, and see if she can come up the output examples? And then we work together to correct or refine them. And the output examples can be used as a guideline for your QA in the future.

**Comment by arwenhutt** [comment]
Sounds good.  One thing though, since this is not a dependency for the Feb. 1st Demo deadline, we should postpone this until the demo work is complete.

**Comment by hweng** [comment]
@arwenhutt While waiting for them, I think I can look into their data model and expression and try to create the sample output records.  As they are expertise with their data model but may not know our dams data structure.
Does it sound good to you? And Please let me know what records you would like me to try.

**Comment by arwenhutt** [comment]
Sure, I think that would be great.  I don't have a particular record in mind, you can browse through the RDCP Collection records and pick one out that looks fairly complete, that should be fine.

**Comment by hjsyoo** [comment]
@hweng @arwenhutt Re: Source and Publisher/DataProvider for DAMS records, I'm proposing the following values:
Source = UC San Diego Library
Data provider = UC San Diego Library Digital Collections.

Does this work?

**Comment by hweng** [comment]
@hjsyoo Yes, It looks fine to me. Currently for SHARE API V1, publisher = "UC San Diego Library, Digital Collections", but there is no source and Data provider fields.

**Comment by hjsyoo** [comment]
@hweng Publisher is fine - it'll map correctly to their schema. I think we only asked that the Publisher be relabeled as "Data Provider". But if the records don't have a Source value, then we won't be able to call up the DAMS records by Source=UC San Diego Library. Do you think Source is something they assign on their end when receiving records? If so, I can submit the request to SHARE.

**Comment by hweng** [comment]
@hjsyoo I think the Source=UC San Diego Library. need to be included in the JSON data we pushed to SHARE API, currently their system doesn't assign on their end when receiving records.
But I think It would be easy to incorporate the source field when push the records to SHARE.

**Comment by hjsyoo** [comment]
@hweng That would be great. Thanks!

**Comment by hweng** [comment]
@arwenhutt  I've created an example output record which conforms to SHARE V2 schema:
 to_share_bb7305352v
https://gist.github.com/hweng/81bbd50513895f09b9b93003e921a5a4

Let me know if it looks right to you or do we want to ask SHARE developer to verify it?

**Comment by arwenhutt** [comment]
@hweng I think it would be good to get them to verify, I'm not sure enough about the use of ThroughTags and name/role structures. 

A few other things I noticed in the meantime:
-  @type should be "DataSet" for bb859c88-e309-4d51-aaf3-39f9ec39f97e (mapping line 2)
- it looks like description note (mapping line 6) and doi (mapping line 8) are missing
- The DAMS encoding for the funding note needs updating (we added a dedicated funding type after that record was created), and then it should also be in the SHARE output (mapping line 29)

Oh and please cc/tag me when you ask for input from SHARE so I can follow along, thanks!

**Comment by hweng** [comment]
@arwenhutt  I talked with SHARE developer Abram Booth today, and he helped to validate our output example.
Most of our JSON output looks fine to him. He pointed out a few issues and I made correction to them.

For your last comments:
#1. Verified with Abram that it is correct, "DataSet" is just the label name in the schema page. In actual JSON, it should starts with {"data": {"type": "NormalizedData","attributes": {"data": {"@graph": [ 
#2 Yes, I’ll add the description note. For doi (mapping line 8), Could you give me an ark of record that contains the doi?  And I need to verify it with Abram if it is fine to have multiple work identifier in a record.
#3 DAMS encoding for the funding note, as in SHARE schema it is an object type: “extra": {"type": "object"}
Could it be something like this syntax: [“extra”: {funding: “some funding notes put in here “]

**Comment by hweng** [comment]
@arwenhutt And For otherNote_json_tesim value for "type":"related publications"(mapping line 29), to related_works/@type='workrelation'.  I'm not clear how to express it according to SHARE schema yet. Does it require the link to parent node like what the related_agent, through_tag does? Does it require the link to IDs existing in the SHARE database? And if it is the external link, what the structures it should be? I need to talk to SHARE developer about those questions.  It would be helpful if you could send me an ark of record which have the related publications? Thanks!

**Comment by hweng** [comment]
@arwenhutt, @hjsyoo I got it pushed to SHARE Staging V2 successfully, Let me know if it looks fine to you:
https://staging-share.osf.io/creativework/4605A-898-E37

**Comment by hjsyoo** [comment]
@hweng For Resource Type, can we assign all RDCP collections the value, "Data Set"? @arwenhutt Should we be including the Funding note, if it exists for a collection? This example happens to have one, but since it's not in any sort of standard format, I'm not sure how easy it is to do.

**Comment by hweng** [comment]
@hjsyoo This example don't have Funding note, because in solr it doesn't have otherNote_json_tesim value for "type":"funding".  Do you know any collection record have "type":"funding" ?

**Comment by hjsyoo** [comment]
@hweng The only DAMS record I'm able to find at https://staging-share.osf.io/ is the one you gave, https://staging-share.osf.io/creativework/4605A-898-E37. This one has a funding note.

**Comment by hweng** [comment]
@hjsyoo Thanks, you are right. I checked that this is because I got an out-of-dated bb7305352v which have the "type":"note" instead of "type":"funding":
<img width="1192" alt="screen shot 2017-03-08 at 11 23 47 am" src="https://cloud.githubusercontent.com/assets/2432753/23720357/5efc0312-03f3-11e7-96c1-3b814c47eab2.png">

I will reload the record into my localhost and reindex and map it to SHARE.

**Comment by hweng** [comment]
@hjsyoo, I've updated mapping to add "extra": {"funding": "Doctoral Dissertation........"}, And I pushed it to SHARE V2 staging again.
https://gist.github.com/hweng/81bbd50513895f09b9b93003e921a5a4,
The JSOn output looks fine to me according to SHARE V2 schema, but I don't know why The SAHRE interface doesn't show extra field. I will pin this issue to their developer.

**Comment by hjsyoo** [comment]
@hweng Ok, thanks for following through on this. Hopefully, the additional funding note will mesh reasonably well with the other funding information SHARE has.

**Comment by hweng** [comment]
@arwenhutt Would you take a look of our JSON output: https://gist.github.com/hweng/81bbd50513895f09b9b93003e921a5a4

And corresponding record pushed on staging:
https://staging-share.osf.io/creativework/4605A-898-E37

And let me know if it looks all right to you. Thank you!

**Comment by hjsyoo** [comment]
@hweng I'm not versed well enough in JSON to review your output correctly, but I do have a request! Could all RDC landing pages (whether it's from a collection or object page) be mapped to Resource Type = Dataset, rather than Creative Work? We're trying to steer away from typing any DAMS-RDC data as Creative Works.

**Comment by hweng** [comment]
@hjsyoo The CreativeWork is defined as "Anything created by an Agent" in SHARE V2 schema: https://staging-share.osf.io/api/v2/schema. The DataSet and all other type of resource are the subcategory of CreativeWork.
Thus the CreativeWork is defined as default in the share_notify gem.

**Comment by hjsyoo** [comment]
@hweng Thanks for the clarification. I'd still like Dataset to be displayed somewhere. The pushed record, https://staging-share.osf.io/creativework/4605A-898-E37, has resource type "Not Categorized". Can we indicate that DAMS records are of the subcategory, DataSet?

**Comment by hweng** [comment]
@hjsyoo Sure, I will check with OSF developer which field in their schema is used to display it in their UI.

**Comment by gamontoya** [comment]
FWIW: https://staging-share.osf.io/api/v2/datasets/

**Comment by hweng** [comment]
@hjsyoo @gamontoya I confirmed with Lauren that if we map it to a particular CreativeWork type, it will show up in UI as category.  And I've also looked into the datasets schema.
I'm updating the mapping code for all RDC collections to SHARE dataset, what about the library collections?

**Comment by gamontoya** [comment]
@hweng Good point. Unfortunately for library collections, we don't have an appropriate type based on their schema so they will have to stay within CreativeWork.

**Comment by hjsyoo** [comment]
Thanks @hweng @gamontoya. It makes the most sense to me that RDC colls are "Datasets", while library colls remain "Collections" or "CreativeWork".

**Comment by hweng** [comment]
@gamontoya It makes sense. I updated our mapping code for datasets schema. Here is the result generated from new mapping code:  https://gist.github.com/hweng/81bbd50513895f09b9b93003e921a5a4

And also I found there is an response error to push to OSF  when using the new staging token from OSF. I will contact them to sort out this issue.

**Comment by arwenhutt** [comment]
I'm adding @hannahbegley to this issue to review the export.  Thanks!

**Comment by hweng** [comment]
@gamontoya @arwenhutt  @hannahbegley, 
There is the "researcher" type in relationship_json_tesi which is not a valid type in OSF schema:

From dams4 solr http://lib-hydratail-prod.ucsd.edu:8983/solr/blacklight/select?q=id:bb7305352v:
{"contributor":["Ascher, John","Berrian, Jim","Davids, Jessica A.","Holway, David A.","Rightmyer, Molly G.","Wall, Michael","Yanega, Doug"],"researcher":["Hung, Keng-Lou James"]}

And The valid "related_agents" type in OSF includes:
https://staging-share.osf.io/api/v2/schema/CreativeWork
"@type": {
                            "enum": [
                                "AGENTWORKRELATION",
                                "AgentWorkRelation",
                                "CONTRIBUTOR",
                                "CREATOR",
                                "Contributor",
                                "Creator",
                                "FUNDER",
                                "Funder",
                                "HOST",
                                "Host",
                                "PRINCIPALINVESTIGATOR",
                                "PRINCIPALINVESTIGATORCONTACT",
                                "PUBLISHER",
                                "PrincipalInvestigator",
                                "PrincipalInvestigatorContact",
                                "Publisher",
                                "agentworkrelation",
                                "contributor",
                                "creator",
                                "funder",
                                "host",
                                "principalinvestigator",
                                "principalinvestigatorcontact",
                                "publisher"
                            ]
                        }

So what would you like it to be mapped to if DAMS relationship data is not included in the above list, for example, the "researcher" relationship type? Thanks!

**Comment by arwenhutt** [comment]
@hjsyoo and @hannahbegley 
I'd lean towards Researcher -> Creator, unless you guys think "contributor" is better.

**Comment by hannahbegley** [comment]
@arwenhutt before answering I think I need understanding/clarity on 2 things:
1. the intention here- SHARE displays all individuals under "Contributors" regardless of their role, so is this for our benefit, or in case of future functionality?
2. Can we count on a pretty consistent use of "researcher"? In the above example, https://librarytest.ucsd.edu/dc/collection/bb7305352v it looks like "researcher" is the PI (lead author anyway). I don't know if this actually occurs, but I could also see it interpreted as someone who contributed to the research but maybe not enough to list as an author. Does that seem like a valid concern?

**Comment by hweng** [comment]
@arwenhutt @hannahbegley, Good questions!
To clarify - The dams record got rejected when push to OSF staging because of the role type of "researcher", so we have to replace it with any type in the above "@type" list.  The pushed data has to be strictly following OSF data schema to get push successfully.
It is true OSF UI only display "Contributors" regardless of their role. But as long as data is there, I think it can be easily updated to display according to its real role. If we want we can request OSF to update their UI.

**Comment by arwenhutt** [comment]
I've been looking through RDCP collection records and there is a fair amount of variability.  Some of which is probably based on an accurate description of roles, but some seems to be more of an inconsistent application.  I've seen pi (with multiple names), co-pi's, creator, author, research team head, researchers, etc.  It might be worth a review of how these are applied and perhaps some clean up, though I think we'd need to rely on @hjsyoo to know which are correct and which could be better.  It would give us more confidence in the mapping, but also help to formulate some BP guidelines for future collections.  

@hjsyoo @hannahbegley what do you think?

**Comment by hannahbegley** [comment]
thanks @hweng for clarifying that's really helpful! @arwenhutt @hjsyoo my preference generally is vague but consistent over precise but potentially inconsistent. So, if we continue relying on researchers to supply roles (which we should) I don't think I would place the trust to do that "consistently" with a group (tbh wouldn't even trust myself). For that reason I'd vote map it to contributor- all the other RelationshipType values are basically instances of contributor. 

Going further, if I could take this all the way I might just map all "related_agents" types as contributors, but leave the more complex role relationships in our source data as they were provided- perhaps conventions around when to use creator/author/PI/etc. can vary across disciplines, and we would want to let invested parties make these decisions based on appropriate terminology in their field. You both are far better positioned to comment on whether that's actually the case, and this view could be placing too must trust/thought in the way these have been assigned.

**Comment by arwenhutt** [comment]
I suspect it's somewhat in the middle, with there being some inconsistency coming from the library side (both from change over time and variability between metadata analysts), and some that's from the researcher.  How much of it is one vs. the other, I'm not sure - and not sure then how valuable it'll be to review, change and set guidelines.  Though I do think the example you listed probably should be PI, it was an early collection so may have even pre-dated the addition of the PI role in the system.

For @hweng's question, I'm fine with either creator or contributor (we are mapping into a big vague bucket, where the value of specificity is pretty unclear at this point).  As long as @hjsyoo doesn't think PI is better.

**Comment by hweng** [comment]
@arwenhutt @hannahbegley Thanks for the reply. Just to clarify do you prefer to that all roles to be mapped to "creator" or "contributor"? Or only those role type which is not in OSF schema list to be mapper to "creator" or "contributor"?

**Comment by arwenhutt** [comment]
@hweng I think we need to consult Ho Jung before we decide.  Sorry for the delay, but once we talk to her we'll let you know.

**Comment by hweng** [comment]
@arwenhutt Sure, no problem. Thank you all!

**Comment by hjsyoo** [comment]
Hi all, thanks for the discussion. Those are all excellent points. It looks like creating some documentation on how the various DAMS roles will map to SHARE would be a good idea. In the meantime, if Researcher has only been used in that one collection, let's do the following:
* Change James Hung's role from Researcher to Creator (@hannahbegley is correct that he was more of a PI in this instance, except that he didn't get specifically funded for this work, so PI isn't exactly correct either). I will confirm with James that this change is okay with him.
* Map Researcher to Contributor.
* Remember to let researchers know that Researcher~Contributor. I don't think this will be burdensome, given how infrequently this role has been selected.

Also confirming that it's best to let researchers choose roles from a predefined list, whether short or long. Attribution is paramount, but the good news is that what we have now seems to work well.

**Comment by hweng** [comment]
Thanks @hjsyoo, Let me know if you want me to proceed the above steps, and please confirm the following:
#1 "Change James Hung's role from Researcher to Creator", do you want to update the dams metadata for it?
#2 "Map Researcher to Contributor" -  This will be implemented in mapping code. Do you want all roles which is not in OSF schema list to be mapped to "contributor"?

**Comment by gamontoya** [comment]
@hweng @hjsyoo What's the status of this ticket?

**Comment by hweng** [comment]
@gamontoya This work has been on hold status for some reason. I'm fine to proceed it if need. What do you think @hjsyoo ?

**Comment by hjsyoo** [comment]
@hweng Yes, please proceed with the work. Thank you!

**Comment by gamontoya** [comment]
@hweng You don't need feedback from @hjsyoo or @arwenhutt  on this ticket in order to proceed, do you?

**Comment by hweng** [comment]
@hjsyoo, Let me know if you want me to proceed changes, and please confirm the following:
#1 "Change James Hung's role from Researcher to Creator", do you want to update the dams metadata for it?
#2 "Map Researcher to Contributor" - This will be implemented in mapping code. Do you want all roles which is not in OSF schema list to be mapped to "contributor"?

**Comment by hjsyoo** [comment]
@hweng Yes, sorry this fell through the cracks. We had updated the DAMS metadata (https://library.ucsd.edu/dc/collection/bb7305352v), but the confirmation hadn't made it to this ticket. Also confirming that all roles not in the OSF schema list should be mapped to "contributor".

**Comment by hweng** [comment]
Thanks for confirming @hjsyoo
