### ISSUE TITLE
https streaming issue on latest chrome

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damspas#271]
From Ron:
```
While Dan was trying to add a video to LISN, he discovered that streaming no longer worked for the latest chrome.
 
The problem seems to be that https LISN includes http streaming links and chrome no longer allowes http links on https pages.
 
I added an https streaming port to the streaming server and changed the LISN streaming-video macro to use it.
 
The change was from http://lib-streaming.ucsd.edu:1935 to https://lib-streaming.ucsd.edu:1936.
 
And I added a manifest.mpd source and made the source order manifest.mpd, playlist.m3u8, rmtps (from rmtp) last.
 
We confirmed that https streaming works for chrome, firefox, IE, and Edge.
 
Dev, you will need to make similar changes for DAMS and DMR.
 
Additionally, make manifest.mpd first in the source list.
 
Ron
```

**Comment by VivianChu** [comment]
@gamontoya The update to fix this streaming issue has been deployed to staging.  Would you please take a look?  
For example
//complex video
http://librarytest.ucsd.edu/dc/object/bb3482439v

//single video
http://librarytest.ucsd.edu/dc/object/bb1571482k

//audio
http://librarytest.ucsd.edu/dc/object/bb23565552

//audio complex
http://librarytest.ucsd.edu/dc/object/bb2629146f

Thanks

**Comment by gamontoya** [comment]
@VivianChu @mcritchlow This has been tested and working. How soon can we push this out to prod? Today? Tomorrow?

**Comment by mcritchlow** [comment]
@gamontoya - @VivianChu is setting up a deploy ticket now and we'll ask OPS to deploy as soon as they can.

**Comment by gamontoya** [comment]
@mcritchlow Thanks. Should I let John know we want it in by tomorrow morning?

**Comment by VivianChu** [comment]
@gamontoya John is planning to deploy it service window tomorrow.
