### ISSUE TITLE
Add captcha to contact form

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damspas#272]
Unfortunately the current [contact form](http://library.ucsd.edu/dc/contact) is getting spammed like crazy.

It does appear that [we're using the :captcha feature](https://github.com/ucsdlib/damspas/blob/3bb7eb57c071b713f7c7ad27d37a1a30bc073c96/app/models/contact_form.rb#L9) built into the mail_form gem, but it doesn't appear to be working. There is a [single issue](https://github.com/plataformatec/mail_form/issues/50) at the moment which mentions a similar problem, though we're using the version he says works fine.

In any event, we may have to resort to an external captcha as we do in the public website forms.

**Task**: Please put a captcha on the form as we do on other public website forms.

**Reviewer**: Please tag @gamontoya for review and confirmation

**Comment by dt-ucsd** [comment]
How about replacing the mail_form gem with MachFrom? For example...

https://library.ucsd.edu/forms/view.php?id=47795

**Comment by mcritchlow** [comment]
@dt-ucsd by replace you mean embed the MachForm into the current contact form view?

**Comment by dt-ucsd** [comment]
@mcritchlow Yeah.

**Comment by mcritchlow** [comment]
@dt-ucsd - OK cool. I think that's worth trying out, and then they'll get the benefit of having submissions available in the Mach Form system. Could you create a PR for this, and perhaps attach a screenshot as well in advance so @gamontoya can get an idea for what the UI will look like?

**Comment by dt-ucsd** [comment]
Sure thing.

**Comment by dt-ucsd** [comment]
![dc-contact-form-mf](https://cloud.githubusercontent.com/assets/2448340/21871551/b5bb8b58-d817-11e6-87d2-a568a872b7b7.png)

attn: @gamontoya

**Comment by gamontoya** [comment]
@dt-ucsd Thanks David. Please move forward with this. I happen to love CAPTCHA!

**Comment by mcritchlow** [comment]
@dt-ucsd are you going to be able to get a PR up for this today? We're trying to wrap up the Sprint and wondering if we'll be able to cut a release for the DC app. Thanks.

**Comment by dt-ucsd** [comment]
@mcritchlow I will get this PR up momentarily.

**Comment by dt-ucsd** [comment]
Pull request made. Find it here:

https://github.com/ucsdlib/damspas/pull/275

**Comment by dt-ucsd** [comment]
Another note, I added a static contact form "success" page to the app. That is so we can redirect MF there if need be.

**Comment by mcritchlow** [comment]
@ucsdlib/developers - please review
