### ISSUE TITLE
Delete records from SHARE db

### ISSUE THREAD

**Issue by hweng** [ucsdlib/damspas#274]
From: Yoo, Ho Jung
Sent: Monday, January 09, 2017 1:19 PM
To: Montoya, Gabriela; Hutt, Arwen; Weng, Huawei
Subject: FW: two records to delete

Hi Gabriela and Huawei,
Just following up to see if you’ve got this covered? At the SHARE meeting last month, I brought up the need to delete a few of our records, and the two below were the only ones I could dig up at the moment. I think there was a third record somewhere, but I can’t find it – the one that had Gabriela and Joohee on it.
 
Ho Jung
 
From: Lauren Barker [mailto:lauren@cos.io] 
Sent: Tuesday, December 27, 2016 7:15 AM
To: Yoo, Ho Jung <hjsyoo@ucsd.edu>
Cc: Montoya, Gabriela <gamontoya@ucsd.edu>; Hutt, Arwen <ahutt@ucsd.edu>; Chris Seto <chris@cos.io>
Subject: Re: two records to delete
 
Hi Ho Jung,
 
At the meeting a couple questions came up about the UCSD data in SHARE: deleting records, missing records, and records missing information.
 
 
Deleting Records
 
The API can be used to delete records from SHARE. I believe Huawei got the Ruby gem set up while she was at COS; the records can be updated using their IDs and setting  is_deleted  to true. More details can be found in the documentation.
{
    "@id": "46227-0C4-522"
    // Omitted...
}
 
Missing and Incomplete Records
 
The problem records were coming from Datacite. The missing records are the result of the lull in harvesting when we switching from v1 to v2 of SHARE. The incomplete records are caused by Datacite's OAI-PMH metadata prefix which was used until month or two after the SHARE meeting in July. Both of these will be fixed once we back harvest Datacite using their 'oai_datacite' metedata prefix. 
 
 
Please let me know if you have any further questions or trouble deleting the records.
 
Best,
Lauren Barker
 
 
On Fri, Dec 16, 2016 at 2:05 PM, Yoo, Ho Jung <hjsyoo@ucsd.edu> wrote:
Hi Lauren,
I wonder if you can delete these records from the SHARE db:
 
Need to delete: https://share.osf.io/creativework/4622F-3EC-CC5
Need to delete: https://share.osf.io/creativework/46008-74E-592
 
They were pushed in error to SHARE during testing, I believe. I know for sure that the metadata is inaccurate.
 
Thanks,
Ho Jung

**Comment by hweng** [comment]
The delete requests for the two records were successful that got the correct response. But it still shows from OSF website UI. 
Just talked to osf developer Lauren about it that she said It will take some time to get through the queue. So I will check their website later.

**Comment by hweng** [comment]
Checked that the record is deleted by search: https://share.osf.io/discover?q=%22San%20Diego%20History%20Center%20Oral%20Histories%22

Currently, if go directly to the record it will still display (https://share.osf.io/creativework/4622F-3EC-CC5) , this is what the SHARE system current design, according to @laurenbarker,  they are in the process of deciding how a deleted record should look.

**Comment by mcritchlow** [comment]
Marking as closed per @hweng's last comments
