### ISSUE TITLE
Sync from Prod to QA

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damspas#278]
In preparation for the upcoming subject conversion, we need to get the QA environment directly in line with Prod, include data, indexes, packages, etc.

To Do:

- [ ] Disabled the QA bamboo plans for damsrepo, damsmanager, damspas, damspas private_config, and config
- [ ] Update all packages/dependencies to match production (e.g. ImageMagick, FFMpeg, ..)
- [ ] Sync Solr index from prod to qa
- [ ] Sync triplestore db from prod to qa
- [ ] Sync Filestore from prod to qa
- [ ] Deploy [env-variables](https://github.com/ucsdlib/env-variables) for qa
- [ ] Deploy [damspas](https://github.com/ucsdlib/damspas/tree/master) from master branch to qa
- [ ] Restart damsolrizer on QA
- [ ] Deploy [damsrepo](https://github.com/ucsdlib/damsrepo/tree/master) from master branch to qa
- [ ] Deploy [damsmamager](https://github.com/ucsdlib/damsmanager/tree/master) from master branch to qa

**WIP - will fill in details w/ @tmarconi @lsitu @rstanonik @jhriv**

**Comment by rstanonik** [comment]
Can I do a filestore sync now, so that it will be smaller and faster on the conversion date?
Same for solr, can I replicate from prod now, so smaller and faster later?
Are you ready for me to disable QA deployment for damsrepo and damsmanager now?
I assume John can deal with damspas deployment.

**Comment by lsitu** [comment]
@rstanonik Yes. I think we can do the syncs in any order for filestore, solr and the triplestore. And we can just disable QA auto deployments for damsrepo and damsmanager at anytime. Thanks.

**Comment by mcritchlow** [comment]
@rstanonik - I agree w/ @lsitu . If you can start updating QA to match Prod now it would be great and, as you said, shorten out sync times when we're ready to start testing.

**Comment by rstanonik** [comment]
I disabled the QA bamboo plans for damsrepo, damsmanager, damspas, damspas private_config, and config.

**Comment by mcritchlow** [comment]
@rstanonik - Thanks! I've updated the ticket description to note that and marked it done.

**Comment by rstanonik** [comment]
QA and staging use the same filestore.
Still okay if I start syncing it from prod?

**Comment by mcritchlow** [comment]
@rstanonik - That might be a problem. One of the mail goals in this effort is to keep staging free so @ucsdlib/domm can continue work on testing ingest of new collections. Do we have space for QA to have its own filestore? This can be temporary if needed, as we'll really just need it for this project.

**Comment by rstanonik** [comment]
Yes, we have space.
I'll let you know when it's copied (estimate five days).

**Comment by mcritchlow** [comment]
@rstanonik did the sync/copy finish?

**Comment by stanonik** [comment]
Yes, the rsync finished.
I'm changing the mounts and copying some other files (assets?  opaque?) from staging to a qa mount.
Juliana is copying the triplestore now.
If QA isn't ready this afternoon, it will be on Friday.
(I'm out Thursday.)

**Comment by jgorney** [comment]
The triplestore db tables (dams_triples and events_triples) have been sync'd from prod to QA.

**Comment by rstanonik** [comment]
QA was mounting other staging space (assets, opaque, and zoomify), so to keep QA from overwriting those spaces, I'm making copies for QA.  Then I need to make sure the QA config files don't reference staging for solr and other things.

**Comment by mcritchlow** [comment]
Sounds great, thanks @rstanonik

**Comment by rstanonik** [comment]
QA is up, except it is still using staging zoomify tiles because those take time (maybe days) to copy.
I'll let you know when I have an estimate of the time to copy.
Copied from production (localstore, solr, triplestore, assets, opaque).

**Comment by rstanonik** [comment]
Copy of prod zoomify for QA is about 16% done, so estimate another ten days.
It takes time to copy 40 million files.

**Comment by rstanonik** [comment]
zoomify finished syncing yesterday.
QA is now using its own copy of zoomify on libraryqa and lib-ingest-qa.
The other servers don't mount a zoomify share.

**Comment by mcritchlow** [comment]
Where are we on this ticket? @lsitu @rstanonik @jhriv It looks like the data syncing needs happened, but the deploy items on the checklist either haven't happened or haven't been marked as complete.

**Comment by lsitu** [comment]
@mcritchlow I think it should be very closed now. @rstanonik @jhriv What else do we need to wrap up the ticket? Thanks.

**Comment by jhriv** [comment]
env-variables are deployed. It looks like hydrahead-prod and hydratail-prod are using OS packages for ffmpeg and ImagMagick, so versioning should be consistent already.

**Comment by mcritchlow** [comment]
@jhriv ok great, thanks. I checked the dependencies item then.

So I suspect then we just need Bamboo back up and running so that we can get dams manager and damsrepo deployed, and we could do damspas anytime?

**Comment by mcritchlow** [comment]
@jhriv @rstanonik @lsitu - so with the successful testing of Solr replication in #279 I'd like to circle back on whether this QA environment is ready to go for the subject conversion. See my last comment, is that where we are at the moment?

**Comment by lsitu** [comment]
@mcritchlow I think we should be ready for Subject Conversion now since @rstanonik and @jhriv already updated all components with SOLR indexing working nicely. Are we Okay to just deploy the apps from the develop branch?

**Comment by mcritchlow** [comment]
@lsitu Yep, I think deploying from develop makes sense for now. At some point we will likely lock it to master or specific release branches so we can mirror production. But 👍  on develop for now.

**Comment by rstanonik** [comment]
I assume this is finished.

**Comment by mcritchlow** [comment]
@rstanonik , @jhriv: @ucsdlib/domm are going to be ready to start doing test data cleanup work in QA. 

Can we request a sync back to QA again from production, please? ;)

**Comment by jgorney** [comment]
Does this include the triplestore tables?  When would you like this done?

**Comment by mcritchlow** [comment]
@jgorney - yes please! and as far as timing, I think if we can get this started in the next few days that would be great. so not super urgent, just as soon as convenient for you all.

**Comment by jgorney** [comment]
I can start my part anytime.  @rstanonik and @jhriv , do I need to time this with any syncing you're doing?

**Comment by rstanonik** [comment]
It will probably take  four days for the localStore sync.  I don't see any need for @jgorney  to wait.  I'll have a better estimate of time for the localStore sync after it has been running for a while.  I'm about to start it now.

**Comment by jgorney** [comment]
OK I'll get mine started.

**Comment by jgorney** [comment]
The triplestore table sync from prod to QA is complete.

**Comment by mcritchlow** [comment]
Thanks @jgorney !

**Comment by rstanonik** [comment]
The file copy is 80% done.
Should finish by tomorrow.

The solr sync is done.

**Comment by rstanonik** [comment]
Hmm, I also need to sync prod zoomify to qa zoomify.

**Comment by rstanonik** [comment]
The localStore finished.
I started the zoomify sync.
I'll have an estimate after it has run for a while.

**Comment by mcritchlow** [comment]
Great, thanks for the updates @rstanonik :+1:

**Comment by rstanonik** [comment]
zoomify is about 25% done.
Estimate another six hours.

**Comment by rstanonik** [comment]
The zoomify sync finished.
The sync from prod to qa finished.
