### ISSUE TITLE
R&D: Solr solution for subject conversion

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damspas#279]
Problem: The upcoming subject conversion project is going to require a complete re-index of everything in Solr. In the past, we've seen this take weeks and negatively impact the application performance for end users.

To Do: Evaluate, test, and recommend a solution to this issue. This could be using Solr replication, or another means for shielding the public from the heavy batch updates.

Environment: Please test this out on the upgraded QA environment once it is ready via #278

**Comment by mcritchlow** [comment]
@rstanonik @jhriv @lsitu @tmarconi 

Adding in our email discussion below, can we carry it forward in this ticket?

```
Hi Ron,
 
Yeah, something like that is generally what I was thinking. Once QA is up to date, perhaps we can test this out there?
 
We’ve got a new Sprint starting today, and Longshou could probably put some cycles into testing this out. We’ve got this ticket [1], perhaps I could make another just for this effort?
 
Other thoughts or ideas?
 
Matt
 
From: "Stanonik, Ronald" <rstanonik@ucsd.edu>
Date: Wednesday, February 15, 2017 at 9:49 AM
To: Matt Critchlow <MCritchlow@ucsd.edu>, "Situ, Longshou" <LSitu@ucsd.edu>, John Robinson <jhriv@ucsd.edu>
Cc: "Marconi, Tim" <tmarconi@ucsd.edu>
Subject: RE: Subject Reconciliation - DAMS4
 
What about updating a master index and having hydra use an index that is replicated on periodically or when required?
 
Ron
 
From: Critchlow, Matt 
Sent: Wednesday, February 08, 2017 9:40 AM
To: Situ, Longshou <LSitu@ucsd.edu>; John H. Robinson, IV <jhriv@ucsd.edu>; Stanonik, Ronald <rstanonik@ucsd.edu>
Cc: Marconi, Tim <tmarconi@ucsd.edu>
Subject: Subject Reconciliation - DAMS4
 
Hi everyone,
 
Tim and I were in a meeting yesterday with Arwen and Gabriela to discuss a pretty significant upcoming project for the DAMS 4 to 5 transition. Essentially, all of the subjects that are currently “complex”, which use pre-coordinated headings like “Undergraduate Sciences Building (Revelle College)--Design and construction--Photographs”, are going to get broken up into individual subjects. This will simplify our data as we move towards Fedora4/DAMS5 and more importantly make the browsing experience better for users.
 
The work involved here is going to require essentially a complete overhaul of our repository and Solr index. We’ve started outlining a larger series of steps in a ticket [1], but one of the main things we would ideally like to try and avoid is dragging down the UI for users while the updates are being made in production. As you all know, global Solr updates take a very long time, and have a very negative impact on front end performance.
 
So, we’re wondering what ideas you all have for how we might go about this. For example, can we do something with Solr replication so that the Hydra app uses the “old” Solr index while a replicated index gets updated on the side and then, once complete, we have the Hydra app point to the updated index. We have some time on this, but it would be great if we can start thinking about this now and what our options might be. Ideally, it might be an architecture decision we could port into our DAMS5 system as well, since I highly doubt this will be the last global update we ever do..
 
Thanks,
 
Matt
 
 
1.      https://github.com/ucsdlib/damspas/issues/245
```

**Comment by lsitu** [comment]
@rstanonik It looks like we still have SOLR 4 on prod. Do we have any plans to change it to use SOLR 5?

**Comment by lsitu** [comment]
@mcritchlow @rstanonik I think using Solr replication sounds doable. But we may need to move the damsolrizer to another server instead of running it on the same server (lib-hydrahead-prod) along with the hydrahead app (damspas ), and setup a master server for damsolrizer to update indexes. This may require us to deploy two copies of damspas code base, one for the damspas, and the other for damsolrizer with different configuration in solr.yml for the master SOLR server. 
What do you think?

**Comment by mcritchlow** [comment]
@lsitu I suspect you're right on that, given the dependency/coupling between damsolrizer and the codebase as a whole. Doesn't feel ideal, perhaps it's our best option at the moment?

**Comment by rstanonik** [comment]
Hi Longshou,
Sorry, I keep overlooking that.
I’m out Thursday, so I’ll try to do it early next week.
Ron

**Comment by lsitu** [comment]
@rstanonik Thanks. We may need @jhriv's help to update and deploy [env-variables](https://github.com/ucsdlib/env-variables/blob/master/group_vars/DHH/vars.yml#L99) for it once we are ready to move to SOLR 5.

**Comment by lsitu** [comment]
@rstanonik What's your thought regarding setting up the master-slave SOLR like that on prod, see @mcritchlow's [#issuecomment-281469515](https://github.com/ucsdlib/damspas/issues/279#issuecomment-281469515)?

**Comment by jhriv** [comment]
https://github.com/ucsdlib/env-variables/compare/feature/solr5-prod?expand=1

**Comment by mcritchlow** [comment]
@lsitu - Similar to your updated diagram in the Solr5 ticket, would you mind attaching a proposed diagram into this ticket that would reflect Solr replication solution we've been discussing? Might help everyone to have a visual for further discussion and testing.

**Comment by lsitu** [comment]
@mcritchlow I've updated the ingest diagram for the SOLR replication solution, it's in lucidchart and we can update it for the changes we need: https://www.lucidchart.com/invitations/accept/79e9127b-d510-4cf2-81f4-189b4be11376
It seems like adding the slave solr to lib-hydrahead and deploy the damsolrizer to lib-hydratail could fit into our current architecture well. 

Here is the jpeg version:
 ![ingestdiagram_solr-master-slave](https://cloud.githubusercontent.com/assets/2430784/23233160/d33463ce-f902-11e6-8e82-9fea196ec1f9.jpeg)

**Comment by lsitu** [comment]
@ucsdlib/operations Do you have any suggestions on implementing the [master-slave SOLR](https://github.com/ucsdlib/damspas/issues/279#issuecomment-281810435) solution above on QA to test it out? Please feel free to update the ingest diagram if you see something else works better. Thanks.

**Comment by lsitu** [comment]
@rstanonik Anything else do you expect me to help on setting up the master-slave SOLR model on QA? Please let me know if we are ready to test it out. Thanks.

**Comment by rstanonik** [comment]
I installed a slave solr 5 on lib-hydrahead-qa, which syncs from the master solr 5 on lib-hydratail-qa.
It syncs every minute.

According to your diagram, two things need to change.

1) John or someone needs to change the environment variable APPS_DHH_QA_SOLR_URL on lib-hydrahead-qa, so that it points to solr on lib-hydrahead-qa, rather than lib-hydratail-qa.

2)damsolrizer needs to be installed on lib-hydratail-qa, which I susppose means that damspas must be deployed to lib-hydratail-qa.  John should be involved in that too.  

Does that sounds like what your diagram expects?

If so, then I'll talk to John about items 1 and 2.

**Comment by lsitu** [comment]
@rstanonik Yes. It's exactly like what the diagram expects. 
For step 1, we may need to restart the hydrahead (damspas) once environment variable APPS_DHH_QA_SOLR_URL is updated to lib-hydrahead-qa. And for 2, we may need to deploy [env-variables](https://github.com/ucsdlib/env-variables) and [damspas](https://github.com/ucsdlib/damspas) to lib-hydratail-qa.

I think we had better finish step 2 first and then do step 1 to update environment variable APPS_DHH_QA_SOLR_URL to point to lib-hydrahead-qa for damspas app. Thanks.

**Comment by rstanonik** [comment]
The env-variable APPS_DHH_QA_SOLR_URL deployed to lib-hydratail-qa should point to lib-hydratail-qa so that damsolrizier updates the master solr on lib-hydratail-qa, correct?

And the env-variable APPS_DHH_QA_SOLR_URL deployed to lib-hydrahead-qa should point to lib-hydrahead-qa so damspas access the slave solr.

Maybe there should be two env-variables APPS_DHH_QA_SOLR_MASTER_URL and APPS_DHH_QA_SOLR_SLAVE_URL

**Comment by lsitu** [comment]
@rstanonik Yes. But it may not be straight forward to have two parameters like APPS_DHH_QA_SOLR_MASTER_URL and APPS_DHH_QA_SOLR_SLAVE_URL for environment variable APPS_DHH_QA_SOLR_URL. I am not sure whether we can just simply make it through local configuration (something like the vault values for credentials) or we have to create another environment variable to deploy it, something like qa_solr_master, qa_solr_slave etc instead of the qa environment we have now. What's your thoughts, @jhriv ?

**Comment by lsitu** [comment]
@jhriv @rstanonik What's your plans for configuring the master/slave solr for damspas on lib-hydratail-qa and lib-hydrahead-qa? Thanks.

**Comment by jhriv** [comment]
Since any DHH needs to talk to one and only one SOLR, there is one and only one SOLR url environmental variable. https://github.com/ucsdlib/env-variables/pull/11 adds the feature to override a variable per-host, which is how we can get DHH on head to use a different SOLR url than DHH on tail.

**Comment by rstanonik** [comment]
QA damspas is now using solr slave on hydrahead, which sync's every minute from solr master on hydratail.
John is working on creating ansible playbook

**Comment by mcritchlow** [comment]
Was this supposed to be closed @rstanonik @lsitu ?

**Comment by rstanonik** [comment]
No, I started a comment, but then decided not to comment and closed the comment, I guess I closed the issue.

**Comment by lsitu** [comment]
@rstanonik Are we ready to test the master/slave SOLR sync now or not?

**Comment by rstanonik** [comment]
No, I need @jhriv to deploy damspas to lib-hydratail-qa, so damsolrizer can run there

**Comment by jhriv** [comment]
My understanding, damsolarizer is part of DHH, which heaven deploys. Is there a heaven plan to deploy DHH to lib-hydratail-qa? If not, what project should that issue be opened on?

@ucsdlib/developers

**Comment by lsitu** [comment]
@jhriv @rstanonik I don't think we have other tickets setup for this master/slave SOLR solution but set it up to make it work here. I can work on anything that you think it's needed for you to deploy DHH to lib-hydratail-qa. We have the following configuration in damspas for DHH QA deployment at this time: https://github.com/ucsdlib/damspas/blob/develop/config/deploy/qa.rb.

Will it work if I add "server 'lib-hydratail-qa.ucsd.edu', user: 'conan', roles: %w{web app db sitemap_noping}" after [qa.rb#L3](https://github.com/ucsdlib/damspas/blob/develop/config/deploy/qa.rb#L3) for lib-hydratail-qa? Or we have to set it up as a new environment to deploy it for lib-hydratail-qa.ucsd.edu?

**Comment by rstanonik** [comment]
@jhriv Comparing with lib-hydrahead-qa, I don't see any special firewall or authorized_keys entries, but I wasn't involved after the switch to circleci(?).

I created /pub/capistrano and make conan.conan the user and group owner, although maybe you want that creation in ansible too.

**Comment by jhriv** [comment]
@VivianChu Do we need to make a new deploybot stanza for DHH on lib-hydtatail-qa?

**Comment by VivianChu** [comment]
@jhriv - if you use the command "deploybot deploy damspas to qa", it will deploy to lib-hydrahead-qa

https://github.com/ucsdlib/damspas/blob/develop/config/deploy/qa.rb#L3

We can change that line in qa.rb to deploy to lib-hydratail-qa

**Comment by jhriv** [comment]
@VivianChu We now need it on both, though.

**Comment by VivianChu** [comment]
@jhriv - I think we can create another deploy file like qa.rb in damspas and add that environment to deploybot.

**Comment by jhriv** [comment]
@VivianChu   Is there any way to get it to deploy to both? Like perhaps loop over a list of hosts in the QA environment?

**Comment by rstanonik** [comment]
Or can the damsolrizer piece become a separate deploy?

**Comment by jhriv** [comment]
Which would also have to go to both

**Comment by VivianChu** [comment]
@jhriv - we can try %w{server1 server2 server3}  in that qa.rb to deploy to multiple server

**Comment by jhriv** [comment]
@VivianChu sounds good to me.

**Comment by rstanonik** [comment]
damsolrizer only runs on lib-hydratail-qa now

**Comment by lsitu** [comment]
@rstanonik That's great! What changes we need for the deployment?

**Comment by rstanonik** [comment]
@lsitu Sorry, I meant to say "damsolrizer will only run on lib-hydratail-qa", after John/Vivian deploy damspas to lib-hydratail-qa.

**Comment by lsitu** [comment]
@VivianChu Should we update the qa.rb for damspas now to give it a try? It looks like adding another line for server like "server 'lib-hydratail-qa.ucsd.edu', user: 'conan', roles: %w{web app db sitemap_noping}" is worth us to try too if it doesn't work with %w{server1 server2 server3}.

**Comment by VivianChu** [comment]
@lsitu - Yes, we should give it a try.  Do you want to make that change? Or you want me to do it?

**Comment by lsitu** [comment]
@VivianChu Are you convenient to do it? Thanks.

**Comment by VivianChu** [comment]
@lsitu I made that change in the branch.  Are we ready to deploy it both servers now? I can run the deploy command if we're ready.

**Comment by lsitu** [comment]
Thanks @VivianChu.
@jhriv @rstanonik Would you like us to test it on QA now?

**Comment by jhriv** [comment]
:+1: yes, please do

**Comment by jhriv** [comment]
With this change, damsolarizer, which is part of DHH, will run only on hydratail now?

**Comment by lsitu** [comment]
Yes. We should remove the damsolarizer on hydrahead and start it on hydratail. Is damsolarizer restarted by the bamboo at this time?

**Comment by lsitu** [comment]
@VivianChu It looks like you've got damspas deploy on lib-hydratail-qa! I see the damspas repository is created there on /pub/capistrano.

**Comment by VivianChu** [comment]
@lsitu - I will make a PR to merge this change.

**Comment by jhriv** [comment]
https://github.com/ucsdlib/env-variables/pull/15 has been deployed, things probably work now.

**Comment by rstanonik** [comment]
John got damsolrizer running on lib-hydratail-qa!

**Comment by lsitu** [comment]
I just tested it on QA to index a couple of records and it works! Thanks @jhriv, @rstanonik and @VivianChu for working it out so nicely!

**Comment by mcritchlow** [comment]
Nice job everyone! 👍 

As an acceptance test to close this out, @lsitu and @gamontoya will coordinate a larger test in QA involving indexing a larger number of records and monitoring the DC application browsing experience. This will happen early next week.

**Comment by lsitu** [comment]
@gamontoya @mcritchlow I've added more than 18,000 records to the queue for SOLR reindexing on QA, and some records are indexed and I am adding more records in SIO to the queue. I think it's ready for test now: http://libraryqa.ucsd.edu/dc. Thanks.

**Comment by gamontoya** [comment]
@lsitu @mcritchlow I saw no slowness or lagging as I ran searches and navigated around on QA. I checked sporadically throughout the day.
