### ISSUE TITLE
Delete duplicate object

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#280]
Permanently delete a the following duplicated object (ingested twice erroneously).
- bb71688450

**Comment by lsitu** [comment]
@gamontoya It looks like I can only find only one object with title "Le philosophe indifferent" or bib number b3396889, which is binding to object http://library.ucsd.edu/dc/object/bb71688450. Could you confirm the deletion?

**Comment by gamontoya** [comment]
Confirming that you delete http://library.ucsd.edu/dc/object/bb71688450 entirely. The correct image is bound to a different bib number.

**Comment by lsitu** [comment]
@gamontoya I've deleted object http://library.ucsd.edu/dc/object/bb71688450, and it should be gone now.

**Comment by gamontoya** [comment]
@lsitu Thank you!
