### ISSUE TITLE
DAMS 4 Data Sync - Sprint 5, 2017

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#286]
### Descriptive summary

- Requesting a DAMS data sync from Production back to the **Test** environment
- This should include the triplestore, Solr, filestore, etc.

**Comment by gamontoya** [comment]
@rstanonik I could assign to Juliana as well because Matt needs to add her to our github repos.

**Comment by rstanonik** [comment]
I'm syncing solr and the filestore from prod to staging.
Juliana is syncing the triplestore.
I'll give you an estimate of the time for the filestore sync after it has run for a while.

**Comment by rstanonik** [comment]
solr sync finished.
filestore sync is 68% done, estimate another half an hour.

**Comment by jgorney** [comment]
The triplestore data is sync'd, just waiting for indexes to build.

**Comment by rstanonik** [comment]
The filestore sync finished.
I guess not much changed since the last sync.

**Comment by gamontoya** [comment]
@rstanonik That was fast. Thanks Ron!
