### ISSUE TITLE
Make dams:license display publicly

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#287]
### Descriptive summary
Make CC licenses display in the object's metadata view. 

### Rationale
Ho Jung noted that the CC licenses to RDCP objects are not being displayed. If you log in to curator, it is displayed. Ryan thought that inserting dams:Permission=display in the RDF would solve the issue, but it did/does not.

`<dams:permission>`
    `<dams:Permission>`
       `<dams:type>display</dams:type>`
    `</dams:Permission>`
`</dams:permission>`

**Comment by gamontoya** [comment]
@mcritchlow Can you assign to Longshou for when he's back from Code4Lib?

**Comment by lsitu** [comment]
@gamontoya Can you show me an example that is in question? Thanks.

**Comment by gamontoya** [comment]
@lsitu Yes, here is an example:
- http://library.ucsd.edu/dc/object/bb78857130

**Comment by lsitu** [comment]
Thanks Gabriela. Yes, I see the weird issue with the license missing from the public view.

**Comment by lsitu** [comment]
@gamontoya It looks like that license, statute, and other_rights are displayed for curator only. Would you like to just make license for public access but leave the other two for curator access only?

**Comment by gamontoya** [comment]
@lsitu Do you have examples of objects that use statute and other rights?

**Comment by lsitu** [comment]
@gamontoya I can't find any objects that use statute so I think we can just ignore it. Here is an example that has other rights:
http://library.ucsd.edu/dc/object/bb5257003c

**Comment by mcritchlow** [comment]
FWIW, I believe this call was made in an (old) JIRA ticket: https://lib-jira.ucsd.edu:8443/browse/DHH-225 Reading back through that though, it seems odd that we chose to made the license note curator only.

Tagging w/ this Sprint milestone

**Comment by remerjohnson** [comment]
Looking back through the archives, the `display` value for Permission might be misleading. From [DOMM's LiSN](https://lisn.ucsd.edu/display/DOMM/RightsAction%2CPermission%2C+Restriction+type+controlled+value+list), it seems to indicate `display` means UCSD-only, and is a separate notion from "visibility".  

Unfortunately there are many old docs lying around and hard to tell which are definitive. I believe `statute` was deprecated once the current copyright/access was planned out, because it used to be a separate note along with a country that indicated where that statute was from? 

Also, I _believe_ the CC licenses display publicly when you specify it as an override in DAMS Manager at time of ingest. This problem occurs when you edit the RDF, so might be sidestepping some logic somewhere (combined with above possibility of `display` actually limiting visibility).

**Comment by mcritchlow** [comment]
@remerjohnson Those classes can impact the access control state of an object, but not the display (or visibility) of individual properties. The display of individual properties is [hard-coded](https://github.com/ucsdlib/damspas/blob/3bb7eb57c071b713f7c7ad27d37a1a30bc073c96/app/views/shared/fields/_show_raw.erb#L88-L92), so to speak, in the application. As @lsitu noted above, at the moment only curators will be able to see them. An overrides via DAMS Manager wouldn't have an impact. 

I do agree that the `display` name can be misleading. I look forward to moving away from that set of classes and access control logic :)

**Comment by remerjohnson** [comment]
That gives me hope this can be solved easier than I expected. And also happy we'll have a better system for this soon.

**Comment by lsitu** [comment]
@gamontoya @remerjohnson Do we need to add OtherRights note for public view or not? I think we have more than 5000 objects that have OtherRights which will override the object access, but only those metadataDisplay object will have a note like "Please contact Mandeville Special Collections & Archives at spcoll@ucsd.edu or (858) 534-2533 for more information about this object." that is displayed on the curator view at this time. 
With the current damspas implementation, if we decide to add OtherRights for the public view, only those objects with metadataDisplay access will have a OtherRights note to be displayed on the object viewer.

**Comment by gamontoya** [comment]
@remerjohnson @arwenhutt Are there cases where the otherRights is private info?

**Comment by gamontoya** [comment]
@lsitu Wouldn't this be an example of something we would **not** want to display publicly?

`<dams:otherRightsNote>Suppress public discovery</dams:otherRightsNote>`

**Comment by remerjohnson** [comment]
@gamontoya @lsitu I didn't know we still had `otherRightsNote`... it wasn't in the [Access Override Mapping](https://lisn.ucsd.edu/display/DOMM/Access+Override+Mapping) so is out of sight/mind. Maybe other DOMM people would know more

**Comment by GregReser** [comment]
We don't need to display otherRightsNote if it's something like  "Please contact Mandeville Special Collections..."  because we have contact info in "Digital Object Made Available By"

I bet most otherRightsNote values are not very useful and do not need to be displayed.

**Comment by gamontoya** [comment]
@lsitu I agree with Greg so let's not display otherRights notes.

**Comment by lsitu** [comment]
@gamontoya Sure. Do we need to remove otherRights notes from the curator view or leave it as is for now?

**Comment by gamontoya** [comment]
@lsitu No. Please leave as is - curator view. Thanks.

**Comment by lsitu** [comment]
Okay, I've created PR https://github.com/ucsdlib/damspas/pull/290 to make dams:license display publicly and leave otherRights as is in the curator view. Thank you all.
