### ISSUE TITLE
Deploy damspas 1.69

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damspas#291]
### Descriptive summary

Deploy version 1.69

### Related work

- [ ] #290 Display License publicly

**Comment by lsitu** [comment]
@ucsdlib/domm We've deployed damspas 1.69 to staging. It's ready for review now. Since Gabriela is out today, could anyone review it? Please check the action for reviewing in the "Related work" section above  if it's ready for prod deployment. Thanks.

**Comment by GregReser** [comment]
@lsitu I'll test it.

**Comment by GregReser** [comment]
@lsitu #290 Display License publicly is resolved.
I checked several objects from different collection (as a public user) and the License value displayed correctly.
I didn't see any other problems during my tests.

**Comment by lsitu** [comment]
Thanks @GregReser . Should we deploy it to prod?

**Comment by gamontoya** [comment]
@lsitu Approved for production. Thank you!

**Comment by lsitu** [comment]
Thanks Gabriela.
@jhriv I've merged the changes on release/1.69 to the master branch. It's ready for prod deployment now. Thanks.

**Comment by jhriv** [comment]
Deployed.
