### ISSUE TITLE
Updates to Home Page

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#296]
### Descriptive summary

RDCP refers to “research data collections” as a category of content within the DC, but does not refer to Research Data Collections as a branding. We refer to the DAMS as, “UC San Diego Library Digital Collections”, both as publisher (in the context of data citations and DOI minting) and as a repository. But a user entering the DC from the homepage finds that the portal is called “Digital Collections”, and that the content behind the orange button on the left is called “UC San Diego Library Digital Collections”. This could be confusing for anyone who has seen a citation for a research data collection in the DAMS, but then browses the DC from the homepage. Example: Al-Delaimy, Wael K (2015): California Tobacco Survey (CTS). UC San Diego Library Digital Collections. http://dx.doi.org/10.6075/J0H41PBM.

### Rationale

The DAMS as a whole is technically the “repository”, while the two categories of content only differ by “Program” or “Category” or “Content”. It would be more accurate to label the dichotomy by program of stewardship (i.e., Digital Library Development Program and Research Data Curation Program) or by category (e.g., Library collections or Cultural heritage collections, and Research data collections), rather than by “Repository”

### Approved Updates

1. Change DIGITAL COLLECTIONS in the header to say LIBRARY DIGITAL COLLECTIONS
In citations, the publisher is UC San Diego Library Digital Collections. Since the UC San Diego logo is on the right, UC San Diego text does not need to be repeated on the left.

![1](https://cloud.githubusercontent.com/assets/4314914/24622787/17b2179a-185b-11e7-8e7c-f9adf8deb6db.png)

2. Delete this entire section of text. Wording is a somewhat awkward.

![2](https://cloud.githubusercontent.com/assets/4314914/24622812/34e2c4fe-185b-11e7-834e-220c96113922.png)

3. Text above buttons
    a. Delete
    b. Delete

4. Get rid of logos in buttons and replace with text
    a.	Library collections
    b.	Research data collections

5. Text below buttons
    a.	Move to sit above the button
    b.	Move to sit above the button

With the proposed changes, the bottom fold will end up looking like this:

![3](https://cloud.githubusercontent.com/assets/4314914/24622937/a13cce38-185b-11e7-8bc0-c7d80dde4b1f.png)

6. Make the font and font size more consistent?  Right now, the final line is much smaller than the rest and the font appears to be different when it all should be consistent.

![4](https://cloud.githubusercontent.com/assets/4314914/24622986/cc3698c6-185b-11e7-86af-898348bfe4a6.png)

**Comment by dt-ucsd** [comment]
Just noting as part of this work I updated old non-HTTPS links to use HTTPS.

**Comment by dt-ucsd** [comment]
Here are some screenshots of the update:

**[Desktop]**
![dams-home-desktop-fullpage](https://cloud.githubusercontent.com/assets/2448340/25204542/cead4280-2512-11e7-9e64-62361c70c979.png)

**[Tablet]**
![dams-home-tablet-fullpage](https://cloud.githubusercontent.com/assets/2448340/25204544/ceb16356-2512-11e7-944a-fc129eb0e8fa.png)

**[Phone]**
![dams-home-phone-fullpage](https://cloud.githubusercontent.com/assets/2448340/25204543/ceae0e4a-2512-11e7-8736-bdc7c0cef4ef.png)

Note that I tweaked the design of the bottom half of the page to better suit the current content. I also used styles/colors that in line with the new PWS redesign. Opted for grays to help the featured background image pop a bit better than it used to against the blue.

**Comment by dt-ucsd** [comment]
Note that I tweaked the design of the bottom half of the page to better suit the current content. I also used styles/colors that in line with the new PWS redesign. Opted for grays to help the featured background image pop a bit better than it used to against the blue.

**Comment by dt-ucsd** [comment]
@gamontoya I just noticed that we have the "Currently totaling..." copy in two place on the home page (above the search bar and above the footer). Thoughts?

**Comment by dt-ucsd** [comment]
Here is a screenshot of the different hover states (dark for hover):

![image](https://cloud.githubusercontent.com/assets/2448340/25242842/e854497a-25af-11e7-8ffd-6ad79f6b0355.png)

**Comment by gamontoya** [comment]
This is fantastic! I like it very much David. Excellent work.

**Comment by gamontoya** [comment]
@mcritchlow @dt-ucsd My thought is to get rid of the "Currently totaling..." from the bottom.

**Comment by mcritchlow** [comment]
@gamontoya - yep, totally agree on removing the bottom entry.

**Comment by dt-ucsd** [comment]
Here is a screenshot of the home page with the "Currently..." container removed:

![image](https://cloud.githubusercontent.com/assets/2448340/25288335/d758afd8-2679-11e7-9375-b4e945a4b5b8.png)

**Comment by dt-ucsd** [comment]
If it looks good let me know and I will submit a PR.

**Comment by mcritchlow** [comment]
LGTM, but will of course let @gamontoya make the call

**Comment by gamontoya** [comment]
@dt-ucsd Go for it!
