### ISSUE TITLE
Search navigation not working

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#297]
### Descriptive summary

We have lost the ability to navigate through search results. There should be a search pager at the top of search results.

### Rationale

This was working in the past, so there must be a bug. People need to be able to navigate with the search pager instead of having to use their browser's back button.

### Expected behavior

- Search for "fish"
- Get search results
- Click on an object
- See search pager at top for navigation

### Actual behavior
- Search for "fish"
- Get search results
- Click on an object
- No search pager

### Screen shots

**Now**

![pagernow](https://cloud.githubusercontent.com/assets/4314914/25253411/bb8505a8-25d5-11e7-8930-1f7f8b179b4c.png)

**Before**

![pager](https://cloud.githubusercontent.com/assets/4314914/25253416/bf09f814-25d5-11e7-89ef-db158aab0881.png)

**Comment by VivianChu** [comment]
@gamontoya - Could you try again?  It's working fine now.  Thanks
![fishsearch](https://cloud.githubusercontent.com/assets/1864660/25628755/3ab3bfc8-2f1c-11e7-89bc-da1400ce9398.png)

**Comment by gamontoya** [comment]
@VivianChu  @cgarciaspitz Thank you, Vivian. Confirming that the issue has been fixed.
