### ISSUE TITLE
Permanently delete object

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#308]
### Descriptive summary

Per decision in conversation, please delete the following object:

https://library.ucsd.edu/dc/object/bb40300199

**Comment by gamontoya** [comment]
Ho Jung reported this to me, and I didn't dig deep to notice that it is a consent form. How did this get in the DAMS to begin with?

I'd be more than happy to have this object deleted for now, or?

**Comment by remerjohnson** [comment]
:+1: to delete

**Comment by gamontoya** [comment]
Decision made to delete object.

**Comment by lsitu** [comment]
@gamontoya I've deleted the object https://library.ucsd.edu/dc/object/bb40300199 and it should be gone now.

**Comment by gamontoya** [comment]
@lsitu Thank you.
