### ISSUE TITLE
Re-create and replace derivatives

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#315]
### Descriptive summary

Calisphere reports an issue with our access JPEG from the Spanish Civil War Stamp collection (_2.jpg is corrupted with byte stream format). 

Re-create the derivatives for the following object:

- https://library.ucsd.edu/dc/object/bb9045517h.

### Note
Once this work is done, Gabriela will reharvest this collection for Calisphere.

**Comment by gamontoya** [comment]
@lsitu Adding to your queue if you have time.

**Comment by lsitu** [comment]
@gamontoya No problem and I'll fix it.

**Comment by lsitu** [comment]
@gamontoya I've re-created the derivative for the corrupted _2.jpg (https://library.ucsd.edu/dc/object/bb9045517h/_2.jpg). Other derivatives looks good.

**Comment by gamontoya** [comment]
@lsitu Perfect. Thank you!
