### ISSUE TITLE
Delete duplicate collection level record and objects

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#316]
### Descriptive summary

Delete this stub collection level record and its attached 12 objects:

https://library.ucsd.edu/dc/collection/bb6657586q

- bb0718953w
- bb28008966
- bb52923763
- bb5292384j
- bb5770205w
- bb6009111t
- bb73401909
- bb7442575w
- bb7715606m
- bb8295816m
- bb8637127d
- bb9149065n

**Comment by lsitu** [comment]
@gamontoya I've removed the stub collection and all 12 objects attached rom prod and they are gone now.

**Comment by gamontoya** [comment]
@lsitu @arwenhutt Confirming that this work is complete. Thank you!
