### ISSUE TITLE
Dedupe collection titles in Research Data Collections

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damspas#319]
### Descriptive summary

Some of the RDCP collection titles appear twice in the RDF. For example, http://library.ucsd.edu/dc/collection/bb0070711k/data and http://library.ucsd.edu/dc/collection/bb5940732k/data. This may be an error that was systematically introduced when the default Creative Commons license was applied to RDCP collections.
It’s not clear if there’s a negative downstream consequence of the duplicated titles.

**Comment by gamontoya** [comment]
@hjsyoo Can you tell me if this request is for a sweep of *ALL* RDCP collections? Is this global or just these two objects?

**Comment by hjsyoo** [comment]
Yes, please sweep all RDCP collections. I was told it may be a global occurrence, but these are the two I'm aware of.

**Comment by lsitu** [comment]
@hjsyoo Where can I find some source metadata that could produce the dup title issue?

**Comment by lsitu** [comment]
@hjsyoo I think there should be another title provided in the source metadata in addition to the title in the submitted form that contributes to the dup titles. I've created a [PR](https://github.com/ucsdlib/damsmanager/pull/156) to use the the one provided in the  source metadata to override the one submitted in the form.
@mcritchlow The PR https://github.com/ucsdlib/damsmanager/pull/156 is ready for review now. Thanks.

**Comment by hjsyoo** [comment]
@lsitu Thanks - it sounds like you don't need a source metadata example, then (your request from 2 hrs ago)?

**Comment by lsitu** [comment]
@hjsyoo I believe it's fixed and I don't need the example now. But let me know if it's a different case. Thanks.

**Comment by GregReser** [comment]
@lsitu Having the collection title on the collection import form causes some confusion, if it is also in the spreadsheet.  Would it be hard to just remove it from the form?  It seems like it would be better to always take the title from the spreadsheet.

**Comment by lsitu** [comment]
@GregReser Yes, now we are using the one from the spreadsheet if it's provided. I could hide it from the form if that works better.

**Comment by hjsyoo** [comment]
@lsitu Has this fix been deployed yet? We're seeing duped titles in EZID now, and are wondering if this fix will remove the EZID issue.

**Comment by lsitu** [comment]
@hjsyoo No. It will be deployed to staging tomorrow when the sprint ended.

**Comment by hjsyoo** [comment]
Thanks @lsitu

**Comment by lsitu** [comment]
@GregReser I've added a commit to remove the collection title from the collection import form, see PR https://github.com/ucsdlib/damsmanager/pull/159.
@mcritchlow The PR is ready for review now. Thanks.

**Comment by hjsyoo** [comment]
@lsitu Sorry, I'm still confused about where the work was done. On July 6, I sent the following list of duped titles to @remerjohnson, because we were trying to figure out why an EZID record generated a duped title.
Fresno: https://library.ucsd.edu/dc/collection/bb22212199/data
CSC: https://library.ucsd.edu/dc/collection/bb0070711k/data
SOAS: https://library.ucsd.edu/dc/collection/bb6282674b/data
CCDB: https://library.ucsd.edu/dc/collection/bb5940732k/data
Galactose: https://library.ucsd.edu/dc/collection/bb5668210c/data
Commitment problems: https://library.ucsd.edu/dc/collection/bb38249709/data
Seafloor deformation: https://library.ucsd.edu/dc/collection/bb7101749f/data
Bee and plant samples: https://library.ucsd.edu/dc/collection/bb3415450r/data
Electrostatic interactions: https://library.ucsd.edu/dc/collection/bb4849132z/data
Mediterranean New Rio Grande: https://library.ucsd.edu/dc/collection/bb46439170/data

On Friday, July 7, I checked all of these pages again and the titles are no longer duped. Looking on staging, however, the CSC collection (for example) does have a duped title: http://librarytest.ucsd.edu/dc/collection/bb0070711k/data.

**Comment by remerjohnson** [comment]
@hjsyoo Those titles were de-duped by hand on production. You would also want those de-duped on staging?

**Comment by hjsyoo** [comment]
@remerjohnson No, you're right, I forgot you corrected those by hand. I don't need them de-duped on staging, unless it will help us to figure out where the duping on EZID is coming from?
@lsitu What's the best way for us to review the work on this ticket? Do we wait until @remerjohnson can ingest a new collection to staging?

**Comment by hjsyoo** [comment]
Actually, Ryan just did ingest a collection on staging, and the duping is still there: http://librarytest.ucsd.edu/dc/collection/bd0494580w/data

**Comment by lsitu** [comment]
@hjsyoo I think we are trying to fix the potential issue that generate the dup CLR title here. That is, we shouldn't get any dup-titles when ingest new CLRs on staging now. Yep, we need to de-dupe titles for those collections by hand as @remerjohnson said. We could use the rdf import tool https://librarytest.ucsd.edu/damsmanager/rdfImport.do to do it. Do you want me to de-dup those CLRs?

**Comment by lsitu** [comment]
@hjsyoo @remerjohnson It looks like CLR http://librarytest.ucsd.edu/dc/collection/bd0494580w/data was created on earlier at 2017-06-26T08:34:31 but just updated. We may need to ingest **new** CLR now to test the dup-title CLR issue. Thanks.

**Comment by hjsyoo** [comment]
@lsitu Oh, that would do it! Thanks. @remerjohnson, maybe we can do a test ingest later today? I think any of the existing ones on rdcp-staging should work?

**Comment by hjsyoo** [comment]
@lsitu No need to dedupe the CLRs on staging manually. Once we're able to test this ticket and get a test coll page without duped titles, I can mint a DOI after that to test duping on EZID.

**Comment by hjsyoo** [comment]
Tested DOI minter on staging, and no duping occurred in EZID.
