### ISSUE TITLE
Create and replace derivative

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#322]
### Descriptive summary

Calisphere refused to harvest this object. It is the wrong mime-type. 

- https://library.ucsd.edu/dc/object/bb58372132

- Re-create the _2.jpg derivative and ensure that it's mime-type is Content-Type: image/jpeg

**Note:** When done Gabriela will re-harvest to Calisphere.

### Image Header:

```
HTTP/1.1 200 OK
Date: Thu, 15 Jun 2017 23:51:32 GMT
Server: Apache/2.2.15 (Red Hat)
Cache-Control: max-age=0, private, must-revalidate
Content-Disposition: inline; filename=bb58372132_2.jpg
X-Powered-By: Phusion Passenger 5.0.30
Content-Length: 350401
Status: 200 OK
Content-Type: application/octet-stream
```

**Comment by lsitu** [comment]
@gamontoya I've recreated the _2.jpg derivative late yesterday afternoon. But it seems like there's an issue with solr indexing. I am now checking with @jhriv to restart the Solrizer. I'll let you know once it ready for you.

**Comment by gamontoya** [comment]
@lsitu I appreciate it. Thanks!

**Comment by lsitu** [comment]
@gamontoya I think the issue with the corrupted _2.jpg derivative is fixed and it can display now: https://library.ucsd.edu/dc/object/bb58372132/_2.jpg.

**Comment by gamontoya** [comment]
## Note: 

Harvested to Calisphere.
