### ISSUE TITLE
Re-create and replace derivatives

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#323]
### Descriptive summary

Calisphere refused to harvest these objects because they are the wrong mime-type. 

- bb0478952m (Glasheen)
- bb55301874 (Glasheen)
- bb0239878f (Keesing)
- bb2594848v (Keesing)
- bb66904480 (Keesing)
- bb2185136v (Seuss Political)

- Re-create the _2.jpg derivative and ensure that its mime-type is Content-Type: image/jpeg

**Note:** When done Gabriela will re-harvest to Calisphere.

### Image Header:

```
HTTP/1.1 200 OK
Date: Thu, 15 Jun 2017 23:51:32 GMT
Server: Apache/2.2.15 (Red Hat)
Cache-Control: max-age=0, private, must-revalidate
Content-Disposition: inline; filename=bb0478952m_2.jpg
X-Powered-By: Phusion Passenger 5.0.30
Content-Length: 350401
Status: 200 OK
**Content-Type: application/octet-stream**
```

**Comment by hweng** [comment]
@gamontoya Just let you know that My work has been going on to fix https://github.com/ucsdlib/damspas/issues/325 will also fix this ticket.

**Comment by gamontoya** [comment]
@hweng Thank you for the update!
