### ISSUE TITLE
Change visibility to Independent Study Project collection

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#324]
### Descriptive summary

I set the [ISP collection](https://library.ucsd.edu/dc/collection/bb92846544) from **Curator** to **UCSD IP access**, however, only 11 records out of 210 were affected. 

Please update the display visibility to the remaining 199 records. All objects should be **UCSD IP access** only.

Collection: https://library.ucsd.edu/dc/collection/bb92846544

**Comment by lsitu** [comment]
Hi Gabriela,
I see a "Display currently prohibited." license in most of the objects in ISP, this will have higher priority to over rights override to block those objects from UCSD-only access. For example:
http://lib-hydratail-prod.ucsd.edu:8080/dams/api/objects/bb4131023f.
And also, for those 11 public objects, rights override won't take effect as well since the copyright allow public access though we could implement something in the collection level to hood them up for UCSD-only, like what we do for public collections under reviewing. 

So if we can't change the License/copyright metadata, we may need to implement new access override rules, which could affect objects in other collections as well. 
What do you think?

**Comment by lsitu** [comment]
@gamontoya With access override, the simplest way that we can do is to enable collection level local visibility with access override for all objects in a collection for UCSD-only access, no matter what copyright/license the objects are. This will fix all 210 objects in ISP for UCSD-only access.
Another way that we could do is to apply the rule above to hood up public objects (those 11 objects) with collection level visibility for UCSD-only access, while allowing OtherRights to override objects with restricted license for UCSD-only access.

But we may need to see how this change will affect objects in other collections though.

**Comment by gamontoya** [comment]
@lsitu Which access override do we have implemented now in DAMS 4 that we can use?

**Comment by lsitu** [comment]
@gamontoya The current access override implemented won't work for the ISP case, which has 11 public object and there are 196 objects (except 3) are curator access with the "Display currently prohibited" license, which won't allow for UCSD-only access override.
We may need to override the rules to hood up those 11 objects for UCSD-only access from the collection visibility and also allow objects with the restricted license for "Display currently prohibited" to allow UCSD-only access override.

**Comment by gamontoya** [comment]
@lsitu Proceed with the overriding the rules to hood then. Thanks!

**Comment by lsitu** [comment]
Hi Gabriela,
I've updated the access rules to allow UCSD local overridden by collection visibility hood up for public objects and OtherRights for restricted objects. The issues with the ISP collection local display will be fixed once we deploy damsrepo to prod.

@mcritchlow The PR (https://github.com/ucsdlib/damsrepo/pull/53) is ready for review now. Thanks.

**Comment by lsitu** [comment]
@gamontoya I've updated records in ISP for access override with local access for those private object on staging. All 210 objects should be available for UCSD local access on staging now: https://librarytest.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=UCSD+Independent+Study+Project+%28ISP%29&id=bb92846544
Could you take a look? If it's good, we can move the deployment for damsrepo to prod and fix it here. Thanks.

**Comment by gamontoya** [comment]
@lsitu Looks good Longshou. Feel free to proceed.

**Comment by lsitu** [comment]
Hi Gabriela,
Thanks. We'll move it forward once the deployment ticket https://github.com/ucsdlib/damsrepo/issues/54 is approved, which is bound to ticket https://github.com/ucsdlib/damspas/issues/319 for test result now.

**Comment by gamontoya** [comment]
@lsitu Let me know when this update is reflected on prod.

**Comment by lsitu** [comment]
@gamontoya Sure. It looks like we should deploy damsrepo https://github.com/ucsdlib/damsrepo/issues/54 to prod now.

**Comment by lsitu** [comment]
Hi Gabriela,
I think the UCSD local access issue for the ISP collection should be fixed on prod at this time. I am seeing all 210 records are showing up with VPN now: https://library.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=UCSD+Independent+Study+Project+%28ISP%29&id=bb92846544. Could you take a look?

**Comment by gamontoya** [comment]
@lsitu Yes, looks good. Thank you Longshou!
