### ISSUE TITLE
Keesing Collection: Image(s) and metadata export needed

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#326]
### DESCRIPTIVE SUMMARY

I'd like to have a copy of the tiffs and med-resolution jpegs (2.jpg) exported from the DAMS.  

Export the images (divided by restricted and non-restricted) along with a CSV export of the descriptive metadata (see below for requested metadata elements).

**Note:** List of 886 restricted images (ARKs) [attached here](https://github.com/ucsdlib/damspas/files/1092722/keesing_restricted.txt)

**EXPORT LOCATION**

TIFFS:
- \\lib-storage.ucsd.edu\digital-staging\Cristela_Keesing\tiff\non-restricted
- \\lib-storage.ucsd.edu\digital-staging\Cristela_Keesing\tiff\restricted

JPEGS:
- \\lib-storage.ucsd.edu\digital-staging\Cristela_Keesing\jpeg\non-restricted
- \\lib-storage.ucsd.edu\digital-staging\Cristela_Keesing\jpeg\restricted

CSV:
- \\lib-storage.ucsd.edu\digital-staging\Cristela_Keesing\metadata

**DESCRIPTIVE METADATA ELEMENTS**
- ARK
- Filename (type=identifier Note)
- Title
- Creation Date
- Description
- Geographic
- Topics
- Personal Name
- Location of Originals Note
- Preferred Citation Note
- Local Attribution Note
- Copyright
- RightsHolder

### Rationale

Anthropologist David Akin, who we've been working with for a number of years on the Roger Keesing Collection, will be making a trip to the Solomon Islands in August.  They have set up an archive there, and he will be delivering electronic equipment to share content, e.g. solar power laptops, projectors, etc.

As a part of the work we've been doing with the community, we sent physical hard copies of documents, and now we would like to send the digital copies of the Keesing Photographs along with David on his trip to return to the community.

**Comment by lsitu** [comment]
@ucsdlib/operations We may need to see how to download the TIFFs and JPEGs to the specific locations. 
I recalled that @rstanonik once use a script to download the files from dams with a list of ARKs in the past. Is it still doable to use/update that script to download the TIFFs and JPEGs for the restricted and non-restricted objects to the locations above? In addition to those 886 ARKs for the [restricted objects](https://github.com/ucsdlib/damspas/files/1092722/keesing_restricted.txt) above, I can provide the ARKs for those non-restricted objects in Keesing as well if that works. Thank you very much.

**Comment by lsitu** [comment]
@gamontoya I've exported the metadata for all 3868 objects in Keesing:

[metadata.txt](https://github.com/ucsdlib/damspas/files/1106196/metadata.txt)

Could you take a look? Note that the "Personal Name" column only includes subject personal name at this time. Please let me know if we need to include personal names from relationship with creator roles.

**Comment by gamontoya** [comment]
@lsitu Can you export as Tab delimited (we are seeing issues with comma separate), and yes... export the creator roles too. Thanks for asking!

**Comment by lsitu** [comment]
Hi Gabriela,
Here is the Tab delimited version 
[metadata.txt](https://github.com/ucsdlib/damspas/files/1106613/metadata.txt). 
What's the problem with the CSV format?

**Comment by gamontoya** [comment]
@lsitu Perfect! With the commas, the subjects were running on into the personal names column, but this one works fine.

**Comment by lsitu** [comment]
Got it. I think we can fix that. Just let me know if you still want the CSV format.

**Comment by gamontoya** [comment]
@lsitu No, we just need that tab delimited version.

**Comment by lsitu** [comment]
That sounds good. Thanks Gabriela.

**Comment by lsitu** [comment]
@rstanonik Could we copy the Tab delimited metadata file [metadata.txt](https://github.com/ucsdlib/damspas/files/1106613/metadata.txt) to \lib-storage.ucsd.edu\digital-staging\Cristela_Keesing\metadata? We don't have the write access to lib-storage.

Here is the arks for those 2892 non-restricted objects:
[arks_non-restricted-2892.txt](https://github.com/ucsdlib/damspas/files/1106957/arks_non-restricted-2892.txt). Could we use your script to download the TIFFs to \lib-storage.ucsd.edu\digital-staging\Cristela_Keesing\tiff\non-restricted and the JPEGs (2.jpg) to \lib-storage.ucsd.edu\digital-staging\Cristela_Keesing\jpeg\non-restricted?
And also download the TIFFs and JPEGs (2.jpg) for those[ 886 restricted objects](https://github.com/ucsdlib/damspas/files/1092722/keesing_restricted.txt) to download \lib-storage.ucsd.edu\digital-staging\Cristela_Keesing\tiff\restricted and \lib-storage.ucsd.edu\digital-staging\Cristela_Keesing\jpeg\restricted respectively?

Please let me know if it doesn't work and we'll see what's the better way to download those files. Thank you very much.

**Comment by gamontoya** [comment]
@lsitu I copied over the metadata.txt file to digital-staging. Remaining to do it @rstanonik copying over the TIFF and JPEGs.

**Comment by lsitu** [comment]
Thanks Gabriela.
@rstanonik Please let me know if you have any questions regarding copying the TIFFs and JPEGs over. Thanks.

**Comment by rstanonik** [comment]
I'm working on the script.

**Comment by lsitu** [comment]
Thanks @rstanonik . Just let me know if there's anything that you need me to work on.

**Comment by rstanonik** [comment]
It's done.
Take a look and confirm the files are correct.

**Comment by lsitu** [comment]
Thanks a lot @rstanonik. 
The TIFFs looks correct. The only issue I see is the JPEGs files are all in folder the non-restricted jpeg/non-restricted while the jpeg/restricted is empty. I think we just need to separate it.

**Comment by rstanonik** [comment]
Good catch.
I moved the restricted jpegs.

**Comment by lsitu** [comment]
@rstanonik It looks like that the non-restricted files were moved instead, and now the JPEGs in jpeg/restricted and jpeg/non-restricted files need to switch.

**Comment by lsitu** [comment]
@rstanonik I see folder jpeg/restricted contains 2982 files, which are from the non-restricted ark list (https://github.com/ucsdlib/damspas/files/1106957/arks_non-restricted-2892.txt) and the folder jpeg/non-restricted contains 886 restricted files instead. This is not correct and we may need to rename the folders. Do you see the same thing?

**Comment by rstanonik** [comment]
Okay, I switched jpeg restricted and non-restricted

**Comment by gamontoya** [comment]
@cgarciaspitz Please confirm that you have everything you need from this ticket.

Thank you @lsitu and @rstanonik
