### ISSUE TITLE
Student Newspapers: Identify 7 curator only objects and release

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#327]
### Descriptive summary

There are 646 digital objects in the DAMS, but only 639 are **public**. Identify the 7 that are **curator only** and release them to public visibility.

**Comment by lsitu** [comment]
@gamontoya The following 7 objects were curator only and I'd released them:
https://library.ucsd.edu/dc/object/bb0445239r
https://library.ucsd.edu/dc/object/bb14008793
https://library.ucsd.edu/dc/object/bb2697817g
https://library.ucsd.edu/dc/object/bb39947572
https://library.ucsd.edu/dc/object/bb5291697h
https://library.ucsd.edu/dc/object/bb6554507s
https://library.ucsd.edu/dc/object/bb7851447c
 
All 646 objects in [UCSD Student Newspaper](https://library.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=UCSD+Student+Newspapers&id=bb9318959d) are showing up for public access now. Could you take a look? Thanks.

**Comment by gamontoya** [comment]
@lsitu 646 for me! Thank you.
