### ISSUE TITLE
Add sitetrackings partial to staging environment (librarytest)

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damspas#328]
### Descriptive summary

Please render the _sitetrackings partial when the environment is staging (librarytest)

* https://github.com/ucsdlib/damspas/blob/7dc9e2c58152984fd76652bf1b7cc67a13ae6078/app/views/layouts/homepage.html.erb#L7
* https://github.com/ucsdlib/damspas/blob/475a6a3bd9eaf7a60a56f5eb3874bd7708b7333e/app/views/layouts/ucsdlib.html.erb#L14

### Rationale

We've been asked to add the hotjar/crazyegg partial (_sitetrackings) back to the staging environment by Colleen and SuHui to facilitate an upcoming user study.

### Expected behavior

The hotjar JS should be rendered on the staging environment.

### Actual behavior

It is currently only enabled in production.

**Comment by colleenfgarcia** [comment]
Just wanted to check in on this - request.  Was hoping to do some testing this week on staging.  Thanks!
