### ISSUE TITLE
Update RDCP collections local attribution note URL

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#333]
### Descriptive summary
Globally update the current `<dams:type>local attribution</dams:type>` note URL from:

- http://libraries.ucsd.edu/services/data-curation/

  to:

- https://library.ucsd.edu/research-and-collections/data-curation/

### Rationale

While the current URL redirects, Ho Jung would like to see the URLs updated before DAMS 5.0 migration.

![1](https://user-images.githubusercontent.com/4314914/28180984-da8422c2-67bb-11e7-9778-9e4aac80adea.png)

**Comment by gamontoya** [comment]
@mcritchlow This can be assigned for this Sprint if you have the bandwidth. Otherwise it can wait.

**Comment by mcritchlow** [comment]
@ucsdlib/developers - if anyone has capacity in this sprint to work on this, please feel free to grab the ticket. Thanks!

**Comment by VivianChu** [comment]
@mcritchlow I can work on this.

**Comment by mcritchlow** [comment]
Thanks @VivianChu!

**Comment by VivianChu** [comment]
@gamontoya - The  url has been updated for RDCP collections.
