### ISSUE TITLE
Mint DOI button should set default Resource Type to "Dataset"

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damspas#340]
### Descriptive summary

When minting a DOI from curator tools, the EZID field, Resource Type, should be set to "Dataset". Currently, it is left blank. But when entering edit view in EZID and saving the record after making no changes, Resource Type defaults to "Dataset" on its own.

### Rationale and Expected behavior

Prior to the latest code fix, both Resource Type General and Resource Type were being set to "Dataset" upon clicking the Mint DOI button. This is the desired behavior. RDCP creates EZID records partially with the intent of having records properly harvested by other databases. Consistency in these mappings is important to proper harvesting.

### Steps to reproduce the behavior

1. I click on Mint DOI button on object page (e.g., https://library.ucsd.edu/dc/object/bb4542052j). DOI is successfully minted.
2. The record shows up in https://ezid.cdlib.org/manage, with Object Type listed as “Dataset”.
3. I go into edit view, for that EZID record. Resource Type General is set to “Dataset”, but Resource Type is blank.
4. Without making any changes, I click on Save Changes. Now, Object Type is listed as “Dataset/Dataset”.
5. And Resource Type has been set to “Dataset”, even though I didn’t add it manually.

### Related work

Link to related tickets or prior related work here.

**Comment by VivianChu** [comment]
@hjsyoo -  For your example record xml - https://ezid.cdlib.org/manage/display_xml/doi:10.6075/J0D21VRF - the resourceType element is 
<resourceType resourceTypeGeneral="Dataset">Dataset</resourceType>
If you want the Resource Type is set to “Dataset”, what does the xml look like? I tried <resourceType>Dataset</resourceType> and it doesn't work because the attribute resourceTypeGeneral is mandatory based on the schema https://schema.datacite.org/meta/kernel-3.0/doc/DataCite-MetadataKernel_v3.0.pdf.  
The Controlled List Values for resourceTypeGeneral:
Audiovisual
Collection
Dataset
Event
Image
InteractiveResource
Model
PhysicalObject
Service
Software
Sound 
Text
 (combine with free-
text 
OR terms from CASRAI 
Publications resource type 
list
)
21
Workflow  
Other

Do you know any object that has both Resource Type General and Resource Type were being set to "Dataset" before the latest code fix?  It would helpful to look at these objects xml.  Thanks

**Comment by hjsyoo** [comment]
@VivianChu I don't recall what the history of this particular record is, but try https://ezid.cdlib.org/manage/display_xml/doi:10.6075/J0RF5RZ9.  The record was created in 2015 and last modified 2017-01-05. Unfortunately, it's entirely possible that I created the record manually, and it's certain that I've modified the record since its creation. 
I'm afraid there are no current EZID records that haven't been modified. Let me know if there's any other information that would help.

**Comment by VivianChu** [comment]
@hjsyoo - I reverted the change from the latest code fix and deployed it to staging.  I tried to mint doi for this record   http://librarytest.ucsd.edu/dc/object/bb4438832x 
For the ezid edit view - https://ezid.cdlib.org/manage/edit/doi:10.5072/FK21Z4828R?   The value for resourceType is still blank.  From the javascript code - if we click the "SAVE CHANGES" button & if the value for resourceType is blank, the value from Resource Type General will get copy to Resource Type automatically.  
<script type="text/javascript">
  $(document).ready(function() {
    //* set the resourceType to the same as resourceTypeGeneral
    $(':submit').click(function(e)
    {
      var gen = $('#resourceType-resourceTypeGeneral').val();
      var res_type = $('#resourceType').val();                 
      if(gen != '' && res_type == ''){
        $('#resourceType').val(gen);
      }
    });
  });
  The different I saw from the old and new change is the xml view for that record https://ezid.cdlib.org/manage/display_xml/doi:10.5072/FK21Z4828R   has the element <resourceType resourceTypeGeneral="Dataset"/>  while with the latest code fix that element is <resourceType resourceTypeGeneral="Dataset">Dataset</resourceType> (https://ezid.cdlib.org/manage/display_xml/doi:10.6075/J0D21VRF) 
  I think the default value for Resource Type doesn't come from the xml, only the Resource Type General does. 
Your other example - https://ezid.cdlib.org/manage/display_xml/doi:10.6075/J0RF5RZ9.  - if you already modified the record using the ezid edit view, then the value Resource Type is already get copied from Resource Type General. 
Do you have any suggestion about this issue?  Thanks

**Comment by hjsyoo** [comment]
That sounds like what I've observed about the current behavior. The thing is, this behavior is new, since around the time of the last code fix. It's possible that EZID changed something on their end around the same time, which caused this issue to emerge. But I'm just speculating. Do you think it's worth asking the EZID community or maybe the developers about it? It's just that this wasn't really a problem before.

**Comment by VivianChu** [comment]
@hjsyoo - Sounds good.  I'll ask and will keep you posted.  Thanks

**Comment by VivianChu** [comment]
@hjsyoo - EZID customer support mentioned that they have not made substantial changes to the user interface in the last several month.  However, I found out how that resource type value  is created. 
I just deployed my change to staging and it worked.
Here's the record I just added using the MINT DOI button.  The resource type value is set to dataset

https://ezid.cdlib.org/manage/edit/doi:10.5072/FK2VT1Q063

You could try to mint doi from staging.
If it looks ok to you, we can get it deploy to production.

Thanks

**Comment by VivianChu** [comment]
![ezidedit](https://user-images.githubusercontent.com/1864660/29227736-e9b026a6-7e8b-11e7-9819-c6edb87b74bb.png)

**Comment by hjsyoo** [comment]
@VivianChu Yes! This fix is exactly what I would like to see. It will save me lots of busy work. Thank you, and please do deploy to production!
