### ISSUE TITLE
Batch update geographic coordinates for Pacific Charts collection

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damspas#341]
### Descriptive summary

We received corrections for our (polygonal) geographic coordinates in the [Pacific Basin Nautical Charts collection](https://library.ucsd.edu/dc/collection/bb0786509m). I'm providing a tab-delimited file in order to batch update all the DAMS objects' coordinates (the `Geographic:polygon` property).  

**NOTE:** The sheet has ID and a "Name" column that must be ignored/removed; and URLs for DAMS objects, not ARKs. If I need to reform those into valid ARKs, let me know. 

### Rationale

As metadata analyst on this collection, I can confirm that the source metadata coordinates were often slightly or totally incorrect (for example, a lot of the Tonga area maps have coordinates near Hawaii).  

I did a [test ingest](http://librarytest.ucsd.edu/dc/collection/bd37371932) with the updated coordinates, using current DAMS objects as related resources, and the improvement is significant. This fix would be a large enhancement to our Leaflet displays. 

[pacific_charts_coordinates_fix.txt](https://github.com/ucsdlib/damspas/files/1191576/pacific_charts_coordinates_fix.txt)

**Comment by VivianChu** [comment]
@remerjohnson - The geographic coordinates have been updated for Pacific Basin Nautical Charts collection.  For example
https://library.ucsd.edu/dc/object/bb90797642
https://library.ucsd.edu/dc/object/bb1878332n

**Comment by remerjohnson** [comment]
@VivianChu Thanks so much! From my random selections, they all updated nicely.
