### ISSUE TITLE
Batch metadata edit - remove FA links from objects in Fletcher Collection

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damspas#342]
### Descriptive summary
Many of the objects in the Fletcher Collection https://library.ucsd.edu/dc/collection/bb55647135 display two links to the online finding aid: one which is correctly drawn from the collection level record, and a second which is (against practice) encoded in the object level record.

We would like to remove all of the related resource links to the online finding aid from Fletcher collection objects.

### Rationale
Redundant info for the user and doesn't conform to best practice.

Asking for batch editing because we think this may affect 1800+ objects.

### Steps to reproduce the behavior
Remove the following from all objects in the Fletcher collection:
```
<dams:relatedResource>
<dams:RelatedResource>
<dams:description>Finding aid</dams:description>
<dams:type>online finding aid</dams:type>
<dams:uri rdf:resource="http://libraries.ucsd.edu/speccoll/findingaids/mss0081.html"/>
</dams:RelatedResource>
</dams:relatedResource>
```

**Comment by gamontoya** [comment]
@mcritchlow This ticket can be worked on if you have the bandwidth for this Sprint.

**Comment by VivianChu** [comment]
@arwenhutt - dams:relatedResource has been removed for 1823 objects.
For example
https://library.ucsd.edu/dc/object/bb7919723t
https://library.ucsd.edu/dc/object/bb6929950p

**Comment by arwenhutt** [comment]
Thanks @VivianChu, it looks good to me!  I'll update the collection owners.
