### ISSUE TITLE
Browse by Collection - thumbnails loading over http

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damspas#344]
### Descriptive summary

@hannahbegley reported that her browser(s) are reporting the search results for "Browse By Collection" are resulting in a "Connection not Secure" message. I've verified this.

It looks like the issue (or at least *an* issue) is the thumbnails are being pulled via http links. This can be verified by opening up the dev console in FF, Chrome, etc.

Example: http://library.ucsd.edu/assets/dams/collections/thumbnails/bb41312109.jpg

### Rationale

We want to provide a complete "Secure" browsing experience for our users and not create a scenario where they are concerned about the security and validity of our web application.

### Expected behavior

Collection thumbnails reference https urls.

https://library.ucsd.edu/assets/dams/collections/thumbnails/bb41312109.jpg

### Actual behavior

http://library.ucsd.edu/assets/dams/collections/thumbnails/bb41312109.jpg

### Steps to reproduce the behavior

1. Browse by Collection
1. Open up Developer console. See warnings along the lines of "Loading mixed (insecure) display content “http://library.ucsd.edu/assets/dams/collections/thumbnails/bb7305352v.jpg” on a secure page"

**Comment by VivianChu** [comment]
@mcritchlow - I updated the thumbnail url for all collections and the insecure message is not displaying in developer console anymore.

**Comment by lsitu** [comment]
@rstanonik Could you update DAMS Manager configuration parameter "xdre.clr.urlBase" in file damsmanager.properties for each environment prod, staging and QA to use HTTPS instead of HTTP as well:
xdre.clr.urlBase=https://libraries.ucsd.edu/assets/dams/collections/thumbnails

This will prevent the newly created collection CLR from getting the same browser error above. Thanks.

**Comment by rstanonik** [comment]
I changed it in all three environments, but only restarted damsmanager tomcat in qa and staging.

If production damsmanager is idle, I can restart it there too, otherwise I'll restart Monday morning.

**Comment by lsitu** [comment]
@rstanonik I think we can restart it tomorrow morning. Thanks.

**Comment by rstanonik** [comment]
I scheduled production damsmanager tomcat to restart at 6am tomorrow morning

**Comment by mcritchlow** [comment]
Thanks all! And nice catch, @lsitu on the urlBase setting.
