### ISSUE TITLE
PDF not searchable - create new derivative

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#345]
### Descriptive summary

It was reported that the derivative PDF for bb1982115k is not searchable. Confirming that I downloaded the master file and it has been OCR'd so something is not working.

### Resolution

Per @VivianChu, needs to re-index which invokes full extraction.

- Vivian will re-index all 24 objects in this collection.

**Comment by VivianChu** [comment]
@gamontoya - All objects in the collection have been re-indexed.

**Comment by gamontoya** [comment]
@VivianChu Thank you!
