### ISSUE TITLE
Issue with superfluous audio channels for .mov file

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#346]
### Descriptive summary

These two mov files show irregular characteristics:

- bb07861733_1_1.mov has 3 audio streams (stream 1 and 2 are superfluous, tagged as if they were multichannel surround for a “front center” channel). 

- bb07861733_2_1.mov has 2 audio streams (stream 1 is superfluous, tagged as if it were multichannel surround for “front left right” channel). 

### Observations:

1. mov containers have superfluous audio streams, the only ones that look consistent with DV spec is tagged “muxed in Video 1”
2. both mov master files are inconsistent between each other.

### Recommended fix (by Stefan)

Possible option for repair: Recreated derivatives by running the FFmpeg command to strip superfluous audio channels.

**Comment by gamontoya** [comment]
@VivianChu Stefan said this ticket can be closed if the derivative plays as expected. I believe he created the derivatives for you so we should be good now. Leave the .mov master file as is.

**Comment by VivianChu** [comment]
Thanks @gamontoya  .  The derivatives plays as expected.  I'll close the ticket.
