### ISSUE TITLE
Remove several objects from Scripps CO2 Program Data collection

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damspas#352]
### Descriptive summary

Due to an improved restructuring of the object model by the data provider after ingest to production, we need to remove the 13 following objects from production:

https://library.ucsd.edu/dc/object/bb0480492c
https://library.ucsd.edu/dc/object/bb4303052r
https://library.ucsd.edu/dc/object/bb0139192t
https://library.ucsd.edu/dc/object/bb5292823c
https://library.ucsd.edu/dc/object/bb9456682x
https://library.ucsd.edu/dc/object/bb3620455b
https://library.ucsd.edu/dc/object/bb9115382m
https://library.ucsd.edu/dc/object/bb4610222c
https://library.ucsd.edu/dc/object/bb4951522p
https://library.ucsd.edu/dc/object/bb8432784p
https://library.ucsd.edu/dc/object/bb3961753m
https://library.ucsd.edu/dc/object/bb8774083d
https://library.ucsd.edu/dc/object/bb9797985s

(The collection page and the one remaining object will be retained and edited. Once the 13 objects are removed, 3 new objects will be added to the collection.)

### Rationale

The data have been restructured in a way that both improves data delivery to users and reduces the monthly workload for curators.

**Comment by gamontoya** [comment]
@mcritchlow Here's another for assignment.

**Comment by VivianChu** [comment]
@hjsyoo - 13 objects have been deleted in production.
