### ISSUE TITLE
Subject Conversion: Question about labels

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damspas#354]
### Descriptive summary

From @arwenhutt :

In D4 many, all?, of our authorities have both a display label and a value (usually variants on "authoritativeLabel" and "elementValue"). Do we need to update both of these? or is it sufficient/safe to update just the display label and then when we migrate to D5 only map the label and not the element value?

For example, is authoritativeLabel leveraged in something like Solr indexing, whereas elementValue is used for the display views?

### Rationale

@ucsdlib/domm needs to understand the relationship between the two properties, and whether the subject conversion instructions can simply be to "update both properties with the same value" or if there needs to be additional care taken in assessing and updating the values individually.

### Related work

https://github.com/ucsdlib/damsmanager/issues/172
https://github.com/ucsdlib/damspas/issues/355

**Comment by lsitu** [comment]
@arwenhutt It looks like this is a ticket for you DOMMs as well.
In D4, the properties "authoritativeLabel" and "elementValue" are variants on the following cases:

1. Simple Subject
    Generally speaking, both "authoritativeLabel" and "elementValue" should be the same.
2. Name
    For CorporateName, normally we only have a mads:NameElement that both properties are consistent.
    For mads:PersonalName, we may have list of name elements like mads:FamilyNameElement, mads:GivenNameElement, mads:DateNameElement etc, which are variant. While others may only have the mads:FullNameElement that is consistent with "authoritativeLabel".
3. Complex Subject
    This could be a combination of subject/name elements, which is variant on the two cases above.

I think the question is, do we want to keep it consistent for "authoritativeLabel" and "elementValue" or not? 
And as @mcritchlow noted above, do we have any special use of the "authoritativeLabel" and "elementValue" properties that need to leverage or not?

**Comment by arwenhutt** [comment]
@lsitu Are the element values used by the application at all or does it only use the authoritativeLabel?

From a data standpoint, I don't think we'll be able to update the family/given/date sub elements as part of the conversion process since our reconciled data doesn't break them down that way.  I think that is probably okay for now, but I want to make sure that we don't create functionality issues in D4 by only updating the label and creating discrepancies between the label and element values.

**Comment by lsitu** [comment]
@arwenhutt In D4, I think we only index and use the authoritativeLabel for clr/olr UI displaying at this time. However, we do index element value for subject/name records, though we haven't utilized those subject/name records in SOLR yet.
So I think it won't break any current D4 functionalities by just updating the authoritativeLabel and leaving the element values as-is. But when moving forward with D5 migration, we have to say that only the authoritativeLabel will be used for D5 data migration. Is it correct?

**Comment by arwenhutt** [comment]
> only the authoritativeLabel will be used for D5 data migration

@lsitu yes that is correct, we'd map from authoritativeLabel to D5

Thanks for checking on the D4 functionalities, I'm going to close now and update the stage 1 ticket!
