### ISSUE TITLE
Subject Conversion:  Review of draft of processesing rules/instructions

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damspas#355]
### Descriptive summary
I think the draft for the [subject conversion process](https://docs.google.com/a/ucsd.edu/document/d/12HOMth8ylD20bcEeVYb336NaVxSwaip58n0IhXUWFMs/edit?usp=sharing) is ready for review.  
The document linked outlines the proposed approach for converting, updating, de-duplicating, and enhancing authority records and their links to object and collection level records in the DAMS database.

A few notes:
- The processing is divided into different stages to make the instructions (and transformation code) less complicated.  
- The "Data input files" identified at each stage do not yet exist in the format described.  The ones for stages 1 & 2 will be created utilizing the data we have in DOMM's full subject conversion file.  Subsequent ones utilize data from this same file as well as data output from previous stages.
- The stage (or possibly stages) for updating name records is still being worked on and will be added when it seems solid.
- I've categorized most of my comments.  Those marked TODO are notes about creation of data files (or other things like that) largely that DOMM will be doing.  There are also some marked QUESTION and CLARIFICATION - which are pretty self explanatory.  

### Requested
Please review the document. Feedback is welcome on anything, but definitely on:
- Any possible problems with the logic of how the data is being transformed
- Improving the clarity of how this is expressed
- More efficient ways to accomplish something 

Please use the "suggesting" mode.  Due to the nature of the document, small changes can have a big affect, so I think it'll be easier to review, stay up to date and check and re-check how a suggested change affects other stages.  

### Related work
Name role report request https://github.com/ucsdlib/damsmanager/issues/176

**Comment by mcritchlow** [comment]
Tagging @lsitu in to the assignee group to review also.

**Comment by remerjohnson** [comment]
> The "Data input files" identified at each stage do not yet exist in the format described. The ones for stages 1 & 2 will be created utilizing the data we have in DOMM's full subject conversion file. 

I had a repo laying around for the older subjects' data analysis, and I've [updated it](https://github.com/remerjohnson/subject-data-analysis) using the newer master file, with the goal to hopefully end up generating said input files.  

The readme for now sketches out the steps to make the input files, which, once we solidify more in the Google Doc, could maybe turn into discrete issues in this or our repo. Of course we could tackle this in other ways if people want :smile:

**Comment by arwenhutt** [comment]
@remerjohnson that looks very cool! I haven't read through all the steps, but I love the idea of doing this in a reusable way, and I think there's a lot of the processing that's going to be easier in python then excel.  It would be good to have this in our unit repository when we move forward, so we have it all together with the related work, but I'm not sure if it needs to be there now, or if that's like using LiSN for drafts (confusing).  Maybe once we start getting the tickets for the reports nailed down...

Once we have general agreement that the overall process seems good, I think I can start working on those.

**Comment by arwenhutt** [comment]
@lsitu - @mcritchlow mentioned that it might be useful to see the data spreadsheet we've been working in, so I'm attaching a sample version here: [temp_combined_subject_conversion_file_longshou.xlsx](https://github.com/ucsdlib/damspas/files/1369941/temp_combined_subject_conversion_file_longshou.xlsx)

I've removed some of the columns we use for our work, and about half of the rows.  There are some columns which will be filled out further during different steps of the process.  But this is basically the source data we'll be working with to create most of the data input files mentioned in the document linked above.

**Comment by lsitu** [comment]
@arwenhutt Thanks. Do we have a general mapping rules for each column in the sample file temp_combined_subject_conversion_file_longshou.xlsx? Or we need to walk through the steps in  [subject conversion process](https://docs.google.com/a/ucsd.edu/document/d/12HOMth8ylD20bcEeVYb336NaVxSwaip58n0IhXUWFMs/edit?usp=sharing) to catch the mapping rule for each column?

**Comment by arwenhutt** [comment]
@lsitu It's all in the subject conversion process document.  The main outlined stages in that document are focused on the ITD side, there will also be DOMM work in between those stages to prep data input files and integrate output data.  The whole data transformation is pretty complicated and multi-step, so doesn't really lend itself to general mappings per source data column.

**Comment by lsitu** [comment]
@arwenhutt Got it. Thanks. It looks like we may need to re-link some of the subject/name authority records, right? In this case, we may need to track all those CLRs/OLRs that the subject/name need to link to.  Are we able to keep track of those CLRs/OLRs or not?

**Comment by arwenhutt** [comment]
@lsitu if I'm understanding your question correctly, we are linking the updated/new authority records to  olr/clrs in Stages 3 and 4.  The olr/clr records that need one (or many) subject/name links added would be identified by  searching for all clr/olr records for the old_ARK, adding the link, and repeating for all the old_ARK's.  

We have no plans for tracking all the links between authority records and clr/olrs, it seems like that would require recreating a large portion of our database, and I'm not sure we need to or can manage tracking the data in that way.

**Comment by arwenhutt** [comment]
I think this ticket should have been closed a long time ago...
