### ISSUE TITLE
Update collections to be metadata-only view

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#356]
### Descriptive summary

Steering Committee has approved making the following collections metadata only:

- Center  for Music Experiment
- Dept. of Music  Concert Archive
- ECE   Distinguished Lecturer Series
- Kelco Aerial  Photograph Collection
- Scientific Voyages and Expedition Reports

### Please Note

- At this time, only the Kelco CLR is public (objects are not viewable). The other four collections are curator only. 
- All CLRs should be public and all objects should display metadata only. 
- Test first on **staging** to ensure our overrides, thumbnails, and notes are working as expected. I suspect that the notes will have to be updated based on the local attribution note.

[metadataonly.xlsx](https://github.com/ucsdlib/damspas/files/1364123/metadataonly.xlsx)

### Related Resources  
#409 
#410 
#411 
#413 
#415

**Comment by arwenhutt** [comment]
@gamontoya what's the priority for this in relation to current collection ingest work?

**Comment by gamontoya** [comment]
@arwenhutt I'm happy letting you set the priority based on DOMM's current workload. I was not given a deadline by anyone, so...

**Comment by arwenhutt** [comment]
@gamontoya Since this falls under dldp/sca collection editing, without expressed priorities or urgency from steering, my assumption is that it's lower priority then current dldp/sca project/ingest work, since for that portfolio of work, new ingest is usually given priority.

**Comment by gamontoya** [comment]
@arwenhutt I agree with your assumption.

**Comment by arwenhutt** [comment]
Cool, let me know if anything changes :)

**Comment by remerjohnson** [comment]
Just putting this here for whenever we want to explore this further...  

I did a test ingest for metadata-only objects on staging (we have an upcoming metadata-only request for future Blackburn batches), but can't seem to release them. I used the release tool on staging, but the objects remain as curator-only. The CLR is visible. 

http://librarytest.ucsd.edu/dc/collection/bd6160587j

**Comment by gamontoya** [comment]
**Note:** Object display behavior and specs are forthcoming.

**Comment by gamontoya** [comment]
IT Dev will do this work once metadata-only visibility is fully implemented.

**Comment by lsitu** [comment]
@gamontoya As a UCSD IP users, do they still be able to access the objects in these collections once we change them from "localDisplay" to metadta-only (metadataDisplay)? In other words, what's the difference for "localDisplay" and metadta-only objects when access from UCSD campus?

**Comment by gamontoya** [comment]
@lsitu There isn't really a difference in behavior between these two, but we probably need to keep both since not all collections that are _localDisplay_ will also be _meatdataDisplay_ be default.

@mcritchlow Do you agree?

**Comment by lsitu** [comment]
@gamontoya Thanks. Will these meatdataDisplay objects be allowed to access from UCSD campus or not? Are there any differences/conflicts with the metadataDisplay objects in Oceania collections like Keesing, Lambert Photographs etc.?

**Comment by gamontoya** [comment]
- If collection X is UCSD IP only and metadata-only for public, as an _**authenticated user**_, I should be able to get to the content.
- If collection X is UCSD IP only and metadata-only for public, as an _**unauthenticated user**_, I should not be able to get to the content.
- If collection X is UCSD IP only and metadata-only for public, as a **_curator_**, I should be able to access all content (download master files).

## Reference page:

- https://lisn.ucsd.edu/display/dlpg/DAMS4+Metadata-Only+Display+Specifications

**Comment by gamontoya** [comment]
- Lambert = 23 cultural sensitivity, but can display metadata to public
- Keesing = 883 cultural sensitivity, but can display metadata to public

We need to test these collections on QA/Stage to make sure they are working as expected after you're done.

**Comment by lsitu** [comment]
@gamontoya Thanks. With that said, we need to update access control:
- Display metadata to public for both localDisplay and metadataDisplay objects. 
- Allow both localDisplay and metadataDisplay objects that are in a CLR with local visibility value to be accessible (be able to get the content) on campus.
- Disallow those metadataDisplay objects in Lambert and Keesing, which with a CLR that has a visibility value other than local, from getting their contents on campus.

Please correct me if I miss anything. Thanks.

**Comment by lsitu** [comment]
@gamontoya It looks like we should not make the changes on prod now. It'll block the access to these collections on campus once we change them to metadata only.
Should we hold off the ticket until we deploy damsrepo to prod with access control for UCSD IP /metadata-only access control? Or just make the change for those collections that we want to test on staging for now and do it later when the support for UCSD IP /metadata-only feature is ready on prod?

**Comment by gamontoya** [comment]
Can you make the changes for these affected collections on staging on? I'm not ready for any of this code to go to production without it being fully tested.

**Comment by lsitu** [comment]
@gamontoya Sure. I'll make the change on staging for now.

**Comment by gamontoya** [comment]
@lsitu Great! This will be easier for DLDP/RDCP folks to vet if they can see the behavior on staging.

**Comment by gamontoya** [comment]
It is not showing it Access Status at the collection grid view and at the collection level. Looks fine at the object level.

@lsitu @VivianChu Which one of you can fix this?

**Comment by VivianChu** [comment]
@gamontoya - Could you check again?  They show up fine for me.
https://librarytest.ucsd.edu/dc/collections?f%5Btype_sim%5D%5B%5D=Collection&page=2&sort=title_ssi+asc
https://librarytest.ucsd.edu/dc/collection/bb10936072

**Comment by lsitu** [comment]
@gamontoya Do you use QA or staging for your test? I am updating those UCSDIP/metadata-only collections on QA at this time, which will take some time. I'll let you know once all those collections are updated and indexed on SOLR.

**Comment by gamontoya** [comment]
Oh, I was testing on staging. Okay, let me confirm on QA then,

**Comment by lsitu** [comment]
@gamontoya I've updated all those 5 UCSDIP/metadata-only collections above on QA and the SOLR re-indexing process is done. I think you can test it QA now.
Do you have any other collections that you want to test? I think we may need to update SOLR for those collections as well. Thanks.

**Comment by gamontoya** [comment]
See #466

**Comment by gamontoya** [comment]
Closing for now. Testing of these collections and other dummy test records will begin.

**Comment by gamontoya** [comment]
To remain open until code is pushed to prod and testing has been completed.

**Comment by gamontoya** [comment]
These collections must be fixed in Prod once the above has been addressed.

**Comment by gamontoya** [comment]
**Note:** Fix #515 before re-indexing these collections.

**Comment by lsitu** [comment]
@gamontoya I think the metadata changes for those five UCSD IP/metadata-only collections are done on prod and all 8 collections listed above are re-indexed. Please let me know if you see anything is missing. Thanks.

**Comment by gamontoya** [comment]
@VivianChu @lsitu Congratulations! Confirming that every collection affected is behaving as expected.

Excellent job, Vivian and Longshou! Very good work!
