### ISSUE TITLE
omniauth security vulnerability

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damspas#357]
### Descriptive summary

https://gemnasium.com/github.com/ucsdlib/damspas/alerts#alert-6269566

**Comment by mcritchlow** [comment]
@ucsdlib/developers - if anyone has any cycles this week to take this, please do.

**Comment by VivianChu** [comment]
@mcritchlow - I can take it

**Comment by mcritchlow** [comment]
Thanks @VivianChu!
