### ISSUE TITLE
Update attribution note for all objects referencing DLDP

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#360]
### Descriptive summary

**Global updates needed for all attribution notes**

Digital Library Development Program:

> Digital Object Made Available By
> Digital Library Development Program, UC San Diego, La Jolla, 92093-0175 
> (http://libraries.ucsd.edu/about/digital-library/)

Update URL to:

- http://lib.ucsd.edu/digital-library 

> Digital Object Made Available By
> Special Collections & Archives, UC San Diego, La Jolla, 92093-0175
> (http://libraries.ucsd.edu/collections/sca/)

Update URL to:

- http://lib.ucsd.edu/sca 

> Digital Object Made Available By
> Research Data Curation Program, UC San Diego, La Jolla, 92093-0175
> (https://library.ucsd.edu/research-and-collections/data-curation/)

Update URL to:

- http://lib.ucsd.edu/rdcp

**Comment by gamontoya** [comment]
@lsitu If you have the bandwidth for this Sprint.

**Comment by lsitu** [comment]
@gamontoya Sure. I'll work on it.

**Comment by lsitu** [comment]
@gamontoya It looks like there is a variation "http://libraries.ucsd.edu/services/data-curation/" for "https://library.ucsd.edu/research-and-collections/data-curation/". Do we need to change it to "http://lib.ucsd.edu/rdcp" as well? For example, https://library.ucsd.edu/dc/object/bb4303245q.

**Comment by lsitu** [comment]
@mcritchlow I also updated Excel Input Stream tool in DAMS Manager for the local attribution note changes. It's ready for review now: https://github.com/ucsdlib/damsmanager/pull/191. Thanks.

**Comment by lsitu** [comment]
@gamontoya Just an update that the local attribution notes for all objects referencing DLDP wre updated for the URL on prod last week. Most of the objects in DAMS are affected by this change and the SOLR indexing process is still ongoing. There are still around 30,000 items in the queue that could take another two days.
It look like some RCI objects use a URL like "http://libraries.ucsd.edu/services/data-curation/", which is not in the ticket description text. Please let me know if we need to change it to  http://lib.ucsd.edu/rdcp as well.

**Comment by gamontoya** [comment]
@lsitu Thank you Longshou. Yes, please update http://libraries.ucsd.edu/services/data-curation/

**Comment by gamontoya** [comment]
@lsitu Please update the program URLs to use https instead of http. All records will need to be-reindexed again.

- https://lib.ucsd.edu/sca
- https://lib.ucsd.edu/digital-library
- https://lib.ucsd.edu/rdcp

**Comment by lsitu** [comment]
Reopen it since we need to update the local attribution notes to use https.

**Comment by lsitu** [comment]
@gamontoya I think we've change the local attributions notes to use https instead of http for objects that referencing DLDP. 
There are total 109,288 objects affected and the SOLR re-indexing process is delayed with around 990,000 items in the queue at this time. Hopefully this could be one by the end of next Week.

**Comment by gamontoya** [comment]
@lsitu https for RDCP, SC&A, and DLDP objects, not DLDP, correct?

**Comment by lsitu** [comment]
@gamontoya Right. All objects with the following references:
https://lib.ucsd.edu/sca
https://lib.ucsd.edu/digital-library
https://lib.ucsd.edu/rdcp

**Comment by lsitu** [comment]
@gamontoya Solr re-indexing is done and I think it's ready for you to review now. Thanks.

**Comment by gamontoya** [comment]
@lsitu Looks good! Thank you.
