### ISSUE TITLE
Distorted item view display for RDCP collection

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#361]
### Descriptive summary

If using this URL to get to the item view display for the Southern Ocean Carbon and Climate Observations and Modeling collection, the item display is skewed starting from the third object down:

https://library.ucsd.edu/dc/search?utf8=%E2%9C%93&q=bb4473712z

![001](https://user-images.githubusercontent.com/4314914/33503928-62758098-d69a-11e7-8321-c4a21cd423fb.png)

### Steps to reproduce the behavior

- Go to DC Home Page and enter the ARK (bb4473712z)
- Note that you are taken to a results page that lists the collection record + items
- This odd display does not happen when you are in the collection record and you click on the View Items

### To Do

@VivianChu will ingest this collection onto the staging environment to better troubleshoot.

**Comment by VivianChu** [comment]
@gamontoya - The problem has been fixed locally.  Attached is the screen shot.  I'll let you know when this fix get deploy to staging.  Thanks
![note_search](https://user-images.githubusercontent.com/1864660/33745320-01236604-db6b-11e7-9973-71aa73b6ca5f.png)

**Comment by gamontoya** [comment]
@VivianChu Good work Vivian.
