### ISSUE TITLE
Permanently delete objects/files from DAMS (Solr, file store, etc.)

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#362]
### Descriptive summary

While doing QC of the RDCP collections transfer to DPN, I found the following issues:

Scripps CO2 Program Data - bb3381541w | Confirmed with Ryan that these files should be deleted in both DAMS and DPN (rdf + content files):

- bb0139192t/20775-bb0139192t-0-rdf.xml
- bb0480492c/20775-bb0480492c-0-rdf.xml
- bb3620455b/20775-bb3620455b-0-rdf.xml
- bb3961753m/20775-bb3961753m-0-rdf.xml
- bb4303052r/20775-bb4303052r-0-rdf.xml
- bb4610222c/20775-bb4610222c-0-rdf.xml
- bb4951522p/20775-bb4951522p-0-rdf.xml
- bb5292823c/20775-bb5292823c-0-rdf.xml
- bb8432784p/20775-bb8432784p-0-rdf.xml
- bb8774083d/20775-bb8774083d-0-rdf.xml
- bb9115382m/20775-bb9115382m-0-rdf.xml
- bb9456682x/20775-bb9456682x-0-rdf.xml
- bb9797985s/20775-bb9797985s-0-rdf.xml

 
Teaching Bee - bb6725113c | These 45 should be deleted from the DAMS and DPN (rdf + content files):

- bb0888881v-2-2.mp4
- bb12301807-0-2.mp4
- bb2185821x-1-2.mp4
- bb2527121q-0-2.mp4
- bb3824064v-0-2.mp4
- bb5121003d-0-2.mp4
- bb7032284r-1-2.mp4
- bb7032284r-10-2.mp4
- bb7032284r-11-2.mp4
- bb7032284r-12-2.mp4
- bb7032284r-13-2.mp4
- bb7032284r-14-2.mp4
- bb7032284r-15-2.mp4
- bb7032284r-16-2.mp4
- bb7032284r-17-2.mp4
- bb7032284r-18-2.mp4
- bb7032284r-19-2.mp4
- bb7032284r-2-2.mp4
- bb7032284r-20-2.mp4
- bb7032284r-21-2.mp4
- bb7032284r-22-2.mp4
- bb7032284r-23-2.mp4
- bb7032284r-24-2.mp4
- bb7032284r-25-2.mp4
- bb7032284r-26-2.mp4
- bb7032284r-27-2.mp4
- bb7032284r-28-2.mp4
- bb7032284r-29-2.mp4
- bb7032284r-3-2.mp4
- bb7032284r-30-2.mp4
- bb7032284r-31-2.mp4
- bb7032284r-4-2.mp4
- bb7032284r-6-2.mp4
- bb7032284r-7-2.mp4
- bb7032284r-8-2.mp4
- bb7032284r-9-2.mp4
- bb73394544-2-2.mp4
- bb76807535-1-2.mp4
- bb76807535-2-2.mp4
- bb9592033j-0-2.mp4
- bb9933331c-0-2.mp4

### Rationale
Once this work is complete, Gabriela will ask Ron to resync these collections to DPN.

**Comment by lsitu** [comment]
@gamontoya For those rdf.xml like bb0139192t/20775-bb0139192t-0-rdf.xml, I think we insert those stub records purposely for keeping track of the deletion of that ARK. For example, [bb0139192t/20775-bb0139192t-0-rdf.xml](http://lib-hydratail-prod.ucsd.edu:8080/dams/api/files/bb0139192t/rdf.xml) includes the event to keep track of who is taking the last action to delete the record.
I don't know why those records were sent to DPN since they won't link to any collections once they were deleted. Maybe the ARK list is outdated or just coincide with the deletion action while waiting for SOLR indexing?

I think we can simply deleted them from DPN. But do you still want to delete them from the filestore in this case?

**Comment by lsitu** [comment]
@gamontoya I've deleted all those .mp4 files above from the filestore. What do you think regarding those rdf.xm stub records that mark the deletion like bb0139192t/20775-bb0139192t-0-rdf.xml?

**Comment by gamontoya** [comment]
@lsitu I'm not sure those "tombstone" records are of any value. I'm sure there were a lot of other objects that have been deleted from the DAMS, but we never kept rdf records for them, or do/have we? @mcritchlow What do you think? Should I consult DOMM?

**Comment by lsitu** [comment]
@gamontoya I think we create a "tombstone" record for every record that was deleted from DAMS4 by default, which was added by damsrepo with a delete event. I believe the rdf.xml files list above are just a small part of those "tombstone" records. However, I think we could change it if we see it meaningless.

**Comment by gamontoya** [comment]
@lsitu Just spoke to Arwen and Jessica and we agreed to leave those tombstone records for now. Thanks Longshou.

**Comment by gamontoya** [comment]
@lsitu So is this work complete? If so, can you reply to Ron in the original email letting him know the clean up/deletions work is done?

**Comment by lsitu** [comment]
@gamontoya I only deleted those 41 .mp4 files above at this time. Is there anything else that you want me to cleanup?

**Comment by gamontoya** [comment]
@lsitu That should be it since we're keeping those tombstone records.

**Comment by lsitu** [comment]
Thanks @gamontoya .
@rstanonik I've deleted all those .mp4 derivatives above. I think you can resync those two collections above to DPN now. Thanks.

**Comment by rstanonik** [comment]
I'm resync'ing.
I'll tell you when it's done.

**Comment by rstanonik** [comment]
Resyncing finished and DPN is ready for QC again.

**Comment by gamontoya** [comment]
@VivianChu Are you able to delete a bogus mp4 derivative that Longshou missed?

- First step, ensure it's not still in the file store.
- If so, delete.
- Re-index Solr for this collection?

**Comment by gamontoya** [comment]
@VivianChu @rstanonik 

Correction.

- Delete from DAMS: bb0888881v/20775-bb0888881v-1-2.mp4
- Re-index bb6725113c
- Ron will then sync to DPN

**Comment by VivianChu** [comment]
@rstanonik @gamontoya 
The mp4 file has been deleted.  The collection bb6725113c has been re-index.
Ron - Could you sync that collection Teaching Bee bb6725113c to DPN?  Thanks

**Comment by rstanonik** [comment]
I sync'ed Teaching Bee bb6725113c to DPN.
bb0888881v/20775-bb0888881v-1-2.mp4 was deleted.
bb0888881v/20775-bb0888881v-0-rdf.xml was updated.

**Comment by gamontoya** [comment]
@VivianChu Sorry Vivian. I just caught this other bogus mp4. Can you delete bb73394544/20775-bb73394544-3-2.mp4

Can you delete,  re-index, and then ask @rstanonik  to sync Teaching Bee bb6725113c to DPN again?

**Comment by VivianChu** [comment]
@rstanonik @gamontoya
The mp4 file 20775-bb73394544-3-2.mp4 has been deleted. The collection bb6725113c has been re-index.
Ron - Could you sync that collection Teaching Bee bb6725113c to DPN again? Thanks

**Comment by rstanonik** [comment]
I sync'ed to DPN.
DELETED    bb73394544/20775-bb73394544-3-2.mp4
UPDATED   bb73394544/20775-bb73394544-0-rdf.xml

**Comment by gamontoya** [comment]
Thank you @VivianChu and @rstanonik !
