### ISSUE TITLE
Statistics: investigate potential new URL crawling patterns

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#364]
### Descriptive summary

Looking at the statistics for the end of November, there are three huge spikes that are suspect.

![stats](https://user-images.githubusercontent.com/4314914/33694798-e99bb76e-daae-11e7-8204-c4592fb1a972.png)

### To Do

- Look for new spiders/bots crawling our site.
- Look at the web logs to see what patterns need to be excluded from the stats.

**Comment by lsitu** [comment]
@gamontoya I think Microsoft (IP: 157.55.175.83, 52.168.19.139) contributed to the peak at Nov. 27 (8793 hits) and Dec. 04 (8600). While the peak at Nov. 30 is normal with https://library.ucsd.edu/speccoll/ (2095 hits) and /dc/ucsd.ico (5393 hits).
There is no obvious pattern to be identified Microsoft as a bot but the browser type is "Mozilla/5.0 (Windows NT 6.2; WOW64; Trident/7.0; rv:11.0) like Gecko SortSiteCmd/5.27.804.0". Here are several URL grab from the weblog from Nov 27:
Nov 27 13:25:46 library apache[5700]: library.ucsd.edu 157.55.175.83 - - [27/Nov/2017:13:25:44 -0800] "GET /dc HTTP/1.1" 200 12915 "https://library.ucsd.edu/dc" "Mozilla/5.0 (Windows NT 6.2; WOW64; Trident/7.0; rv:11.0) like Gecko SortSiteCmd/5.27.804.0"
Nov 27 13:26:33 library apache[5699]: library.ucsd.edu 157.55.175.83 - - [27/Nov/2017:13:26:33 -0800] "GET /dc/p/faq HTTP/1.1" 302 300 "http://library.ucsd.edu/dc/p/faq" "Mozilla/5.0 (Windows NT 6.2; WOW64; Trident/7.0; rv:11.0) like Gecko SortSiteCmd/5.27.804.0"
Nov 27 13:26:33 library apache[5700]: library.ucsd.edu 157.55.175.83 - - [27/Nov/2017:13:26:33 -0800] "GET /dc/p/faq HTTP/1.1" 200 22352 "http://library.ucsd.edu/dc/p/faq" "Mozilla/5.0 (Windows NT 6.2; WOW64; Trident/7.0; rv:11.0) like Gecko SortSiteCmd/5.27.804.0"

I'll eliminate browser type that contains value " SortSiteCmd/" from being counted as hits, and exclude the URL /dc/ucsd.ico from being counted as well.

**Comment by lsitu** [comment]
@rstanonik It seems like that Tomcat was not restarted cleanly last deployment and a stalled thread was running at the same time for dams route background work. I have to run the dams stats process again to regenerate the stats starting from November 2nd. But I don't see the problem in the latest deployment. It once happened in the past when we changed the deployment process.  With Jenkins, are we able to enforce a clean tomcat restart after damsmanager deployed or not?
Could we dump all records on table WEB_STATS? I need to see what else we need to cleanup. And for the long run, I think creating unique index on table WEB_STATS for column APP_NAME and column STAT_DATE could help. Could we try the following script to see how it goes, @jgorney?  
create unique index UIDX_WEB_STATS_STAT_DATE on WEB_STATS (APP_NAME, date_trunc('day', STAT_DATE))

Thanks.

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/damsmanager/pull/196 to eliminate the stats counts from Microsoft and the resource url. It's ready for review now. Thanks.

**Comment by rstanonik** [comment]
I changed the jenkins damsmanager plan in staging and "Dams4 Prod" to restart the tomcat after deploy.

**Comment by lsitu** [comment]
That sounds good. Thanks @rstanonik.
