### ISSUE TITLE
Create tiles (zoom) for object

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#367]
### Descriptive summary

- https://library.ucsd.edu/dc/object/bb0446443f

Component 4 (AMS m/z spectra for five non-refractory species) shows in the component preview, but when clicked to view in zoom viewer, no image loads.

Please create the tiles.

**Comment by gamontoya** [comment]
@jessicahilt This ticket is ready for assignment.

**Comment by lsitu** [comment]
@gamontoya I think the tiles are already generated over the weekend.

**Comment by gamontoya** [comment]
@lsitu On prod? I'm getting nothing with this URL: https://library.ucsd.edu/dc/object/bb0446443f/zoom/4

**Comment by lsitu** [comment]
@gamontoya Hmm, I think I was looking at the wrong component. I'll take a look.

**Comment by lsitu** [comment]
@hjsyoo I found that component 4 is a PDF file while its file use is set to "image-source". Do you mind if I change it to "document-service"?

**Comment by hjsyoo** [comment]
@lsitu Yes, please do! Glad the problem was fairly straightforward.

**Comment by hjsyoo** [comment]
@remerjohnson I just looked up a similar collection (wacs1) and found that .pdf plots have Type of Resource = text. Should the .pdf plot mentioned here also be changed to "text"?

**Comment by remerjohnson** [comment]
@hjsyoo As noted above, I think the most crucial part is what the "file use" value is. PDF files need to be "document-service" in order to behave correctly. This makes the "type of resource" value a little sketchy, since technically it is a still image but it is being treated like a text file for the sake of generating the correct derivatives. I think we normally just put it as "text" to be safe/consistent

**Comment by lsitu** [comment]
@gamontoya @hjsyoo I've updated the record to correct the file use of the PDF in component 4, and updated the Type of Resource to "text". And the missing tiles/zoom for component 4 is no longer to be an issue for https://library.ucsd.edu/dc/object/bb0446443f now.

**Comment by gamontoya** [comment]
Looks good @lsitu . Thank you!

**Comment by hjsyoo** [comment]
Thank you @lsitu
