### ISSUE TITLE
Delete test collection and object

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#369]
### Descriptive summary

This collection level record and single object need to be deleted from the Solr index, file store, etc. Accidentally ingested into prod:

Object:

- http://library.ucsd.edu/ark:/20775/bb9525675s

Collection Level Record:

- https://library.ucsd.edu/dc/collection/bb2085336d (edited)

**Comment by jhriv** [comment]
```
bb/95/25/67/5s
20775-bb9525675s-0-1.jpg  20775-bb9525675s-0-4.jpg  20775-bb9525675s-0-7.jpg
20775-bb9525675s-0-2.jpg  20775-bb9525675s-0-5.jpg  20775-bb9525675s-0-rdf.xml
20775-bb9525675s-0-3.jpg  20775-bb9525675s-0-6.jpg
```

```
bb/20/85/33/6d
20775-bb2085336d-0-rdf.xml
```

have been removed

**Comment by VivianChu** [comment]
@gamontoya - These records have been deleted and the solr index has been updated.

**Comment by gamontoya** [comment]
Thank you @VivianChu and @jhriv
