### ISSUE TITLE
New sync for Prod to QA

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#385]
### Descriptive summary

- Starting a new round of subject conversion testing. 
- Need to align the QA environment with Prod.

### To Do:

- [x] Sync Solr index from Prod to QA.
- [x] Sync Triplestore db from Prod to QA.
- [x] Sync Filestore from Prod to QA.
- [x] Restart DAMS Solrizer on QA.

**Comment by gamontoya** [comment]
@mcritchlow Can you look this over and let add steps that may be missing/needed?

**Comment by mcritchlow** [comment]
@gamontoya - nice, thanks for writing this up 👏 !

I'm not sure whether any of the `Deploy` steps are actually needed as I think things have been kept up to date there, but would be good to confirm with @lsitu. Worst case we get to check off a bunch of things quickly from the list :)

Otherwise I guess we just need to ensure that `Sync` will get us back to a clean starting point, and not just add in new content, for example.

**Comment by lsitu** [comment]
@mcritchlow @gamontoya I think we could ignore those deploy steps since I don't think the the updates in those apps could affect the Subject Conversion process.

**Comment by gamontoya** [comment]
@mcritchlow @lsitu Much easier then. We are down to 4 steps only.

**Comment by jgorney** [comment]
Hi - I'll coordinate with Ron on the steps we need to perform.

**Comment by rstanonik** [comment]
We can perform the sync, but are we waiting to hear from @lsitu whether a sync is ncessary?

**Comment by lsitu** [comment]
@rstanonik Yes, its's necessary. Thanks. We are going to start a new round of testing with the Subject conversion process. See https://github.com/ucsdlib/damsmanager/issues/190#issuecomment-357351964.

**Comment by rstanonik** [comment]
I'm starting the filestore sync.  I'll give an estimate of the time required, after it has run a while.

**Comment by rstanonik** [comment]
Looking at the log from the last sync on 2017-10-10, that sync took nine hours.

**Comment by jgorney** [comment]
I'll start the triplestore DB sync right now.

**Comment by rstanonik** [comment]
I started the solr sync.

The filestore is 5% done in 13 minutes, so estimated time to completion is 13/.05 =  260 minutes or between 4 and 5 hours.

**Comment by rstanonik** [comment]
25% done in one hour, so probably another three hours

**Comment by rstanonik** [comment]
51% in two hours, so another two hours to go.

**Comment by jgorney** [comment]
The Triplestore db sync is complete, including indexes.

**Comment by rstanonik** [comment]
The filestore sync from prod to QA finished.

The solr sync from prod to QA finished.

The DAMS solrizer on QA was restarted

**Comment by rstanonik** [comment]
QA is ready.

**Comment by gamontoya** [comment]
@rstanonik @jgorney Thank you two!

**Comment by gamontoya** [comment]
@arwenhutt @lsitu The QA environment is now ready for the next round.

**Comment by rstanonik** [comment]
QA damsolrizer died

**Comment by arwenhutt** [comment]
@gamontoya @lsitu the data input file and ticket for Take 2: Stage 1 is not ready yet.  I'll let you all know as soon as it is though.

**Comment by rstanonik** [comment]
There were two solrizers running (old and new?).
I killed both and started one.
