### ISSUE TITLE
Papua New Guinea Patrol Reports - Fix typo

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#397]
### Descriptive summary

Papua New Guinea Patrol Reports (Northern District) have a typo in **Title, Location of Original**s, and **Cite this Work**.

There are roughly 159 objects affected. See:

- https://library.ucsd.edu/dc/search?page=8&q=%22Nothern%22&spellcheck.q=%22Nothern%22&utf8=%E2%9C%93

### Fix

Correct misspelled **_Nothern_** to **Northern**.

### Examples of typos

**Title:**
Patrol Reports. **Nothern** District, Kokoda... (should be **Northern**)

Cite This Work:
Patrol Reports. **Nothern** District, Kokoda, 1953 - 1955... (should be **Northern**)

Location Of Originals:
This digital object is a surrogate of an item from the National Archives of Papua New Guinea (Accession no. 496, **Nothern**... (should be **Northern**)

**Comment by gamontoya** [comment]
@lsitu Can you take this on?

**Comment by lsitu** [comment]
@gamontoya Sure. I'll work on it.

**Comment by lsitu** [comment]
@gamontoya I've corrected 600 misspelled "Nothern" typo in those 159 records above. These is what I see in the metadata. But I can still see 9 records with the typo "Nothern", which are coming from the PDF fulltext extraction: https://library.ucsd.edu/dc/search?&q=Nothern&utf8=%E2%9C%93.
What else do we need to do in this ticket?

**Comment by gamontoya** [comment]
@lsitu The PDFs actually have the typos in them, so we'll leave as is. This ticket is complete.
