### ISSUE TITLE
Curator master download link not working

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#402]
### Descriptive summary

For some objects in the Harry Crosby collection, the master download link if signed in as curator results in a 404 error:

- https://library.ucsd.edu/dc/object/bb73733028/_1.tif/download?access=curator

Seems to affect 59 objects:

- https://library.ucsd.edu/dc/search?utf8=%E2%9C%93&q=%22Carnival%2C+UCSD%22

**_A global check should be done (if possible) to see if there are other collections affected._**

### Expected behavior

Can download master TIFF

### Actual behavior

- Not Found
- The page you were looking for does not exist.
- Response Status Code 404

### Notes
Per Longshou: It looks like those files are still using the old file URL that we once used in the past, which has 0 as the file index.

### Related work

See: #403 as these two are related

**Comment by gamontoya** [comment]
@jessicahilt Ready to be assigned.

**Comment by lsitu** [comment]
@gamontoya @jessicahilt We need to clean those file URLs, and I can work on it.

**Comment by lsitu** [comment]
@gamontoya I've done a global check and found the following 950 objects have this stale file URL pattern:
[report_file_url.txt](https://github.com/ucsdlib/damspas/files/1705184/report_file_url.txt)

I'll move ahead to correct them all once you confirm about it. Thanks.

**Comment by gamontoya** [comment]
@lsitu Yes, looks good. Thank you for proceeding with this.

**Comment by gamontoya** [comment]
@lsitu I'm guessing these objects will form part of #403

**Comment by lsitu** [comment]
Hi Gabriela,
I've fixed the stale file url pattern issue with all 950 object reported above. Curators should be able to download those master tif files for damspas now. 

Yes, I think this could be part of the reason for #403. Let me check what else could be an issue with it.

**Comment by gamontoya** [comment]
@lsitu Awesome. Thank you.
