### ISSUE TITLE
Investigate Zoom issue 

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#403]
### Descriptive summary

Zoom is not working for this set of images:

- https://library.ucsd.edu/dc/search?utf8=%E2%9C%93&q=%22Carnival%2C+UCSD%22

Create zoom tiles if they do not exist.

### Related work

See #402 before starting on this ticket.

**Comment by gamontoya** [comment]
@jessicahilt Ready to be assigned.

**Comment by lsitu** [comment]
@rstanonik It looks like we've got some issues with zoomify tiles creation in the past but we don't know about. Where the zoomify tiles for the prod environment is located? Thanks.

**Comment by rstanonik** [comment]
lib-ingest mounts the zoomify tiles on /pub/data1/zoomify

Is that what you need?

**Comment by lsitu** [comment]
@rstanonik Yes. Can I have read access from brilthor or somewhere else?

**Comment by rstanonik** [comment]
I mounted it on brilthor on /pub/data3/zoomify-prod.

**Comment by lsitu** [comment]
That sounds good. Thanks @rstanonik.

**Comment by lsitu** [comment]
@rstanonik I found the following images have the wrong zoomify tiles folder name with '-0' appended in  /pub/data3/zoomify-prod:
[error_zoomify_tiles.txt](https://github.com/ucsdlib/damspas/files/1717285/error_zoomify_tiles.txt)

Could we rename those zoomify tile folders to remove "-0" from the end? I think rerun the zoomify tiles creation process could fix the zoomify issue too. What do you think?

**Comment by lsitu** [comment]
@rstanonik Have you got a chance to look into those zoomify tiles in file [error_zoomify_tiles.txt](https://github.com/ucsdlib/damspas/files/1717285/error_zoomify_tiles.txt) Thanks.

**Comment by rstanonik** [comment]
I'm creating a script now to rename them.
Should have it soon.

**Comment by rstanonik** [comment]
They've been renamed.

**Comment by lsitu** [comment]
Thanks @rstanonik. 
@gamontoya I think the zoom issue should be fixed for those images now. Here is the first one: https://library.ucsd.edu/dc/object/bb3755523v/zoom/0.

**Comment by gamontoya** [comment]
@lsitu @rstanonik Thank you both.

**Comment by gamontoya** [comment]
@mdpeters This issue is now resolved.
