### ISSUE TITLE
Browse by collection view

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#409]
### Descriptive summary

- As a user, I should see the collection's thumbnail and brief description.
- As a user, below the description, I should see all Access notes with the exception of "Curator Only"

### Expected Behavior

The access note for **metadata-only view** collections should say:

**Access**
- **Restricted View**

### Example View

![collection](https://user-images.githubusercontent.com/4314914/37670218-fe433e94-2c25-11e8-85fd-346a1317d7ab.png)

-------------------------------------------
### Reference
[Full specifications](https://lisn.ucsd.edu/display/dlpg/DAMS4+Metadata-Only+Display+Specifications)

**Comment by VivianChu** [comment]
@gamontoya - Here's the screen shot of browse by collection page for my local damspas.  I just created a PR and waited for it to get review.
![browse_by_collection](https://user-images.githubusercontent.com/1864660/38694695-260f13b4-3e3f-11e8-887e-883d92cbfb82.png)

**Comment by gamontoya** [comment]
@VivianChu Looks exactly like what we want.

**Comment by gamontoya** [comment]
@VivianChu Looks good!
