### ISSUE TITLE
Items view

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#411]
### Descriptive summary

- As a user, I should see grey generic thumbnails for objects of metadata data-only visibility collections.

### Example View

![objects](https://user-images.githubusercontent.com/4314914/37671311-afc85134-2c28-11e8-9181-6256f1655ffc.png)

-------------------------------------------
### Reference
[Full specifications](https://lisn.ucsd.edu/display/dlpg/DAMS4+Metadata-Only+Display+Specifications)

**Comment by VivianChu** [comment]
@gamontoya - The items view change has been deployed to qa.  Could you review it?  Thanks
For example
http://libraryqa.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=ECE+Distinguished+Lecturer+Series&id=bb19126574
