### ISSUE TITLE
Object level view

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#413]
### Descriptive summary

- As a user, when I click to view an object, I should see a grey generic image with a banner that explains the restriction.
- As a user, when viewing an object, I should see the Access note below the generic image and other displayed metadata.b

### Expected behavior

The banner note should say:

**Restricted View**
Content not available. Access may granted for research purposes at the discretion of the UC San Diego Library. For more information please contact the Digital Library Development Program at dlp@ucsd.edu

Notes: 
- The specific program can vary depending on the collection (can it be auto-populated based on the owning program?)
- AddThis widget can stay.

### Example View
![banner](https://user-images.githubusercontent.com/4314914/37671711-94d20a22-2c29-11e8-9b54-af2c85f0dee1.png)

-------------------------------------------
### Reference
[Full specifications](https://lisn.ucsd.edu/display/dlpg/DAMS4+Metadata-Only+Display+Specifications)

**Comment by VivianChu** [comment]
@gamontoya - The single object view has been updated to display the restricted note.  Attached is the screen shot for my local environment.  I created a PR and waited for it to get reviewed.
![objectviewmetadataonly](https://user-images.githubusercontent.com/1864660/38761531-8ee038e2-3f38-11e8-84fe-09ff37298bb8.png)

**Comment by gamontoya** [comment]
@VivianChu Yay! Good job.

**Comment by gamontoya** [comment]
@VivianChu Those three examples look good. Where is the program information being pulled from on the banner? 

_Digital Library Development Program at dlp@ucsd.edu_

From the attribution note or is it hard coded?

**Comment by VivianChu** [comment]
@gamontoya - It is hard coded. I don't see that value from attribution note - http://lib-hydrahead-qa:8983/solr/blacklight/select?q=bb9591785q&wt=xml&debugQuery=true

**Comment by gamontoya** [comment]
@VivianChu It's in otherNote_json_tesim

```
<arr name="otherNote_json_tesim">
<str>{"id":"b","type":"local attribution","value":"Special Collections \u0026 Archives, UC San Diego, La Jolla, 92093-0175 (https://lib.ucsd.edu/sca)","displayLabel":"digital object made available by","internalOnly":""}</str>
```
So I don't think it should be hard coded. In this case, the value is wrong in your hard coded example.

**Comment by VivianChu** [comment]
@gamontoya - Would the value be this instead
Restricted View
Content not available. Access may granted for research purposes at the discretion of the UC San Diego Library. For more information please contact the Special Collections \u0026 Archives, 
UC San Diego, La Jolla, 92093-0175 (https://lib.ucsd.edu/sca)

**Comment by VivianChu** [comment]
@gamontoya - The view has been updated for my local damspas with the value from the attribution note.  Attached is the screen shot.  Does it look correct to you?  
The attribution for this record is {"id":"_","type":"local attribution","value":"Digital Library Development Program, UC San Diego, La Jolla, 92093-0175 (https://lib.ucsd.edu/digital-library)","displayLabel":"digital object made available by","internalOnly":""}
![simpleobjupdate](https://user-images.githubusercontent.com/1864660/39220330-2fe78f92-47e5-11e8-90fd-bb84248ba3fe.png)

**Comment by gamontoya** [comment]
The text should read:

`Content not available. Access may granted for research purposes at the discretion of the UC San Diego Library. For more information please contact the Digital Library Development Program at dlp@ucsd.edu`

**Comment by VivianChu** [comment]
@gamontoya - @gamontoya - The update for program name has been deployed to qa. Could you review it again? Thanks
For example
http://libraryqa.ucsd.edu/dc/object/bb9591785q
http://libraryqa.ucsd.edu/dc/object/bb1844273v
http://libraryqa.ucsd.edu/dc/object/bb72371287

**Comment by gamontoya** [comment]
@VivianChu They look fine, but once again, if I sign in, I should be able to see the objects and download the derivative and master. If these rules are not yet implemented, let me know.

**Comment by gamontoya** [comment]
@VivianChu I take that back. The email for Special Collections is wrong. It's using the DLP email. Can you not pull the correct email for Special Collections from the attribution note?

**Comment by VivianChu** [comment]
@gamontoya - I don't see email for Special Collections from the attribute note.
http://lib-hydrahead-qa:8983/solr/blacklight/select?q=id:bb9591785q&wt=xml&debugQuery=true
{"id":"b","type":"local attribution","value":"Special Collections \u0026 Archives, UC San Diego, La Jolla, 92093-0175 (https://lib.ucsd.edu/sca)","displayLabel":"digital object made available by","internalOnly":""}
Which email should I use in this case?
I just updated the rule for the object and will deploy it to qa for you to review again when the build is done.

**Comment by gamontoya** [comment]
@VivianChu Okay, we'll have the following use cases:

- Digital Library Development Program
   - dlp@ucsd.edu

- Research Data Curaation Program
   - research-data-curation@ucsd.edu

- Special Collections & Archives
   - spcoll@ucsd.edu

**Comment by VivianChu** [comment]
@gamontoya - The email and the rule update for simple object has been deployed to qa. Could you review it again? Thanks
For example
http://libraryqa.ucsd.edu/dc/object/bb9591785q
http://libraryqa.ucsd.edu/dc/object/bb1844273v
http://libraryqa.ucsd.edu/dc/object/bb72371287

**Comment by gamontoya** [comment]
@VivianChu The banners for all three are missing.
