### ISSUE TITLE
Complex object view

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#415]
### Descriptive summary

- As a user, I should **not** see content in the object viewer. I should see a restriction image (see notes).
- As a user, I should be able to navigate the component tree or use the navigation arrows.
- As a user, I should **not** see a download option.
- As a user, I should be able to see metadata for all components.
 
### Example View

![complex](https://user-images.githubusercontent.com/4314914/37672714-c82bc258-2c2b-11e8-851f-c05c9e3a35d3.png)

### Notes

- What replaces the image, audio, video, etc. is negotiable. It could be the generic restricted image with the banner or just the banner with the suggested restricted text. aFrom a design perspective, whatever works best.

![banner](https://user-images.githubusercontent.com/4314914/37672773-e4e762ee-2c2b-11e8-9ad2-0d516918a81c.png)

![banner3](https://user-images.githubusercontent.com/4314914/37672781-e8e2607e-2c2b-11e8-89d9-3ae8fe4dd8a0.png)

-------------------------------------------
### Reference
[Full specifications](https://lisn.ucsd.edu/display/dlpg/DAMS4+Metadata-Only+Display+Specifications)

**Comment by VivianChu** [comment]
@gamontoya -  Here are the screen shots of different type of complex object from my local damspas.
//complex audio type
![complexobjaudiotype](https://user-images.githubusercontent.com/1864660/39266558-2a20a748-487f-11e8-8903-3b02446cd41f.png)

//complex video type
![complexobjvideotype](https://user-images.githubusercontent.com/1864660/39266574-349ad7c0-487f-11e8-8e2a-6bbc73665216.png)

//complex data type
![complexobjdatatype](https://user-images.githubusercontent.com/1864660/39266579-3b033256-487f-11e8-84a3-427493387075.png)

//complex image type
![complexobjimagetype](https://user-images.githubusercontent.com/1864660/39266584-422b6d14-487f-11e8-91f2-91182476a055.png)

//complex text type
![complexobjtexttype](https://user-images.githubusercontent.com/1864660/39266597-4cc3d57c-487f-11e8-8842-30d6a2d9b005.png)

**Comment by VivianChu** [comment]
@gamontoya - The complex object update has been deployed to qa.  Could you review it?  Thanks
For example
//complex video
http://libraryqa.ucsd.edu/dc/object/bb3756085z
//complex audio
http://libraryqa.ucsd.edu/dc/object/bb0649592q

**Comment by gamontoya** [comment]
Hi Vivian. This isn't exactly right. If you log in, you as a curator should be able to view the objects. So it looks like one step is missing.

**Comment by VivianChu** [comment]
@gamontoya - The update for complex object has been deployed to qa.  Could you review it again? With login and without login. Thanks
For example
//complex video
http://libraryqa.ucsd.edu/dc/object/bb3756085z
//complex audio
http://libraryqa.ucsd.edu/dc/object/bb0649592q

**Comment by gamontoya** [comment]
@VivianChu Looks good.
