### ISSUE TITLE
Implement metadata-only visibility rules for UCSD IP only collections

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#416]
### Descriptive summary

A UCSD IP only collection should have the following behaviors:

- If collection is UCSD IP only and metadata-only for public users, as an **authenticated user**, I should be able to get to the content.
- If collection is UCSD IP only and metadata-only for public users, as an **unauthenticated user**, I should not be able to get to the content.
- If collection is UCSD IP only and metadata-only for public, **as a curator**, I should be able to access all content (download master files).

Notes: 

- authenticated = UCSD IP user
- do we need access overrides?

--------------------------------------------
### Reference
[Full specifications](https://lisn.ucsd.edu/display/dlpg/DAMS4+Metadata-Only+Display+Specifications)

--------------------------------------------
### Related tickets

#409 
#410 
#411 
#413 
#415

**Comment by lsitu** [comment]
@gamontoya Are we going to change the visibility behavior for UCSD IP only collections to allow objects in those collections to be accessed by public user with metadata-only display? 
Are we going to have metadata-only visibility collection, and so we'll have visibility values for collections like public, UCSD-IP only, metadata-only, curator-only or not?

**Comment by gamontoya** [comment]
@lsitu @VivianChu Technically speaking, a collection can be set to:

- UCSD IP only where authenticated users can see the metadata and view the objects, but also be:
- Metadata only where an unauthenticated user (public user) can only see the metadata for the objects.

However, a public collection at some point may also have an **object(s)** that can be set to metadata-only or UCSD IP only, but a public collection will never be set to public + curator only. 

Does this help?

**Comment by lsitu** [comment]
@gamontoya Yes. Thanks for clarifying it.

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/damsrepo/pull/58 to address the access control rules for this support. It's ready for review now. Thanks.

**Comment by gamontoya** [comment]
@gamontoya will close after this is tested.
