### ISSUE TITLE
R&D Test Queries against CIL endpoints

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damspas#436]
### Descriptive summary

In the somewhat near future we will be ingesting a very large collection into the DAMS, the [CIL](http://cellimagelibrary.org/home).

The metadata for this collection is available in a GitHub repository: 

https://github.com/slash-segmentation/CIL_Public_Data_JSON/tree/master/Version8_6/DATA/CIL_PUBLIC_DATA

With instructions in the README on how to use the identifier to construct URLs to download the files associated with a given record/object.

The work for this ticket is an initial test to verify that the JSON metadata can be queried and parsed and that the identifiers can indeed be used to pull down the data files.

Not in scope:
- Metadata mapping from the host schema to DAMS4
- Ingest, yada yada

**Comment by mcritchlow** [comment]
@hjsyoo - I could use some help, perhaps from @wawong to sort out a download issue I'm running into with some initial testing of the CIL json files.

Basically, according to the [README](https://github.com/slash-segmentation/CIL_Public_Data_JSON/blob/master/README.md)  one can determine that they are downloading video or audio files based on the value of `$json->CIL_CCDB->Data_type->Video`. And then use the URL base path as indicated next to pull the various file types.

In my initial tests however, I was unable to download any `tif` files, I got 404's for each one. The `jpg` and `zip` files download successfully. All the noted files on the video base URL `flv` `jpg` `zip` downloaded successfully in the several records I tried.

Here's a quick ruby script I mocked up for doing this testing:
```
# Ruby script to test out parsing the CIL json data
#
require 'open-uri'
require 'json'
require 'byebug'

data_path = 'CIL_Public_Data_JSON/Version8_6/DATA/CIL_PUBLIC_DATA'
default_file_types = ['jpg', 'zip']
video_base_url = 'https://cildata.crbs.ucsd.edu/media/videos/'
image_base_url = 'https://cildata.crbs.ucsd.edu/media/images/'

# For now just grab a couple samples
results = Dir.children(data_path).take(100)

results.each do |json_record|
  identifier = json_record.split('.')[0]

  file = File.read(data_path + '/' + json_record)
  metadata = JSON.parse(file)

  if metadata['CIL_CCDB']['Data_type']['Video']
    # according to the README we can get jpg, flv, zip
    default_file_types.each do |file_type|
      `wget #{video_base_url}/#{identifier}/#{identifier}.#{file_type}`
    end
    `wget #{video_base_url}/#{identifier}/#{identifier}.flv`
  else
    # acconrding to the README we can get jpg, tif, zip
    default_file_types.each do |file_type|
      `wget #{image_base_url}/#{identifier}/#{identifier}.#{file_type}`
    end
    `wget #{video_base_url}/#{identifier}/#{identifier}.tif`
  end
end
```

**Comment by wawong** [comment]
Can you provide the IDs that you have problem with downloading the tiff images?

**Comment by mcritchlow** [comment]
@wawong - I'm pretty sure these were in the list `37197, 40278` I can do a run again and see if any others pop up. Thanks for the quick response!

**Comment by wawong** [comment]
You can go to the website and check http://cellimagelibrary.org/images/37197 and http://cellimagelibrary.org/images/40278

For example, https://cildata.crbs.ucsd.edu/media/images/40278/40278.tif

**Comment by mcritchlow** [comment]
I'm going to close this out linking to the following gist for future reference:

https://gist.github.com/mcritchlow/f133e8bacd32a7d9daaa4b74af4cbcab

The gist has the ruby code above for parsing the git repo and grabbing metadata and downloading files. It also has a short bash script that we could potentially use instead of a REST API, interacting only with the git repository to check for new files added between commits. This might be the fastest way of processing changes.
