### ISSUE TITLE
Test Securetoken in DAMS

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/damspas#448]
### Descriptive summary

SecureToken from Wowza isn't working correctly currently, we would like to see if it can be implemented in a test version of DAMS to see if anything breaks.

**Comment by VivianChu** [comment]
@gamontoya - The secure token update has been deployed to qa.  Could you review it?
For example 
//video simple object
http://libraryqa.ucsd.edu/dc/object/bb8022051s
//audio simple object
http://libraryqa.ucsd.edu/dc/object/bb72371287
//video complex object
http://libraryqa.ucsd.edu/dc/object/bb3756085z
//audio complex object
http://libraryqa.ucsd.edu/dc/object/bb0649592q

Could you also test for token expiration after 5 min?
To test token expiration, click on one of the links and wait six minutes before clicking to play.  You will get an error.  If you click on play immediately, then you can stop and resume without timing out.  The timestamp in the token is an endtime by which you must start streaming. 
Thanks

**Comment by gamontoya** [comment]
@VivianChu The last three are restricted. Should I be able to access them?

**Comment by VivianChu** [comment]
@gamontoya - You can login to access them.  I just chose them randomly.  Or you can select any other video/audio object to try. Thanks

**Comment by gamontoya** [comment]
![timeout](https://user-images.githubusercontent.com/4314914/40737082-8ad6f598-63f4-11e8-85aa-280d9e197ab5.png)

Looks like it's working as expected.

**Comment by VivianChu** [comment]
Thanks Gabriela for testing.

**Comment by gamontoya** [comment]
![noperm](https://user-images.githubusercontent.com/4314914/40738650-f67a4e18-63f8-11e8-8ed6-6647b00f1da8.png)

Audio test (waited 5 min).
