### ISSUE TITLE
Data Sync to Staging/QA

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damspas#455]
### Descriptive summary

In order to test the new work done by @VivianChu and @lsitu on metadata only changes, DOMM and DLP folks need a data sync to ensure things are working as expected. Please sync from prod to staging and QA. This should include everything (triplestore, solr, files, etc.)

### Related work
- #433 
- #425

**Comment by jgorney** [comment]
When's the best time to do this?  Would it be preferable to do this during a service window?

**Comment by mcritchlow** [comment]
@jgorney - I think this is going back to staging/QA, the timing can really be at your discretion. Though that does make me wonder if we need to give the @ucsdlib/domm folks a heads up, so I pinged them :)

**Comment by jgorney** [comment]
Hey Matt, any word on if the sync is ok to start?

**Comment by mcritchlow** [comment]
@arwenhutt @remerjohnson @GregReser - any issues with us starting to sync to staging/qa?

**Comment by arwenhutt** [comment]
@jgorney @mcritchlow I don't have any test collections in staging. 

@GregReser do you have any test ingests on staging being qa'd at the moment?

**Comment by lsitu** [comment]
@jgorney @rstanonik @mcritchlow While waiting for the response from @GregReser for staging, could we do the sync for QA first? I'll update those UCSD IP/metadata-only collections in ticket https://github.com/ucsdlib/damspas/issues/356 once the sync is done. Thanks.

**Comment by mcritchlow** [comment]
Sounds like a good idea to me @lsitu :+1:

**Comment by gamontoya** [comment]
@lsitu Feel free to sync to prod as well. We are not waiting on @GregReser at this time.

**Comment by lsitu** [comment]
Thank you all. 
@rstanonik /@jgorney So we are ready to do the sync for both Staging and QA now. Thanks.

**Comment by GregReser** [comment]
Sorry everyone, I wasn't subscribed to this thread and didn't know you were waiting on me.

**Comment by rstanonik** [comment]
I'm starting the filestore sync from prod to staging and qa.  I'll give you an estimate of the time, after it has run for a wile.

**Comment by jgorney** [comment]
I've started the database triplestore sync as well.

**Comment by jgorney** [comment]
The database triplestore sync is complete.  As always, please let me know if there are any issues.

**Comment by rstanonik** [comment]
qa file sync is 22% done.

staging file sync is 3% done

It's been about 1 1/2 hours, so estimate 8 hours for qa and 2 days for staging.

**Comment by rstanonik** [comment]
By the way, I'm also sync'ing solr from prod to staging and qa.

**Comment by rstanonik** [comment]
qa file sync is 56% done and staging is 10%.

**Comment by rstanonik** [comment]
qa is done.  prod file, solr, and tripstore have been sync'ed to qa.

file sync from prod to staging is 83% done.

**Comment by lsitu** [comment]
Thanks @rstanonik and @jgorney. I'll start to work on those UCSD IP/metadata-only collection on QA first.

**Comment by rstanonik** [comment]
staging is done.  prod file, solr, and triplestore have been sync'ed to staging.

**Comment by lsitu** [comment]
Thanks @rstanonik for the update. I am updating the UCSD IP/metadata-only collections on staging now.

**Comment by gamontoya** [comment]
Kamino cloned this issue to [ucsdlib/damspas](https://github.com/ucsdlib/damspas/issues/542)
