### ISSUE TITLE
Change objects to be metadata-only view for Lambert collection

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#468]
### Descriptive summary

- Change 34 objects that are currently _culturally sensitive_ or _embargoed_ to be metadata-only. The list of 34 ARKs is attached.

- Fix curator view: If I logged in as a curator, I should be able to see the objects and download the master files. Currently one is not able to.

### ARKs

[lambert.txt](https://github.com/ucsdlib/damspas/files/2120760/lambert.txt)

**Comment by hweng** [comment]
@gamontoya Could you clarify what you would like me to change? The RDF data or the metadata viewer, or both?

The 34 objects has ```<dams:type>metadataDisplay</dams:type>```, Would you like to change data?

```<dams:otherRights>
<dams:permission>
<dams:Permission>
<dams:type>metadataDisplay</dams:type>
</dams:Permission>
</dams:permission>
</dams:otherRights>
```

**Comment by gamontoya** [comment]
Yes, change the data please.

**Comment by hweng** [comment]
@gamontoya Would you like to remove metadata-only in rdf record, correct?

**Comment by gamontoya** [comment]
@hweng No, I don't think so. You might want to wait until Vivian is back to help you with this, but these 34 objects need to be metadata-only and not embargoed as they are now.

How they are now:
![embargoed](https://user-images.githubusercontent.com/4314914/42350096-e3587c7e-8063-11e8-8e25-0bc0b630668d.png)
 
Versus how they should be:
![restricted](https://user-images.githubusercontent.com/4314914/42350109-f4c6943c-8063-11e8-878c-84fb8dab9beb.png)

**Comment by hweng** [comment]
@gamontoya I see what you mean. I will look into it and do some tests. And if it doesn't work I will talk to Longshou or wait for Vivian's back. Thanks!

**Comment by hweng** [comment]
@gamontoya Could you please send me the ARK of the Metadata only view test(frogitha)? 
 I would like to check how it's RDF rights related data structured and what's the difference between them.

**Comment by gamontoya** [comment]
@hweng Sounds like a good idea! Thank you.

**Comment by hweng** [comment]
@gamontoya What's the url to the "Metadata only view test(frogitha)" which you posted the screenshot?

**Comment by gamontoya** [comment]
@hweng It's on staging: https://librarytest.ucsd.edu/dc/object/bd0224952x

**Comment by gamontoya** [comment]
https://librarytest.ucsd.edu/dc/object/bd56858502

**Comment by hweng** [comment]
Thanks @gamontoya, it is helpful!

**Comment by hweng** [comment]
@gamontoya Among the 34 objects, the following list is Culturally sensitive content, not embargoed. Do you want to remove Culturally sensitive so that it will be shown as metadata only?
bb60078423
bb1093127s
bb7373045d
bb0581173b
bb64174045
bb98304029
bb86358554
bb5325245m
bb65197941
bb5495891n
bb3448091s

**Comment by gamontoya** [comment]
@hweng Yes. Metadata only.

**Comment by hweng** [comment]
@gamontoya I updated the Lambert objects RDF data(for example: bb3789396p) to be metadata only on staging:
https://librarytest.ucsd.edu/dc/collection/bb3789396p/data
https://librarytest.ucsd.edu/dc/collection/bb3789396p

But the viewer behavior doesn't look right to me comparing to the test object(bd56858502) you sent above. I will look into it.

**Comment by hweng** [comment]
@gamontoya I see that Vivian has been working on "Fix display behavior of metadata-only collections" https://github.com/ucsdlib/damspas/issues/466.  I think it's better to wait for her updates to be deployed on staging, then I will check if the updated metadataView only Lambert objects look right on staging and start from there. Does it sound good to you?

**Comment by hweng** [comment]
And BTW, the curator view looks right to me after I updated objects that one is able to see the objects and download the master files: https://librarytest.ucsd.edu/dc/collection/bb3789396p,
But the public view doesn't look right to me.

**Comment by gamontoya** [comment]
@hweng I agree. Let's wait until Longshou and Vivian have these behaviors fixed and working.

**Comment by hweng** [comment]
@gamontoya I updated the 34 objects to make them to be able to view or download from curator viewer.  I only updated objects on staging environment, and I will wait until those metadata only viewer behaviors get fixed then make the data changes to production.

Here are some examples, could you take a look in curator viewer if it looks right to you:
https://librarytest.ucsd.edu/dc/collection/bb3789396p
https://librarytest.ucsd.edu/dc/object/bb60078423

**Comment by gamontoya** [comment]
@hweng Looks great. That is the expected curator behavior.

**Comment by hweng** [comment]
@gamontoya The same update for 34 lambert objects was done on production.

**Comment by gamontoya** [comment]
@hweng Great, looks good!

**Comment by hweng** [comment]
@gamontoya The following 14 objects has been updated on staging environment, and the solr index was done. Could you take a look and let me know if it looks good to you:

bb3448091s
bb3789396p
bb7373045d
bb86358554
bb0000967b
bb0581173b
bb1093127s
bb5325245m
bb5495891n
bb9250195j
bb98304029
bb60078423
bb64174045
bb65197941
Including three are restricted + culturally sensitive:
bb3789396p (also restricted + culturally sensitive)
bb0000967b (also restricted + culturally sensitive)
bb9250195j (also restricted + culturally sensitive)

**Comment by gamontoya** [comment]
@hweng Did you do this on prod or staging?

**Comment by gamontoya** [comment]
@hweng I guess it doesn't matter because it's not working on prod or staging. For the first 11, I should see the click-thru agreement and I'm not seeing it.

**Comment by gamontoya** [comment]
@hweng Never mind. I see you said "staging".  While the first 11 work right (with the click-thru), I should see a "grey" generic banner and not the thumbnail.

I'll now check the last three.

**Comment by gamontoya** [comment]
The last three should be restricted by an embargo. I should not see them at all or find them in a search. They need to remain curator only (curator can see, download, etc.)

**Comment by hweng** [comment]
@gamontoya Do you mean the first 11 is correct? And for the last three restricted + culturally sensitive, what exactly the behavior do you expect? Do you have any example record and please send me the link?

**Comment by gamontoya** [comment]
@hweng No, I don't, but let me create a new one using a working image. I'll let you know when it's up.

**Comment by hweng** [comment]
@gamontoya The following three objects have been updated on production. Could you please review and let me know if it looks right to you?

https://library.ucsd.edu/dc/object/bb3789396p
https://library.ucsd.edu/dc/object/bb0000967b
https://library.ucsd.edu/dc/object/bb9250195j
