### ISSUE TITLE
Fix curator view access for Keesing and Lambert collections

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#469]
### Descriptive summary

Currently, one cannot view objects or download master files if logged in as **curator** for 883 embargoed/restricted [Keesing Photograph objects](https://library.ucsd.edu/dc/collection/bb1571361n) and 23 [Lambert objects](https://library.ucsd.edu/dc/collection/bb1912661h) 

Please update the behavior.

List of ARKs is attached below.

### ARKS

- [keesing.txt](https://github.com/ucsdlib/damspas/files/2120769/keesing.txt)
- [lambert.txt](https://github.com/ucsdlib/damspas/files/2160739/lambert.txt)

**Comment by hweng** [comment]
@gamontoya Are 883 embargoed/restricted Keesing Photograph objects and 23 Lambert objects metadata-only objects? And if so, do you mean to change the metadata-only viewer behavior? Thanks!

**Comment by gamontoya** [comment]
Some will eventually be metadata-only, but for now the collection owners needs to review the images to see which ones should be made metadata-only, but when she logs in as curator she cannot see the image display. Even when I log in, I cannot see the images.

**Comment by gamontoya** [comment]
![curator](https://user-images.githubusercontent.com/4314914/42345937-ce1158d0-8055-11e8-891b-f08ba186bb8d.png)

This is what I see when logged in as curator.

**Comment by gamontoya** [comment]
@hweng I think that for this ticket you can just focus on getting the objects to show up for curators.

The metadata only part can be done after Longshou and Vivian fix visibilities.

**Comment by hweng** [comment]
@gamontoya The 883 embargoed/restricted Keesing Photograph objects and 23 Lambert objects have been updated on production. Could you take a look and let me know if it looks fine to you now?

**Comment by gamontoya** [comment]
@hweng Thank you. They are behaving as expected in curator mode.

**Comment by hweng** [comment]
@gamontoya The 883 embargoed/restricted Keesing Photograph objects and 23 Lambert objects have been updated on Staging. Could you take a look and let me know if it looks fine to you?

**Comment by gamontoya** [comment]
Once the metadata only code is pushed to prod I'm going to ask you to fix these on prod.

**Comment by gamontoya** [comment]
Closing this ticket as the initial requested task to make these images available to logged in curators is complete.
