### ISSUE TITLE
Add Embed Video UI

### ISSUE THREAD

**Issue by dt-ucsd** [ucsdlib/damspas#470]
### Descriptive summary

Add "Embed" information (I.e., URL, Code snippet) to object views that display video.

**Original request:**

> "David, can you please look into adding an Embed link to our content in the DAMS4 UI? Specifically video. If you need more details, please let me know." -Tim M.

### Rationale

Once upon a time there lived a prince in a far off land who wished to display a Digital Collections video on his website, to his dismay there existed not a solution that allowed him to do so.

In his despair he called out to the heavens, "Oh sweetest stars above, low am I, take pity and find one who would add the 'embed' information I desire to the website—in an easy to use UI—so that I may share in this vast trove of knowledge."

As if by magic, his words sailed across the land and into the ears of those known only as the Creators.

"And it shall be done," echoed throughout the halls as the new day's light broke.

### Mockups

![ss-click](https://user-images.githubusercontent.com/2448340/41759654-625f7998-75a4-11e8-914b-b2e283069fe9.png)

![ss-modal](https://user-images.githubusercontent.com/2448340/41759671-76ef7822-75a4-11e8-9c41-7c1263954a74.png)

**Comment by gamontoya** [comment]
@dt-ucsd Very nice mockups. Looking forward to seeing this in action!

**Comment by gamontoya** [comment]
@dt-ucsd Oh, and what are our terms of service? Should that be a link to something?

**Comment by gamontoya** [comment]
@dt-ucsd Hi David, what are the next steps for this ticket?

**Comment by gamontoya** [comment]
@dt-ucsd Hi David, what are the next steps for this ticket?

**Comment by gamontoya** [comment]
Kamino cloned this issue to [ucsdlib/damspas](https://github.com/ucsdlib/damspas/issues/551)
