### ISSUE TITLE
Valid zips larger than 4GB do not pass File Validation check

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damspas#476]
### Descriptive summary

When attempting to use the 'File Validation' check for ingesting zip files larger than 4GB, the file will be reported as being unable to be read. 

![large_zip_test_form_result](https://user-images.githubusercontent.com/5183580/42396814-2b81dc3e-8118-11e8-98ba-32ba83cebd26.jpg)

### Rationale

We are getting "false positive" invalid reports for large zips, which makes the File Validation check unreliable for large zips, and we now have evidence we ingested a series of corrupt large zips accidentally. 

### Expected behavior
A valid zip archive > 4GB will be able to be read by, and will pass File Validation checks

### Actual behavior
Valid zip archives larger than 4GB will not pass File Validation checks, reporting `Warning: Format error reading ZIP file`

### Steps to reproduce the behavior

1. Log into DAMS Manager on staging and create a dummy collection
1. On the 'Excel Import' screen, fill out the collection options for your dummy collection, and select the radial button for 'File Validation'
1. Point the File Validation tool at a staging location with a known valid zip over 4GB (I made mine at `//rdcp-staging/zz_Test/large_zip_test/files/`)
1. Click on "Submit" 
1. Observe the DAMS error message when the test completes

**Comment by gamontoya** [comment]
@jessicahilt Does Longshou have the bandwidth to look into this?

**Comment by lsitu** [comment]
@gamontoya @jessicahilt Sure. I'll look into it.

**Comment by lsitu** [comment]
@remerjohnson I think there is an issue with the ExifTool to support the structure of this kind of ZIP files. I tried it with the latest ExifTool version 11.10 and I still got the same warning. However, I tested it by ZIPing two giant .iso files that are more than 5GB and it works.
I also tried to test ExifTool with GZIP format validation, and I don't see any warnings. 
And I tried other tools like FITS, which use ExifTool to extract some technical metadata as well and I don't see any warning or error message. But I am not sure whether it'll do the same validation process and provide the correct message for file validation like what ExifTool does. It seem like FITS uses JHOVE to validate files and I see the empty <filestatus /> element in the file validation status section for the ZIP file.

Moving forward, we may have the following options:
1. Contact the develops to report the issue. In this case we may need to wait until the next release if they will fix it.
2. Use GZIP format instead ZIP for giant files compression.
3. Try to use other tools like FITS to see whether we can get the correct validation message that  we expected.

What do you think it will work better for you?

**Comment by remerjohnson** [comment]
@lsitu Thanks for that research Longshou. I had a feeling this is a larger/community issue, not just unique to the DAMS. 

As a workaround, I do often use GZIP for large zips. The only problem is sometimes we get large ZIPs "as-is" and I do not wish to alter/handle those. We could start doing that if this is deemed important enough. 

I think I'll need some input before selecting the best approach, though. Thoughts? @mcritchlow @gamontoya

**Comment by mcritchlow** [comment]
I think contacting the developers would be good to do regardless. If nothing else, it would likely give us some kind of indication of their willingness/interest in solving this problem upstream. Which would be the best possible situation.

I'd be a little nervous about adding FITS into the mix now for dams4, despite the fact that we're definitely going to be using it when we move to our new system. It would just introduce a series of potential regressions we'd need to be very careful with. Unless of course we could treat some objects like this in a one-off capacity and bypass the normal JHOVE portion of the ingest workflow. Longshou would know better how realistic that is.

As for using gzip, I agree that seems like an ideal solution except for the "as-is" situation. That makes it tricky :(

**Comment by gamontoya** [comment]
Hi all. I think it's a good idea to report to the developers, but that's not going to solve this issue at this time or any time soon. With that said, I'd suggest using the workaround (GZIP) alternative.

So do #1 and #2. I agree with Matt that #3 is not an option for DAMS 4.0.

**Comment by remerjohnson** [comment]
Thanks all, I think we've come to agreement. Not sure if you want to close this out for not, but feel free. Thanks

**Comment by lsitu** [comment]
@gamontoya @mcritchlow @remerjohnson I've posted a message in the ExifTool forum:
http://u88.n24.queensu.ca/exiftool/forum/index.php/topic,9450.0.html.
