### ISSUE TITLE
Automatically update collection record extent when objects are added via DAMS Manager

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damspas#493]
### Descriptive summary

Currently, when objects are added to or removed from an collection that has already been released, the collection extent is not updated causing a discrepancy.

### Expected behavior
When objects are added to a collection via DAMS Manager Excel ingest, the CLR extent value should be updated and SOLR should be re-indexed to display the new value

### Related work
Collection record extent does not match number of published objects #492

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/damsmanager/pull/237 for it, which is ready for review now. Thanks.
