### ISSUE TITLE
Re-insert `cultural sensitivity` note to 886 Keesing objects

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#515]
### Descriptive summary

Re-add `culturally sensitive` restricted note for 886 restricted Keesing objects once Vivian's code has been pushed to production.

[keesing.txt](https://github.com/ucsdlib/damspas/files/2367624/keesing.txt)

Previously deleted by Huawei when fixing the image view for curator (not working) issue.

---
### Note
`<dams:Note>
<rdf:value>Image not available due to cultural sensitivities 
of the community depicted.</rdf:value>
<dams:type>note</dams:type>
</dams:Note>
</dams:note>`

---
### Related work

Link to related tickets or prior related work here.
#469 
#513
#514 

---
### ARKs
[keesing.txt](https://github.com/ucsdlib/damspas/files/2271212/keesing.txt)

**Comment by gamontoya** [comment]
Do not assign until Vivian's code is pushed to production.

**Comment by gamontoya** [comment]
@lsitu Hi Longshou. Can you take this ticket on first thing this morning and re-index? After this is done I'm going to ask you to do #356 .

**Comment by lsitu** [comment]
@gamontoya Sure. I am on it now.

**Comment by lsitu** [comment]
@gamontoya It looks like there are total 886 objects in keesing.txt, which has three more objects. Do you want to add the note above to all 886 objects in keesing.txt?

**Comment by gamontoya** [comment]
@lsitu So those extra three are both restricted and culturally sensitive.

**Comment by lsitu** [comment]
@gamontoya Okay. I'll just add the note above to all 886 objects listed in the keesing.txt then.

**Comment by gamontoya** [comment]
bb3789396p (also restricted)
bb0000967b (also restricted)
bb9250195j (also restricted)

**Comment by gamontoya** [comment]
```
    <dams:license>
      <dams:License>
        <dams:restriction>
          <dams:Restriction>
            <dams:endDate>2059-01-01</dams:endDate>
            <dams:beginDate>2009-01-01</dams:beginDate>
            <dams:type>display</dams:type>
          </dams:Restriction>
        </dams:restriction>
        <dams:permission>
          <dams:Permission>
            <dams:type>display</dams:type>
          </dams:Permission>
        </dams:permission>
        <dams:licenseNote>Display currently prohibited.</dams:licenseNote>
      </dams:License>
    </dams:license
```

**Comment by gamontoya** [comment]
@lsitu Wait, those 3 ARKs above are for Lambert, so never mind.

**Comment by gamontoya** [comment]
@lsitu Looks great. Thank you.
