### ISSUE TITLE
Show generic thumbnail in grid for click-thru agreement objects

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#516]
### Descriptive summary

Currently, when using click-thru cultural sensitivity override, the grid view displays the thumbnail of the image. 

Please correct it to use the grey generic thumbnail.

### Example of current display

![test](https://user-images.githubusercontent.com/4314914/44279214-68b48f80-a205-11e8-83ca-cae3649ecf1e.png)

### Expected behavior
Show the generic thumbnail that is being used in the last example of the above image.

###

See: https://librarytest.ucsd.edu/dc/object/bd0089518z

**Comment by gamontoya** [comment]
@VivianChu Can you start work on this? I'd like to get testing of object visibility options soon.

**Comment by VivianChu** [comment]
@gamontoya - The update has been deployed to staging.  Could you review it? For example - 

https://librarytest.ucsd.edu/dc/search?utf8=%E2%9C%93&q=bd0089518z

Here's what I see as local user
![objclickthru](https://user-images.githubusercontent.com/1864660/44371855-dd056200-a495-11e8-93ef-c021f8369414.png)
