### ISSUE TITLE
Deletion request

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#518]
### Descriptive summary

Image belongs to SD Historical Society and should not be reprinted or digitized without consent. Please delete: 

- https://library.ucsd.edu/dc/object/bb30388568

**Comment by gamontoya** [comment]
@lsitu Can you delete at your earliest convenience?

**Comment by lsitu** [comment]
@gamontoya Sure.

**Comment by gamontoya** [comment]
@lsitu Thank you!
