### ISSUE TITLE
Remove metadataDisplay from public objects (Keesing)

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#528]
### Descriptive summary

Remove OtherRights=metadataDisplay element from the 2982 **public** Keesing objects.

### Rationale

Currently the Keesing collection is showing everything with a "restricted" label after the metadataDisplay update was added to production. These public objects need to be updated in order to behave as non-restricted, public display.

**Comment by lsitu** [comment]
@gamontoya I think the OtherRights=metadataDisplay element is moved from all 2982 public objects in Keesing on prod already. Please let me know if you still see any issues with these objects. Thanks.

**Comment by gamontoya** [comment]
@lsitu Good work again!
