### ISSUE TITLE
Ping Collection: Update Rights Holder

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#529]
### Descriptive summary

Lynda notes that the Ping collection incorrectly lists the UC Regents as the rights holder. Peter confirms that Ping owns the rights. Signed agreement is attached.

- [Reynolds Ping License.pdf](https://github.com/ucsdlib/dams-metadata/files/2380324/Reynolds.Ping.License.pdf)

------

### Task

For all objects in collection: https://library.ucsd.edu/dc/collection/bb64179408

- update _dams:rightsHolderCorporate_ UC Regents **> to** _dams:rightsHolderName_ Reynolds, Roger, 1934-

**Comment by GregReser** [comment]
@gamontoya I think we need to also add a license so these display to the public

<dams:license>
    <dams:License>
        <dams:licenseNote>Public access granted by rights holder.</dams:licenseNote>
        <dams:permission>
            <dams:Permission>
                <dams:type>display</dams:type>
            </dams:Permission>
        </dams:permission>
    </dams:License>
</dams:license>

**Comment by VivianChu** [comment]
@GregReser - I'll add that license predicate to those objects.  Thanks

**Comment by VivianChu** [comment]
@gamontoya - The rightsHolder has been updated and the license predicate has been added for all objects.  They have been re-indexed.  Could you review them?  For example - https://library.ucsd.edu/dc/object/bb0991291g  Thanks

**Comment by GregReser** [comment]
@gamontoya  I think the rightsHolder name should be "Reynolds, Roger, 1934-"

**Comment by gamontoya** [comment]
@GregReser Yes, my bad with the name, but should Vivian link use:

<mads:PersonalName rdf:about="http://library.ucsd.edu/ark:/20775/bb1093608k">

**Comment by GregReser** [comment]
@gamontoya I should have noticed the name and mentioned it earlier.
Yes, we want the same ARK used for creator and rights holder, so you are correct, it would be  http://library.ucsd.edu/ark:/20775/bb1093608k

**Comment by VivianChu** [comment]
@gamontoya @GregReser - The existing object doesn't use any link for the rightsHolder.  It just uses internal predicate    
 <dams:rightsHolderCorporate>
      <mads:CorporateName>
        <mads:authoritativeLabel>UC Regents</mads:authoritativeLabel>
        <mads:elementList rdf:parseType="Collection">
          <mads:FullNameElement>
            <mads:elementValue>UC Regents</mads:elementValue>
          </mads:FullNameElement>
        </mads:elementList>
      </mads:CorporateName>
    </dams:rightsHolderCorporate>

I just updated the rightsHolderCorporate internal predicate to rightsHolderName
    <dams:rightsHolderName>
      <mads:Name>
        <mads:authoritativeLabel>Roger Ping</mads:authoritativeLabel>
        <mads:elementList rdf:parseType="Collection">
          <mads:FullNameElement>
            <mads:elementValue>Roger Ping</mads:elementValue>
          </mads:FullNameElement>
        </mads:elementList>
      </mads:Name>
    </dams:rightsHolderName>

I'll try to update the records again using that ark.

**Comment by GregReser** [comment]
@VivianChu Ping was an older ingest.  Current practice is to use ARks for copyrightHolder

**Comment by gamontoya** [comment]
@GregReser Thanks for clarifying!

**Comment by lsitu** [comment]
@GregReser I think in damsmanager we are still using the internal name instance convention for for copyrightHolder and we've never changed it. Do you want to change it in damsmanager to perform name authority lookup and map it to existing ARKs instead?

**Comment by gamontoya** [comment]
@lsitu @GregReser We probably should, no?

**Comment by lsitu** [comment]
@gamontoya / @GregReser Yep, I think it sounds good. But this will create additional new name authority records if no mapping is found. Can you create a damsmanager ticket for it? Thanks.

**Comment by gamontoya** [comment]
@lsitu I'll create it once @GregReser talks to Arwen about this -- Greg, do you need to consult with your team?

**Comment by VivianChu** [comment]
@gamontoya @GregReser - The objects have been updated with the ARKs for rightsHolder.    Solr reindex process is not done yet.  I'll let you know when it's done.  Here's one of the updated record  https://library.ucsd.edu/dc/object/bb84998938

**Comment by gamontoya** [comment]
@VivianChu Thank you for adjusting so quickly.

**Comment by GregReser** [comment]
@lsitu @gamontoya Oh, I guess I have it backwards.  I looked at some existing objects and saw ARKs, but those must have been added later.  I can see in our most recent tests that there are no ARK.

I think we should move to using ARKs for DAMS Manager ingests. @arwenhutt @remerjohnson what do you think?

**Comment by VivianChu** [comment]
@gamontoya @GregReser - All objects have been re-indexed.  Could you review them?  Thanks

**Comment by GregReser** [comment]
@gamontoya @VivianChu The objects look good to me.

**Comment by GregReser** [comment]
@gamontoya @lsitu DOMM still needs to talk before we update DAMS Manager to use ARKs for rightsHolder.  We will let you know.
