### ISSUE TITLE
Check for recent bot crawls

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#530]
### Descriptive summary

I notice that we are getting high number of hits in our statistics this month. Check the robots file for new bot crawling

- https://library.ucsd.edu/damsmanager/stats.do

### Rationale

Need accurate stats.

**Comment by lsitu** [comment]
@rstanonik It seems like there is a stale Tomcat thread running at the same time for dams statistics. I see the Sep 13 peak and the Sep. 15 peak were double counted. This will happened when Tomcat wasn't restarted cleanly after deploying damsmanager. Could you take a look and restart tomcat on lib-ingest? Thanks.

**Comment by lsitu** [comment]
Thanks @rstanonik . I'll regenerate the stats started from last Monday when we deployed damsmanager.

**Comment by lsitu** [comment]
@gamontoya I've regenerated the stats data starting from Monday Sep 10. So the peaks on Sep 13 and Sep 15 are gone.

It seems like it's a little bit complicated for the other peaks on Aug 26 (44158 hits) and Sep 6 (40751 hits). I found we could exclude user agent `weborama-fetcher (+http://www.weborama.com)` from counting but the majority accesses is from user agent `Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Mobile Safari/537.36`, which is mainly access from China. See https://myip.ms/view/comp_browseragents/2230362/Mozilla_5_0_Linux_Android_6_0_Nexus_5_Build_MRA58N_AppleWebKit_537_36_KHTML_like_Gecko_Chrome_65_0_3325_181_Mobile_Safari_537_36.html.

Here is the counts I got:
```
Date	Hits	User Agent 
08/26	15	weborama-fetcher (+http://www.weborama.com)
08/26	43567	Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Mobile Safari/537.36

09/06	12	weborama-fetcher (+http://www.weborama.com)
09/06	36265	Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Mobile Safari/537.36

09/09	12	weborama-fetcher (+http://www.weborama.com)
09/09	4783	Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Mobile Safari/537.36

09/10	17	weborama-fetcher (+http://www.weborama.com)
09/10	17042	Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Mobile Safari/537.36

09/13	33	weborama-fetcher (+http://www.weborama.com)
09/13	14196	Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Mobile Safari/537.36

09/15	9	weborama-fetcher (+http://www.weborama.com)
09/15	25113	Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Mobile Safari/537.36
```

From the [IP database](https://myip.ms/view/comp_browseragents/2230362/Mozilla_5_0_Linux_Android_6_0_Nexus_5_Build_MRA58N_AppleWebKit_537_36_KHTML_like_Gecko_Chrome_65_0_3325_181_Mobile_Safari_537_36.html) above, the following two IPs are recognized to be crawlers /Bots:
52.83.219.14
52.83.191.29

Here is the stats with IP accesses that are over 100 each day:
```
Date	Hits	IP
08/26	127	220.243.136.146
08/26	122	220.243.136.85
08/26	121	220.243.135.40
08/26	121	220.243.136.169
08/26	118	220.243.135.148
08/26	117	220.243.135.20
08/26	117	220.243.135.21
08/26	117	220.243.135.73
08/26	117	220.243.136.83
08/26	116	220.243.135.13
08/26	116	220.243.135.161
08/26	115	220.243.135.135
08/26	115	220.243.136.43
08/26	114	220.243.135.52
08/26	114	220.243.136.10
08/26	114	220.243.136.117
08/26	113	220.243.135.224
08/26	112	220.243.135.235
08/26	111	220.243.135.147
08/26	111	220.243.135.42
08/26	111	220.243.136.14
08/26	111	220.243.136.143
08/26	111	220.243.136.206
08/26	111	220.243.136.229
08/26	111	220.243.136.232
08/26	110	220.243.135.103
08/26	110	220.243.136.211
08/26	109	220.243.135.77
08/26	109	220.243.136.103
08/26	109	220.243.136.37
08/26	108	220.243.135.178
08/26	108	220.243.135.32
08/26	108	220.243.135.38
08/26	108	220.243.135.81
08/26	108	220.243.136.111
08/26	108	220.243.136.35
08/26	108	220.243.136.60
08/26	108	220.243.136.88
08/26	107	220.243.136.106
08/26	107	220.243.136.84
08/26	106	220.243.135.108
08/26	106	220.243.135.111
08/26	106	220.243.135.151
08/26	106	220.243.135.214
08/26	106	220.243.135.231
08/26	106	220.243.135.84
08/26	106	220.243.136.182
08/26	106	220.243.136.66
08/26	106	220.243.136.81
08/26	105	220.243.135.139
08/26	105	220.243.135.186
08/26	105	220.243.135.98
08/26	105	220.243.136.136
08/26	105	220.243.136.166
08/26	105	220.243.136.186
08/26	105	220.243.136.205
08/26	104	220.243.135.117
08/26	104	220.243.135.192
08/26	104	220.243.135.198
08/26	104	220.243.135.211
08/26	104	220.243.136.176
08/26	103	220.243.136.147
08/26	103	220.243.136.162
08/26	103	220.243.136.203
08/26	102	220.243.135.181
08/26	102	220.243.135.226
08/26	102	220.243.135.37
08/26	102	220.243.136.115
08/26	102	220.243.136.207
08/26	102	220.243.136.45
08/26	102	220.243.136.71
08/26	101	220.243.135.113
08/26	101	220.243.135.206
08/26	101	220.243.135.207
08/26	101	220.243.135.36
08/26	101	220.243.135.56
08/26	101	220.243.135.95
08/26	101	220.243.136.144
08/26	101	220.243.136.221
08/26	101	220.243.136.231
08/26	101	220.243.136.33
08/26	100	220.243.135.169
08/26	100	220.243.135.203
08/26	100	220.243.135.43
08/26	100	220.243.136.123
08/26	100	220.243.136.148
08/26	100	220.243.136.163
08/26	100	220.243.136.38

09/06	653	144.123.46.66
09/06	453	104.225.178.57
09/06	451	104.225.177.27
09/06	444	208.185.3.25
09/06	437	208.185.3.57
09/06	297	52.83.191.29
09/06	287	52.83.254.182
09/06	275	64.150.183.176
09/06	273	52.83.219.14
09/06	271	68.168.100.144
09/06	212	64.150.181.58
09/06	187	132.239.89.179
09/06	183	52.83.110.47
09/06	132	220.243.135.143
09/06	118	220.243.135.23
09/06	112	220.243.136.149
09/06	112	220.243.136.17
09/06	110	220.243.135.250
09/06	110	220.243.136.141
09/06	109	220.243.135.17
09/06	108	220.243.135.186
09/06	108	220.243.136.133
09/06	108	220.243.136.80
09/06	106	220.243.135.206
09/06	106	220.243.135.65
09/06	106	220.243.136.158
09/06	106	220.243.136.2
09/06	105	220.243.135.141
09/06	105	220.243.136.166
09/06	104	220.243.136.137
09/06	104	220.243.136.206
09/06	103	220.243.135.149
09/06	102	220.243.136.143
09/06	101	220.243.135.86
09/06	100	220.243.135.116
09/06	100	220.243.135.80
09/06	100	220.243.136.103
09/06	100	220.243.136.212

09/10	155	52.83.191.29
09/10	142	52.83.254.182
09/10	115	52.83.219.14
09/10	112	52.83.110.47

09/13	692	27.223.18.226
09/13	135	72.197.9.27
09/13	133	52.83.219.14
09/13	124	52.83.191.29
09/13	121	132.239.89.214
09/13	118	52.83.254.182

09/15	210	52.83.254.182
09/15	200	52.83.219.14
09/15	190	52.83.191.29
09/15	107	220.243.135.153
```
It seems like most of  the IPs above are TelComm, Cloud service providers. And the access URLs are strange with redirection and escaped several times during redirecting. For example, an access from Microsoft in China will be something like:
`Aug 26 00:09:26 library apache[8405]: library.ucsd.edu 139.219.0.98 - - [26/Aug/2018:00:09:26 -0700] "GET /dc/search?%20%20%20%20%2520%2520%2520%2520%25252520%25252520%25252520%25252520f%2525255bsubject_cruise_sim%2525255d%2525255b%2525255d=ebs-1-76--ebs-1-76&%20%20%20%20%2520%2520%2520%2520f%255Bsubject_lithology_sim%255D%255B%255D=calcareous%252C%252Bnannofossils&%20%20%20%20%252520%252520%252520%252520f%25252525255bsubject_topic_sim%25252525255d%25252525255b%25252525255d=portraits--solomon%252525252bislands&%20%20%20%20f%5Bdecade_sim%5D%5B%5D=1750s&%2520%2520%2520%2520%252520%252520%252520%252520f%25255bsubject_scientific_name_sim%25255d%25255b%25255d=halobates%25252bsericeus HTTP/1.1" 302 1016 "-" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Mobile Safari/537.36"`

I think we can exclude those IPs that are recognized to be crawlers ( for example 52.83.219.14 and 52.83.191.29), and those reported to be abused like 64.150.183.176 (https://www.abuseipdb.com/check/64.150.183.176).
We also could just exclude user agent `Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Mobile Safari/537.36` from counting in dams statistics if we want.

What do you think? @mcritchlow Do you have any thoughts on it while moving froward?

**Comment by gamontoya** [comment]
Can we block 220.243.135.* and 220.243.136.*, exclude weborama-fetcher (+http://www.weborama.com) for starters?

Let's see if @mcritchlow has ideas about the rest.

**Comment by mcritchlow** [comment]
Yeah this is a frustratingly difficult game, because the goal posts are constantly moving. I'm going to think about this a little bit, I wonder if we just need a fundamentally different approach. Blocking those IPs seems fine as a short term measure. But I think we need to find something 

As for the user agent, I don't think we can/should block via the user agent. Primarily because it's the easiest thing to spoof. A bot (or browser, wget/curl, etc.) can trivially manipulate the user agent string to be whatever it wants to, which would be perceived as a very legitimate agent. So I think that's actually the least reliable thing we can use, unfortunately.

**Comment by gamontoya** [comment]
@mcritchlow Please let @lsitu know how he should proceed with this ticket.

**Comment by lsitu** [comment]
@mcritchlow I think I can add another IP filter to handle those range of IPs that we don't want to include in dams statistics, like `220.243.135.*` and `220.243.136.*`. And I can add a query IP filter in SQL to exclude those single IPs that we don't want to include in the search result. 
So we can have three filters to exclude those bots/crawls accesses from counting in dams statistics:
1. The user agent filter as what we have now.
2. The IP/IP range filter to exclude those accesses that we don't want to include from collecting. I think this could avoid the slow performance with SQL searching to filter out the accesses from a big batch of IPs.
3. The IP filter to filter those single IPs that we don't want to include in the search results. 

I think we can make those two IP filters to be configurable. Does it sound good to move forward with this approach?

**Comment by mcritchlow** [comment]
@lsitu - Sorry for the delay. I think short of something more drastic, which we probably don't have time for right now, that seems like a very good approach. :+1: on my end

**Comment by lsitu** [comment]
Thanks you very much for you inputs @mcritchlow. I'll move forward with it then.

**Comment by gamontoya** [comment]
@lsitu Does this work go into a release?

**Comment by lsitu** [comment]
@gamontoya Yes. We'll release it once the PR above is reviewed and merged when Matt is back next Monday.

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/damsmanager/pull/270 to support filtering bots/crawlers accesses by IP. As we discussed above, this will be done during collecting the statistic data phase, and while querying the statistic data. It's ready for review now. Thanks.

**Comment by gamontoya** [comment]
@lsitu That's what I wondered. So we will need a release ticket for DAMSPAS?

**Comment by lsitu** [comment]
@gamontoya No, we don't need to release DAMSPAS. It's a PR in damsmanger so we just need to add it to damsmanager [Release 2.67](https://github.com/ucsdlib/damsmanager/issues/269) for review.
