### ISSUE TITLE
Object Deletion: East Asia Film Collection

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damspas#531]
#### Reason:
Duplicate object.

#### Collection
none - object is one-off, not linked to a CLR

#### Object affected
https://library.ucsd.edu/dc/object/bb4918700z

#### Current Visibility
Public

**Comment by gamontoya** [comment]
@VivianChu Are you able to do a complete deletion?

**Comment by VivianChu** [comment]
@gamontoya - Yes I'm able to do a complete deletion.

**Comment by VivianChu** [comment]
@gamontoya - The object has been removed.

**Comment by gamontoya** [comment]
@VivianChu Thank you!
