### ISSUE TITLE
Upgrade to JWPlayer 8

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/damspas#534]
### Descriptive summary

Upgrade to JWPlayer 8. Some of the changes include:

- JWPlayer is loaded from the cloud
- The playlist is an icon in the bottom right

Example - https://library.ucsd.edu/jwplayer-cloud/

**Comment by VivianChu** [comment]
@gamontoya - The jwplayer8 update has been deployed to qa.  Could you review it?  Thanks.  For example 
simple video
http://libraryqa.ucsd.edu/dc/object/bb8022051s

complex video
http://libraryqa.ucsd.edu/dc/object/bb3756085z

simple audio
http://libraryqa.ucsd.edu/dc/object/bb2220581g

complex audio
http://libraryqa.ucsd.edu/dc/object/bb08885004

**Comment by gamontoya** [comment]
@VivianChu Looks good. Plays right away too.
