### ISSUE TITLE
Edit visibility values in Roger M. Keesing Photographs

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damspas#536]
### Description

Edit visibility values for 886 objects from Roger M. Keesing Photographs (https://library.ucsd.edu/dc/collection/bb1571361n)

Object ARKs and new values located in the attached spreadsheet Keesing_restriction_edits.xlsx

For each ARK in the spreadsheet:

**1**
IF dams:otherRightsNote exists
REPLACE existing dams:otherRightsNote value with new value in spreadsheet column "otherRightsNote:New"

REPORT that otherRightsNote note was edited

IF dams:otherRights is does not exist
ADD dams:otherRights
dams:otherRights\otherRightsNote = [value in spreadsheet column "otherRightsNote:New"]
dams:otherRights\dams:otherRightsBasis = "cultural sensitivity"
dams:otherRights\dams:Permission\dams:type = "metadataDisplay"
dams:otherRights\dams:Restriction\dams:type = "display"

REPORT that otherRights was added

---
**2**
IF dams:note value = "Image not available due to cultural sensitivities of the community depicted."
REPLACE existing value with new value in spreadsheet column "Note:note:New"

REPORT that note was edited

IF this note does not exist, ADD dams:note
dams:note\dams:type = "note"
dams:note\rdf:value = [value in spreadsheet column "Note:note:New"]

REPORT that note was added

**Comment by hweng** [comment]
@GregReser For dams:otherRights editing, should the 886 objects change to be like https://library.ucsd.edu/dc/object/bb4881568h,  which include the dams:otherRightsBasis, dams:permission and dams:Restriction in <dams:otherRights>

For example of bb1502706w:

```
<dams:otherRights>
      <dams:OtherRights>
        <dams:otherRightsNote>Restricted by Donor. This image contains frontal nudity and depicts a ritual that should not be made available publically prior to the year 2059.</dams:otherRightsNote>
        <dams:otherRightsBasis>cultural sensitivity</dams:otherRightsBasis>
        <dams:permission>
          <dams:Permission>
            <dams:type>metadataDisplay</dams:type>
          </dams:Permission>
        </dams:permission>
        <dams:restriction>
          <dams:Restriction>
            <dams:type>display</dams:type>
          </dams:Restriction>
        </dams:restriction>
      </dams:OtherRights>
    </dams:otherRights>
```

For example of bb67245902:
```
<dams:otherRights>
      <dams:OtherRights>
        <dams:otherRightsNote>Restricted by Donor. This image contains nudity. 
      </dams:otherRightsNote>
        <dams:otherRightsBasis>cultural sensitivity</dams:otherRightsBasis>
        <dams:permission>
          <dams:Permission>
            <dams:type>metadataDisplay</dams:type>
          </dams:Permission>
        </dams:permission>
        <dams:restriction>
          <dams:Restriction>
            <dams:type>display</dams:type>
          </dams:Restriction>
        </dams:restriction>
      </dams:OtherRights>
    </dams:otherRights>
```

For example of bb3379925q
```
<dams:otherRights>
      <dams:OtherRights>
        <dams:otherRightsNote>Restricted by Donor. This image depicts a ritual that should not be made available publically prior to the year 2059.
      </dams:otherRightsNote>
        <dams:otherRightsBasis>cultural sensitivity</dams:otherRightsBasis>
        <dams:permission>
          <dams:Permission>
            <dams:type>metadataDisplay</dams:type>
          </dams:Permission>
        </dams:permission>
        <dams:restriction>
          <dams:Restriction>
            <dams:type>display</dams:type>
          </dams:Restriction>
        </dams:restriction>
      </dams:OtherRights>
    </dams:otherRights>
```

**Comment by hweng** [comment]
@GregReser Let me know if you'd like the 886 objects to behave like bb4881568h: https://library.ucsd.edu/dc/object/bb4881568h

I checked bb4881568h that the dams:otherRights structure is:
```
<rdf:Description rdf:about="http://library.ucsd.edu/ark:/20775/bb4881568h">
    <dams:otherRights>
      <dams:OtherRights>
        <dams:otherRightsNote>Restricted by Donor. This image depicts a ritual that should not be made available publicly prior to the year 2059.</dams:otherRightsNote>
        <dams:otherRightsBasis>cultural sensitivity</dams:otherRightsBasis>
        <dams:permission>
          <dams:Permission>
            <dams:type>metadataDisplay</dams:type>
          </dams:Permission>
        </dams:permission>
        <dams:restriction>
          <dams:Restriction>
            <dams:type>display</dams:type>
          </dams:Restriction>
        </dams:restriction>
      </dams:OtherRights>
    </dams:otherRights>
  </rdf:Description>
```

**Comment by GregReser** [comment]
@hweng Yes, https://library.ucsd.edu/dc/object/bb4881568h behaves correctly. The others you posted above also look correct.

**Comment by hweng** [comment]
@GregReser In keesing_restriction_edits.xlsx, the first item https://library.ucsd.edu/dc/object/bb9045418k, otherRightsNote:New is "Nudity"?  Could you check it?

**Comment by GregReser** [comment]
@hweng that's the value I was given, go ahead and use it.  It's an internal note (curator only).

**Comment by hweng** [comment]
@GregReser Thanks for clarifying it. For dams:Note edit, if the following rdf looks correct to you:

```
<dams:Note>
        <rdf:value>Image not available due to cultural sensitivities. Access may be granted for research purposes at the discretion of the UC San Diego Library. For more information, please contact spcoll@ucsd.edu.</rdf:value>
        <dams:type>note</dams:type>
</dams:Note>
```

**Comment by GregReser** [comment]
@hweng Yes, that dams:Note looks correct.  I see in the spreadsheet that some have two spaces after "UC San Diego Library." and some have one space, otherwise the values are the same.  Let's use one space as you have it above for all dams:Note (column C)

**Comment by GregReser** [comment]
@hweng well done!  I need to look at more and have the Cristela confirm before I close this.

**Comment by hweng** [comment]
@GregReser Solr indexing was done for the keesing collection on production, and I've been updating the collection on test server.  I checked some that they look right to me. Let me know if you and Cristela catch something. Thank you!

**Comment by GregReser** [comment]
@hweng It looks like some objects did not get the correct note.  For example, https://library.ucsd.edu/dc/object/bb5427656k

The note value should be "Restricted by Donor. This image contains nudity."

This note should be used for the 538 objects listed in the attached spreadsheet, 
[Keesing_restriction_2.xlsx](https://github.com/ucsdlib/damspas/files/2447764/Keesing_restriction_2.xlsx)

**Comment by hweng** [comment]
@GregReser I'll fix them. Thank you for catching it.

**Comment by hweng** [comment]
@GregReser I updated RDF for 538 objects to be
`<dams:otherRightsNote> Restricted by Donor. This image contains nudity. </dams:otherRightsNote>`
http://lib-hydratail-prod.ucsd.edu:8080/dams/api/objects/bb5427656k/export

And the solr indexing was done, for example:  http://lib-hydratail-prod.ucsd.edu:8983/solr/blacklight/select?q=id:bb5427656k

**Comment by GregReser** [comment]
@hweng Looks good. Thank you
