### ISSUE TITLE
Edit notes and CLR link for SIO Photos

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damspas#537]
### Description

For 422 objects currently linked to [Scripps Institution of Oceanography Photographs](https://library.ucsd.edu/dc/collection/bb20151229), edit location of originals and preferred citation notes and change link to new collection [SIO Photographs Collection](https://library.ucsd.edu/dc/collection/bb2734402f)

List of ARKs in attached spreadsheet SMC59_batch_updates.xlsx

### Edits
For each ARK:
#### 1
REPLACE existing Note:location of originals with new value:
"This digital image is a surrogate of an item in the SIO Photographs Collection (SMC 59)."

#### 2
ADD Note:preferred citation with value:
"[Title, Date]. SIO Photographs Collection. SMC 59. Special Collections &amp; Archives, UC San Diego."

#### 3
REPLACE existing provenanceCollection with new value:
"http://library.ucsd.edu/ark:/20775/bb2734402f"

**Comment by VivianChu** [comment]
@GregReser - There are only 417 objects because 5 arks are duplicated in the list. 
bb27996565
bb5086365p
bb7065903w
bb2492484r
bb4267247b
417 objects have been updated and re-indexed.  Could you review them?  Thanks For example https://library.ucsd.edu/dc/object/bb27996565

**Comment by GregReser** [comment]
@VivianChu Looks good.  Thank you very much.
