### ISSUE TITLE
Re-ingest Wu Films objects

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damspas#539]
### Descriptive summary

Re-ingest 2 objects that filed during DAMS Manager ingest - re-use ARKS created during original ingest.

Spreadsheet attached with existing ARKs and metadata.
Source files are located at  digital-staging:\CARS Digital Acquisitions\Video\Licensed_Media\Wu Films February 2017\Final_Files

**Comment by lsitu** [comment]
@GregReser I don't see the spreadsheet attached with existing ARKs and metadata is missing. Could you attach it again? Thanks.

**Comment by GregReser** [comment]
@lsitu oops.
[Wu_films_re-ingest.xlsx](https://github.com/ucsdlib/damspas/files/2443960/Wu_films_re-ingest.xlsx)

Also, there are no changes to the metadata, I think the only problem is that the files were not created and linked.  I tried to use the DAMS Manager file replace tool, but I got an error that no there is no original file in the DAMS to replace.

**Comment by lsitu** [comment]
Thanks @GregReser. I'll fix it.

**Comment by lsitu** [comment]
@GregReser The mp4 files in objects https://library.ucsd.edu/dc/object/bb5669559q and https://library.ucsd.edu/dc/object/bb7273696p are re-ingested. The videos are ready for review now.

**Comment by GregReser** [comment]
@lsitu Perfect, thanks!
