### ISSUE TITLE
Deletion request

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damspas#540]
### Description
Please delete the following objects from the DAMS:
bb9318660w
bb39943803
bb06153324
bb19152583

#### Reason:
SC&A request

**Comment by VivianChu** [comment]
@gamontoya @GregReser - The objects have been deleted.   
For example 
https://library.ucsd.edu/dc/object/bb9318660w
https://library.ucsd.edu/dc/object/bb39943803
https://library.ucsd.edu/dc/object/bb06153324
https://library.ucsd.edu/dc/object/bb19152583

**Comment by gamontoya** [comment]
@VivianChu Thank you!
