### ISSUE TITLE
Data Sync to Staging/QA

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#542]
### Descriptive summary

- Please sync from prod to staging and QA. This should include everything (triplestore, solr, files, etc.)

### Notes

- To be started on Monday, October 8 during regular service window
- Operations: @jgorney @rstanonik

**Comment by rstanonik** [comment]
solr is sync'ed from prod to qa and staging.

file sync has started.  I give an estimate of the time after it has run for a while.

**Comment by jgorney** [comment]
I didn't see this until this morning, I got a late start, but the database triplestore syncs to qa and staging are underway.

**Comment by rstanonik** [comment]
file sync is about 40% done to both qa and staging, in about 3 hours, so estimate another 5 hours.

**Comment by rstanonik** [comment]
62% done to staging, estimate another 4 hours.

I paused the sync to qa, to see if that significantly speeds up the sync to staging.  It doesn't seem to affect the sync to staging, so I'll resume the sync to qa.

**Comment by rstanonik** [comment]
The filesync to staging finished.

The filesync to qa is 72% done, so estimate another 3 hours.

**Comment by rstanonik** [comment]
qa and staging have been synced to prod (triplestore, file, and solr) and are ready for use.

**Comment by gamontoya** [comment]
Thank you @rstanonik

**Comment by gamontoya** [comment]
Kamino cloned this issue to [ucsdlib/damspas](https://github.com/ucsdlib/damspas/issues/679)

**Comment by gamontoya** [comment]
Kamino cloned this issue to [ucsdlib/damspas](https://github.com/ucsdlib/damspas/issues/709)
