### ISSUE TITLE
Deletion request: Scheffler

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damspas#544]
### Descriptive summary

Delete 1 object from [Harold Scheffler Photographs](https://library.ucsd.edu/dc/collection/bb08204951) at the request of the curator, Cristela Garcia Spitz.

https://library.ucsd.edu/dc/object/bb58030759

**Comment by VivianChu** [comment]
@GregReser @gamontoya - The object has been deleted.

**Comment by gamontoya** [comment]
@VivianChu Thanks for this too.
