### ISSUE TITLE
Download collection PDFs and place on darry

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#545]
### Descriptive summary

For project related work, I need all 233 PDF files downloaded from the _Armed Revolutionary Organizations in Mexico_ collection in the DAMS.

https://library.ucsd.edu/dc/collection/bb9387084g

Please place them in a folder on \darry.ucsd.edu\

**Comment by lsitu** [comment]
@gamontoya All 233 PDFs in Armed Revolutionary Organizations in Mexico collection are in darry \\darry.ucsd.edu\dams_staging\AROM\PDF now.

**Comment by gamontoya** [comment]
@lsitu Thank you!
