### ISSUE TITLE
Create zoom tiles for San Diego History object

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#547]
### Descriptive summary

- Zoom tiles were created for the recto of object [bb3792566m](https://library.ucsd.edu/dc/object/bb3792566m/zoom/1) but not for the verso. 
- Please create them for /zoom/1

**Comment by gamontoya** [comment]
@VivianChu Do you want to take this on?

**Comment by gamontoya** [comment]
@mdpeters FYI.

**Comment by mdpeters** [comment]
@gamontoya that was not the only object that had zoomify issues in that ingest, some components of 
bb7888170w failed to have tiles created, (/zoom/7, /zoom/10, /zoom/14)
and
bb02430489, bb66594863, bb5533200b, bb0993908q failed for /zoom/0



--



--



--

**Comment by lsitu** [comment]
@gamontoya Maybe we can fix it now. But we need @rstanonik to run the script on prod.

**Comment by lsitu** [comment]
@rstanonik Could you run the following command on lib-ingest to create the zoomify tiles? Thanks.
```
/home/tomcat/zoomify/zoomify.sh bb7888170w/7/1.tif https://lib-hydratail-prod.ucsd.edu:8443/dams/api /pub/data1/damsmanager/localStore
/home/tomcat/zoomify/zoomify.sh bb7888170w/10/1.tif https://lib-hydratail-prod.ucsd.edu:8443/dams/api /pub/data1/damsmanager/localStore
/home/tomcat/zoomify/zoomify.sh bb7888170w/14/1.tif https://lib-hydratail-prod.ucsd.edu:8443/dams/api /pub/data1/damsmanager/localStore
/home/tomcat/zoomify/zoomify.sh bb02430489/1.tif https://lib-hydratail-prod.ucsd.edu:8443/dams/api /pub/data1/damsmanager/localStore
/home/tomcat/zoomify/zoomify.sh bb66594863/1.tif https://lib-hydratail-prod.ucsd.edu:8443/dams/api /pub/data1/damsmanager/localStore
/home/tomcat/zoomify/zoomify.sh bb5533200b/1.tif https://lib-hydratail-prod.ucsd.edu:8443/dams/api /pub/data1/damsmanager/localStore
/home/tomcat/zoomify/zoomify.sh bb0993908q/1.tif https://lib-hydratail-prod.ucsd.edu:8443/dams/api /pub/data1/damsmanager/localStore
```

**Comment by rstanonik** [comment]
I'm running them now, in sequence

**Comment by gamontoya** [comment]
@lsitu @rstanonik Thank you guys.

**Comment by rstanonik** [comment]
[z.txt](https://github.com/ucsdlib/damspas/files/2493637/z.txt)
Here is the output from the commands.
Looks okay

**Comment by mdpeters** [comment]
@lsitu confirmed, tiles are all fixed.
