### ISSUE TITLE
Edit subject in Milo Woodbridge CLR

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damspas#548]
### Descriptive summary

Need to edit a corporateName in the Milo Woodbridge CLR without re-indexing all objects in linked collections (California Explores the Ocean and Scripps Institution of Oceanography Photographs )

### Edit request
In CLR https://library.ucsd.edu/dc/collection/bb6248543w
corporateName/CorporateName
Current value: http://library.ucsd.edu/ark:/20775/bb49516046 "Scripps Aquarium-Museum"
New value: http://library.ucsd.edu/ark:/20775/bb85708557 "T. Wayland Vaughan Aquarium-Museum"

**Comment by gamontoya** [comment]
@hweng Is there a way you can edit without triggering a re-index of the California Explores the Ocean and Scripps Institution of Oceanography Photographs collections?

**Comment by hweng** [comment]
@gamontoya  I think we can just index one or a few ARK by using: https://library.ucsd.edu/damsmanager/solrDump.do

**Comment by gamontoya** [comment]
@hweng As long as it doesn't trigger a full index of those two large collections.

**Comment by hweng** [comment]
@gamontoya It has been updated: https://library.ucsd.edu/dc/collection/bb6248543w
Would you take a look and let me know if it looks fine to you? Thanks.

**Comment by GregReser** [comment]
@hweng @gamontoya The CLR looks good to me.  As far as I can tell, it didn't trigger a re-index of all the objects. Good to know we can do this for future CLR edits.  Thanks.

**Comment by hweng** [comment]
@GregReser Right! Thank you for checking it.
