### ISSUE TITLE
Delete objects from AV Diss

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damspas#549]
### Description

Delete objects that were not structured correctly due to a mistake in the ingest spreadsheet.
Objects have not been published yet.

https://library.ucsd.edu/dc/object/bb7410493d
https://library.ucsd.edu/dc/object/bb7547014n
https://library.ucsd.edu/dc/object/bb8024863q
https://library.ucsd.edu/dc/object/bb40316558
https://library.ucsd.edu/dc/object/bb3690355j
https://library.ucsd.edu/dc/object/bb33490550
https://library.ucsd.edu/dc/object/bb3007755r
https://library.ucsd.edu/dc/object/bb6591405k

JIRA DI: https://lib-jira.ucsd.edu:8443/browse/DI-41

**Comment by VivianChu** [comment]
@GregReser @gamontoya - The objects have been deleted.

**Comment by GregReser** [comment]
@VivianChu Thank you
