### ISSUE TITLE
Update Embed URL to include audio and images

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#551]
### Descriptive summary

- Add Embed information (I.e., URL, Code snippet) to audio and image objects as well.
- Should read: 
   - Embed URL
   - Embed Audio | Image | Video (whichever one)
- Remove "Terms of Service" text

### David Commentary

We could probably get a little fancy with that second one and have it read embed video|audio|image depending on the object type.

###

**Comment by gamontoya** [comment]
@dt-ucsd We started a Sprint yesterday. Do you have time to work on this during this 2-week Sprint?

**Comment by gamontoya** [comment]
@jessicahilt Does Vivian have time to look into this ticket instead of David?

**Comment by VivianChu** [comment]
@gamontoya - The embed url feature for audio and image has been deployed to staging.  Could you review it?
For example - 
//single image
http://librarytest.ucsd.edu/dc/object/bb80217186
//single video
http://librarytest.ucsd.edu/dc/object/bb8022051s
//single audio
http://librarytest.ucsd.edu/dc/object/bb33481593
//complex audio
http://librarytest.ucsd.edu/dc/object/bb5463710v
http://librarytest.ucsd.edu/dc/object/bb4369691m
//complex video
http://librarytest.ucsd.edu/dc/object/bb76807535

Thanks

**Comment by gamontoya** [comment]
@VivianChu Great start! The embed code for all formats is cut off. I expect to see something more like:

```
<iframe src="https://library.ucsd.edu/dc/embed/bb8022051s/0" 
width="560" height="315" frameborder="0"></iframe>
```

**Comment by gamontoya** [comment]
@VivianChu Also, can you remove this in the embed dialog box:

_By embedding Digital Collections videos on your site, you are agreeing to our Terms of Service._

**Comment by gamontoya** [comment]
@VivianChu Also, for images, is it possible to use the image-service version (2.jpg) instead of https://librarytest.ucsd.edu/dc/embed/bb80217186/0

I'm guessing you might say no?

**Comment by VivianChu** [comment]
@gamontoya - The embed code is not cut off.  If you click on it and copy or move your cursor you will see like this <iframe src="https://librarytest.ucsd.edu/dc/embed/bb8022051s/0" width="560" height="315" frameborder="0"></iframe>
Or would you like me to change it to use text area instead of one line input text?
The text "By embedding Digital Collections videos on your site, you are agreeing to our Terms of Service." has been removed.  I don't see it in the embed dialog box.  
Here's the screen shot on staging
![embedimage](https://user-images.githubusercontent.com/1864660/50237150-031e0e80-0371-11e9-9576-afe0c1fc5def.png)
Let me check to see if I can get the image service version.  I'll let you know.  
Thanks

**Comment by VivianChu** [comment]
@gamontoya - The image embed url has been updated to use service file. Could you review it?
https://librarytest.ucsd.edu/dc/embed/bb80217186/0
Thanks

**Comment by gamontoya** [comment]
@VivianChu  image-service looks fine. 

Yes, please use the text area instead of the one line. Otherwise it behaves oddly in Chrome.

**Comment by VivianChu** [comment]
@gamontoya - The code has been updated to use textarea and deployed to staging.  Could you review it?  Thanks

**Comment by gamontoya** [comment]
@VivianChu Looks good, but we have one needed change. For audio, can you set it to:

```width="629" height="46" frameborder="0"```

**Comment by VivianChu** [comment]
@gamontoya - The width & height have been updated for audio and deployed to staging.   Could you review it? Thanks

**Comment by VivianChu** [comment]
@gamontoya - I saw the audio behaves like video problem before when I tried to upgrade to new jwplayer.  We contacted jwplayer support about it.  They suggested us to create some extra javascript function to resize the player to make it looks like audio.  Let me see if I can fix this using those functions.  I'll keep you posted.  Thanks

**Comment by VivianChu** [comment]
@gamontoya - The audio issue has been fixed and deployed to staging.  Here's the screen shot.  Could you review it?  Thanks
![embedurl](https://user-images.githubusercontent.com/1864660/50364759-45d51780-0526-11e9-87e9-7c1611a7cba6.png)

**Comment by gamontoya** [comment]
Hi @VivianChu -- Happy 2019. This look good.
