### ISSUE TITLE
Remove rightsHolder for all AV Dissertations objects

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damspas#557]
### Description

Because the files associated with AV dissertations can contain works copyrighted by multiple people besides the dissertant, there should be no Rights Holder associated with the object.  The objects will still be under copyright.

DAMS Manager requires a Rights Holder for copyrighted objects, so "Unknown" was used as a placeholder which now must be removed.

### Request
Remove the entire rightsHolderPersonal property from all 628 objects in UCSD Electronic Theses and Dissertations (https://library.ucsd.edu/dc/collection/bb9253289t)

JIRA: https://lib-jira.ucsd.edu:8443/browse/DI-41

**Comment by gamontoya** [comment]
@VivianChu Do you have time to work on this ticket? If not, I will gladly assign to someone else.

**Comment by VivianChu** [comment]
@gamontoya - I have time to work on this ticket.

**Comment by VivianChu** [comment]
@GregReser @gamontoya - rightsHolderPersonal has been removed from all 628 objects in UCSD Electronic Theses and Dissertations.

**Comment by GregReser** [comment]
@VivianChu Perfect. Thank you.
