### ISSUE TITLE
Update DAMS to no longer use SecureToken

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#558]
### Descriptive summary

SecureToken removed from DMR which was causing problems. Since then we have had virtually no reports of videos not playing.

To try to stay consistent with apps, remove SecureToken from DAMS PAS.

Not sure why we were using it to begin with.

**Comment by VivianChu** [comment]
@gamontoya - Remove token has been removed and deployed to qa.  Could you review them?  
For example
//single video
http://libraryqa.ucsd.edu/dc/object/bb8022051s
//single audio
http://libraryqa.ucsd.edu/dc/object/bb33481593
//complex audio
http://libraryqa.ucsd.edu/dc/object/bb5463710v
http://libraryqa.ucsd.edu/dc/object/bb4369691m
//complex video
http://libraryqa.ucsd.edu/dc/object/bb76807535

Thanks
