### ISSUE TITLE
Update FFmpeg video-derivative encoding (in test, qa, prod)

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#559]
### Descriptive summary

Update FFmpeg video-derivative encoding to use -ac 2 for mp4 derivatives. In the future, multichannel is going to be a thing, and if/when players can eventually support multichannel in the future, we can always recreate derivatives.

### Audio option

-ac 2: Specifies the number of audio channels. Stereo audio is recommended for best compatibility. Wowza Streaming Engine doesn't support more than two audio channels.

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/private_config/pull/7 with the`-ac 2` option for ffmpeg multichannel video derivative creation. Thanks.

**Comment by lsitu** [comment]
@gamontoya I've deployed the`-ac 2` option for FFmpeg video-derivative encoding to QA and staging. I think we can test it with damsmanager on QA (https://libraryqa.ucsd.edu/damsmanager) now. Thanks.
