### ISSUE TITLE
Add VRR active directory group

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damspas#561]
### Descriptive summary
We need to create an active directory group to be used for authorization of folks allowed to manage the Aeon queues for VRR.

### Rationale

The current 'curator' group is too broad and would allow too many folks access to manage this work. 

### Related work
#560

**Comment by allisonflick** [comment]
New AD group has been created called "dams-vrr" with Matt Peters and Heather Smedburg as members.
