### ISSUE TITLE
Correct Unit value for Makua Beach collection

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#562]
From damsmanager created by [hjsyoo](https://github.com/hjsyoo) : ucsdlib/damsmanager#287  

### Descriptive summary

Change value of Unit/Repository for the collection page, https://library.ucsd.edu/dc/collection/bb48163351, to RDCP (or other standard value). The object page has already been assigned the correct Unit.

### Rationale

This collection page was incorrectly assigned DLP during ingest.

### Related work

https://lib-jira.ucsd.edu:8443/browse/CPP-136

**Comment by gamontoya** [comment]
Cloned ticket to DAMSPAS repo (not DAMS Manager)

**Comment by hweng** [comment]
@gamontoya The Makua Beach collection was updated to fix the unit.

**Comment by gamontoya** [comment]
@hjsyoo For your review.

**Comment by hjsyoo** [comment]
@remerjohnson Can you review the Unit correction in https://library.ucsd.edu/dc/collection/bb48163351?

**Comment by remerjohnson** [comment]
@hjsyoo Yes, this looks good. It now shows up correctly when browsing RDCP collections, and the RDF has the correct RDCP ARK. 👍

**Comment by hjsyoo** [comment]
Great, thanks everyone!
