### ISSUE TITLE
Add Preferred Citations to SIO Cruise Report objects

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#567]
### Descriptive summary

For all objects in this collection:

Collection URL: https://library.ucsd.edu/dc/collection/bb29737300
Temp collection title: SIO Explorer Cruises
Permanent collection title: Data from Scripps Research Expeditions 1953-2005

1. Add text to Preferred Citation/Cite This Work, following the format:

Geological Data Center at Scripps Institution of Oceanography (2018). [ObjectTitle]. In Data from Scripps Research Expeditions 1953-2005. UC San Diego Library Digital Collections. [DOI URL]

See Related ticket for source of DOIs.

2. Add text to Date Issued: 2018

### Related work

https://github.com/ucsdlib/damspas/issues/568 - Batch mint DOIs for all objects in SIO Cruise Reports

**Comment by gamontoya** [comment]
@jessicahilt Please assign to a developer.

**Comment by VivianChu** [comment]
@gamontoya @hjsyoo @arwenhutt - Date issued and preferred citation note has been added for 708 objects in this collection. For example - https://github.com/ucsdlib/damspas/issues/567

**Comment by hjsyoo** [comment]
@VivianChu Thank you! I spot-checked a bunch of objects and they look great.
