### ISSUE TITLE
Batch mint DOIs for all objects in SIO Cruise Reports

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#568]
### Descriptive summary

A collection of 708 objects has been ingested. All objects need DOIs, with all of the metadata pushed to EZID that typically gets pushed when the Mint DOI button is clicked manually.

Collection URL: https://library.ucsd.edu/dc/collection/bb29737300
Temp collection title: SIO Explorer Cruises
Permanent collection title: Data from Scripps Research Expeditions 1953-2005

When the DOIs have been created, please generate a report of the DOIs, target URLs, and object titles.

** NOTE: The Geological Data Center is required to provide these DOIs and target URLs to NOAA (funder) by the end of the year or by mid-January (in which case an ETA would be requested). **

### Related work

https://github.com/ucsdlib/damspas/issues/567 - Add Preferred Citations to SIO Cruise Report objects

**Comment by gamontoya** [comment]
@jessicahilt Ready for dev assignment.

**Comment by jessicahilt** [comment]
Vivian, can you take a look at this and see if it's possible to get this done by winter break. Let me know. Thanks!

**Comment by VivianChu** [comment]
@jessicahilt -  I'll start working on it.  I think it's possible to get this done by winter break.

**Comment by VivianChu** [comment]
@gamontoya - We can mint doi if a record has Preferred Citation Note and Date Issued.  The records in this collection don't have those fields.  For example - https://library.ucsd.edu/dc/collection/bb04139816/rdf https://library.ucsd.edu/dc/collection/bb87075706/rdf
This record from different collection has Preferred Citation Note, Date Issued and DOI - http://lib-hydratail-prod.ucsd.edu:8080/dams/api/objects/bb4438832x
Would you like me to insert a temporary Preferred Citation Note and Date Issued?
Thanks

**Comment by hjsyoo** [comment]
@VivianChu Sorry about this - I somehow managed to forget to include those two fields in the ingest metadata. So I created this related ticket: https://github.com/ucsdlib/damspas/issues/567. It looks like 567 should be tackled first?

**Comment by VivianChu** [comment]
@gamontoya @hjsyoo @arwenhutt - The DOIs  have been minted all objects in SIO Cruise Reports.  For the report, what would be the value for target URLs?  For example  - https://library.ucsd.edu/dc/object/bb60795846  Thanks

**Comment by hjsyoo** [comment]
@VivianChu Yes! That's exactly the target URL we would need.

**Comment by VivianChu** [comment]
@hjsyoo - Here's the report.  Could you review it?
[sio_cruise_explorer_doi_report.txt](https://github.com/ucsdlib/damspas/files/2700263/sio_cruise_explorer_doi_report.txt)
Thanks

**Comment by hjsyoo** [comment]
@VivianChu The report is perfect! Thanks very much, Vivian, for such a quick turnaround. I really appreciate it.

**Comment by hjsyoo** [comment]
@VivianChu Sorry - it looks like a correction is needed in the EZID records for all 708 objects. When the DOIs were minted, we had a stub record for the collection page with the temporary title, "SIO Explorer Cruises". The minting process must have grabbed the collection title component from the stub record (rather than from the citation). The correct collection title is "Data from Scripps Research Expeditions 1953-2005".
So, for example, the record in https://ezid.cdlib.org/id/doi:10.6075/J0C53J5K should have Title, "LUSI05HO Lusiad Leg 5 - Cruise Report. In Data from Scripps Research Expeditions 1953-2005".
The title is correct in Cite This Work for the corresponding object: https://library.ucsd.edu/dc/object/bb60795846.

**Comment by VivianChu** [comment]
@hjsyoo - The minting process always use the collection title from the collection record.  It doesn't use the citation note value.  I can either edit the title for those 708 objects using the ezid dashboard or create a new update DOI function, add that link to our dams UI (like Mint DOI link) and we can click on that link to do the update.  Which way do you prefer?  Do we need to update EZID record frequently? If there's any update to our Dams record that has DOI minting, then the data will be out of sync with EZID record.  Thanks

**Comment by hjsyoo** [comment]
@VivianChu An update DOI button in the DAMS would be very useful! We do indeed need to update the EZID records fairly often, and this would save us a lot of time.
Once the button has been deployed, we can handle the title updates from our end. Thank you!

**Comment by VivianChu** [comment]
@hjsyoo - The Update DOI record function has been deployed to production.  I tried to use it to update this record and the title looks correct now.  https://ezid.cdlib.org/id/doi:10.6075/J0C53J5K

**Comment by hjsyoo** [comment]
@VivianChu I tested it on an object just now and it looks great! Thanks so much for your speedy work on this!

**Comment by VivianChu** [comment]
@hjsyoo - The Mint DOI link will be displayed if the record doesn't have doi minted.  If the record has DOI identifier, then only "Update DOI Record" link will be displayed.
