### ISSUE TITLE
Batch update file use values in SIO Explorer Cruises collection

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#569]
### Descriptive summary
For the items in the SIO Explorer Cruises collection https://library.ucsd.edu/dc/collection/bb29737300

please replace the value:
        <dams:use>document-source</dams:use>
with:
        <dams:use>document-service</dams:use>

and reindex

### Rationale
the document-source value does not trigger the pdf viewer

### Related work
https://github.com/ucsdlib/damspas/issues/568
https://github.com/ucsdlib/damspas/issues/567

**Comment by gamontoya** [comment]
@hweng Do you have time to work on this?

**Comment by arwenhutt** [comment]
@lsitu Great!  Thank you!
