### ISSUE TITLE
Batch update rights (override) for AROM collection

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#570]
### Descriptive summary

[The Armed Revolutionary Organizations of Mexico](https://library.ucsd.edu/dc/collection/bb9387084g) was publicly released, but the objects are not displaying because copyright is `unknown`. Please add access override to release.

**Comment by lsitu** [comment]
@gamontoya All 233 object in [AROM collection](https://library.ucsd.edu/dc/collection/bb9387084g) should be public accessible now. Could you take a look?

**Comment by gamontoya** [comment]
@lsitu Confirming that work is complete. Thank you.
