### ISSUE TITLE
Publish new CCAS Joseph objects

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#578]
### Descriptive summary

We need to make ~36 objects that have been added to the [CCAS Joseph collection](https://library.ucsd.edu/dc/collection/bb5259361d) publicly accessible (they are now curator-only). The exact ARK list is attached.

[damslog--1020446901-arkReport.xlsx](https://github.com/ucsdlib/damsmanager/files/2738865/damslog--1020446901-arkReport.xlsx)

Attempts to re-release the collection (via the Release tool) have not worked. 

### Related work

#200

**Comment by lsitu** [comment]
@gamontoya Those 36 objects listed in [damslog--1020446901-arkReport.xlsx](https://github.com/ucsdlib/damsmanager/files/2738865/damslog--1020446901-arkReport.xlsx) above are available for public access now. For example https://library.ucsd.edu/dc/object/bb1710975w, https://library.ucsd.edu/dc/object/bb1028374z, https://library.ucsd.edu/dc/object/bb03799049 etc.

And I found that only the following 3 objects in the collection are limited to curator access at this time:
https://library.ucsd.edu/dc/object/bb1233155m
https://library.ucsd.edu/dc/object/bb79908992
https://library.ucsd.edu/dc/object/bb92195742

Could you take a look? Thanks.

**Comment by remerjohnson** [comment]
@lsitu Thanks Longshou. Those 3 objects are to remain curator-only due to sensitivity. Thanks again!
