### ISSUE TITLE
Delete Ellen B. Scripps objects from SIO Photographs 

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damspas#582]
### Description

Delete 5 DAMS objects because SC&A does not own the physical objects (requested by Laurel McPhee).
The objects show Ellen B. Scripps and are in the Scripps Institution of Oceanography Photographs Collection

bb6144395f
bb0000997s
bb3823557r
bb5120498q
bb64174375

**Comment by gamontoya** [comment]
@lsitu Can you take this ticket too?

**Comment by lsitu** [comment]
Sure.

**Comment by lsitu** [comment]
@GregReser Are there any ARKs missing from the description text above? I only see 5 objects listed for deletion but in the description text it mentions 9. Thanks.

**Comment by GregReser** [comment]
@lsitu that was a typo on my part.  There are only 5 objects

**Comment by lsitu** [comment]
@gamontoya / @GregReser All those 5 objects listed above are gone now:
https://library.ucsd.edu/dc/object/bb6144395f
https://library.ucsd.edu/dc/object/bb0000997s
https://library.ucsd.edu/dc/object/bb3823557r
https://library.ucsd.edu/dc/object/bb5120498q
https://library.ucsd.edu/dc/object/bb64174375

**Comment by GregReser** [comment]
Thanks @lsitu
