### ISSUE TITLE
Publish all IDEAS objects

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damspas#583]
### Descriptive summary

All of the ~40 objects in the [IDEAS Performance Series](https://library.ucsd.edu/dc/collection/bb4029917n) collection should be published. Note: these items were publicly accessible, and last week I went through and removed "UC Regents" as rights holders for all objects. This could be why all objects reverted to curator-only? 

### Related work

#578

**Comment by gamontoya** [comment]
@remerjohnson Not sure, but I'll assign to @lsitu and he'll let us know why.

**Comment by lsitu** [comment]
@gamontoya / @remerjohnson I think the problem here is that objects [IDEAS Performance Series](https://library.ucsd.edu/dc/collection/bb4029917n) collection have copyright status `Under copyright` and the rightsHolder is missing. And I don't see any licenses or OtherRights override it for public access. For example https://library.ucsd.edu/dc/object/bb44394840.
By default it will be public with `UC Regents` as rights holder. I think that why those objects were public before you removed `UC Regents` as rights holders.
What license or OtherRights would you like to add to override those objects in  [IDEAS Performance Series](https://library.ucsd.edu/dc/collection/bb4029917n) collection for public access?

**Comment by remerjohnson** [comment]
@lsitu Ah, I thought that might be the case. Let me get back to you on that, and I'll let you know. Thanks, Longshou!

**Comment by lsitu** [comment]
@remerjohnson What would you like me to do to publish the IDEAS objects, add license or OtherRights? Thanks.

**Comment by remerjohnson** [comment]
@lsitu Hi Longshou, unfortunately the rights issue has been complicated. I am currently ascertaining the correct rights holders from the collection stakehoders, which will take weeks. Then it would be ready to publish/override. Feel free to take this ticket out of sprint until that's ready.

**Comment by remerjohnson** [comment]
@gamontoya @lsitu Hi Longshou, I think this may be ready to look at again. Peter determined the rights holders for all objects, and I'm attaching a spreadsheet that records those for each object, delimited in the case of multiples by a `|`. 

All objects should be public given these right holders, but let me know if you need more information. Thanks!
 
[IDEAS_rights_additions_cleaned.xlsx](https://github.com/ucsdlib/damspas/files/2937239/IDEAS_rights_additions_cleaned.xlsx)

**Comment by lsitu** [comment]
@remerjohnson Should we add a license `Public - granted by rights holder` or add OtherRights `fair use (public)` `display` to override it for public access?

**Comment by remerjohnson** [comment]
@lsitu I consulted with the project stakeholders, and they agreed that `Public - granted by rights holder` is the appropriate license. Thanks!

**Comment by lsitu** [comment]
@remerjohnson I found two RightsHolders (Cai, Liz and
Thomas, Richard) existing in object https://library.ucsd.edu/dc/object/bb44394840, which is different from the rights holder (Muehlhausen, Andy) provided in the spreadsheet [IDEAS_rights_additions_cleaned.xlsx](https://github.com/ucsdlib/damspas/files/2937239/IDEAS_rights_additions_cleaned.xlsx). Should we remove rights holder Cai, Liz and
Thomas, Richard from object https://library.ucsd.edu/dc/object/bb44394840?

**Comment by remerjohnson** [comment]
@lsitu Correct... Andrew would replace/remove Cai and Liz

**Comment by gamontoya** [comment]
@lsitu Okay, this can be worked on.

**Comment by lsitu** [comment]
@gamontoya / @remerjohnson I've added the license and rights holders listed in spreadsheet [IDEAS_rights_additions_cleaned.xlsx](https://github.com/ucsdlib/damspas/files/2937239/IDEAS_rights_additions_cleaned.xlsx) to the objects in the IDEAS collection. It's ready on prod for review now, https://library.ucsd.edu/dc/collection/bb4029917n. Thanks.

**Comment by remerjohnson** [comment]
@lsitu Thanks, Longshou! I reviewed the objects, and made a few tweaks. But this all looks great. Thanks again!
