### ISSUE TITLE
Edit SIO Photographs CLR witout re-indexing all linked objects

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damspas#584]
### Descriptive summary
For CLR https://library.ucsd.edu/dc/collection/bb2734402f/ (SIO Photographs Collection)

Add corporate subject <dams:corporateName rdf:resource="http://library.ucsd.edu/ark:/20775/bb46431339"/> (University of California (1868-1952). Division of War Research)

without re-indexing all linked objects in SIO Photographs Collection or its parent collections

**Comment by gamontoya** [comment]
@VivianChu Thank you.

**Comment by VivianChu** [comment]
@gamontoya @GregReser - The corporate subject has been added and only the collection has been re-indexed.  https://library.ucsd.edu/dc/collection/bb2734402f/

**Comment by GregReser** [comment]
@VivianChu thanks
