### ISSUE TITLE
Delete 57 curator-only objects in James Stewart Papers collection

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#585]
### Descriptive summary

Request to delete 57 curator-only objects in the [James Stewart Papers](https://library.ucsd.edu/dc/collection/bb40639296) collection approved by Roger Smith.

### Rationale
Laurel McPhee:

_The James Stewart Papers collection has 57 items that were suppressed to curator-only because at the time we did not have permission to delete. Can you create a ticket to move forward with deleting those objects? They were re-appraised when the paper portion of the collection was processed. Anything that is public should remain._

**Comment by lsitu** [comment]
@gamontoya I found the following 57 curator objects in [James Stewart Papers](https://library.ucsd.edu/dc/collection/bb40639296) collection. Can you take a look to see whether the following curator object list is correct for deleting? Thanks.
[jamesStewartPapers-curator-57.txt](https://github.com/ucsdlib/damspas/files/2761163/jamesStewartPapers-curator-57.txt)

**Comment by gamontoya** [comment]
@lsitu That it, sort of. Your list had four leading b's instead of two. The updated list is here:

[JStewart_57.txt](https://github.com/ucsdlib/damspas/files/2761192/JStewart_57.txt)

**Comment by lsitu** [comment]
@gamontoya I think all 57 curator objects [James Stewart Papers](https://library.ucsd.edu/dc/collection/bb40639296) collection are gone now.
