### ISSUE TITLE
Delete ~3000 SIO Photos Lab objects previously set to curator-only

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#586]
### Descriptive summary

Deletion of these curator-only objects approved by Roger Smith.

### Request
- Delete the 3639 objects listed on the spreadsheet linked below.
- [SIO_Portrait_title_list_deletions_2015_09_30.xlsx](https://github.com/ucsdlib/damspas/files/1812206/SIO_Portrait_title_list_deletions_2015_09_30.xlsx)

### Decision

- Steering Committee decided these images should be set to curator only
- Roger now approved request to delete.

**Comment by lsitu** [comment]
@gamontoya I think all 3639 curator objects listed in [SIO_Portrait_title_list_deletions_2015_09_30.xlsx](https://github.com/ucsdlib/damspas/files/1812206/SIO_Portrait_title_list_deletions_2015_09_30.xlsx) are removed from prod now.
I only see the following 27 curator objects in the SIO Photos collection on prod now:
https://library.ucsd.edu/dc/object/bb76802909
https://library.ucsd.edu/dc/object/bb75437762
https://library.ucsd.edu/dc/object/bb8533548p
https://library.ucsd.edu/dc/object/bb0274077s
https://library.ucsd.edu/dc/object/bb4847631v
https://library.ucsd.edu/dc/object/bb0308339k
https://library.ucsd.edu/dc/object/bb35848216
https://library.ucsd.edu/dc/object/bb4642849m
https://library.ucsd.edu/dc/object/bb7612027t
https://library.ucsd.edu/dc/object/bb00011743
https://library.ucsd.edu/dc/object/bb8977358t
https://library.ucsd.edu/dc/object/bb56326201
https://library.ucsd.edu/dc/object/bb2253754v
https://library.ucsd.edu/dc/object/bb63150884
https://library.ucsd.edu/dc/object/bb59737890
https://library.ucsd.edu/dc/object/bb4676849d
https://library.ucsd.edu/dc/object/bb5632498n
https://library.ucsd.edu/dc/object/bb65881377
https://library.ucsd.edu/dc/object/bb9762168k
https://library.ucsd.edu/dc/object/bb2014658p
https://library.ucsd.edu/dc/object/bb8738272f
https://library.ucsd.edu/dc/object/bb8362885f
https://library.ucsd.edu/dc/object/bb5359701n
https://library.ucsd.edu/dc/object/bb4779240n
https://library.ucsd.edu/dc/object/bb9182008x
https://library.ucsd.edu/dc/object/bb5564229h
https://library.ucsd.edu/dc/object/bb51204976

Could you take a look? Thanks.

**Comment by lmcphee** [comment]
It is expected that there will still be some suppressed objects--those were suppressed for other reasons (they are from other archives collections that have been reappraised over time). As long as the portraits are gone--great!

**Comment by gamontoya** [comment]
@lsitu Thank you.
