### ISSUE TITLE
Delete objects and authority record

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#593]
### Descriptive summary

Per Laurel: 

- Please delete these two items (they were suppressed years ago; now we can carry out the deletion). The original Pride Portrait collection was deaccessioned in 2014.
     - https://library.ucsd.edu/dc/object/bb9182008x
     - https://library.ucsd.edu/dc/object/bb4779240n

- Last, delete the local name authority for Pride Portrait Company, Whittier, California [ARK: bb5155097m]

**Comment by lsitu** [comment]
@gamontoya I think object https://library.ucsd.edu/dc/object/bb9182008x and https://library.ucsd.edu/dc/object/bb4779240n, and the local name authority for Pride Portrait Company, Whittier, California [ARK: bb5155097m] are all gone now.

**Comment by lmcphee** [comment]
Thank you!

**Comment by gamontoya** [comment]
@lsitu Yes, thank you!
