### ISSUE TITLE
Inspect the Disappearing Data - Collection Data from Scripps Research Expeditions 1953-2005 (bb29737300)

### ISSUE THREAD

**Issue by lsitu** [ucsdlib/damspas#599]
### Descriptive summary
On Thursday Feb. 7 at around 9:00am, it was reported that some items in collection [Data from Scripps Research Expeditions 1953-2005](https://library.ucsd.edu/dc/collection/bb29737300) were become orphans and only 639 out of 708 objects showing up in the collection:
https://docs.google.com/document/d/1_6I_yfaYILdKj5_wKSUSNcWG6ECMEw-s5v6yWjnJ4Sk/edit?ts=5c61beac#heading=h.p8chxqxaql7l

We found that the title element is missing from the RDF/XML of the collection CLR and lots of empty elements presented:
<img width="1438" alt="screen shot 2019-02-09 at 5 26 21 pm" src="https://user-images.githubusercontent.com/2430784/52588193-c9a5d480-2df0-11e9-84ea-94be1cc749df.png">

After adding the collection title, removing those empty elements from the CLR bb29737300, and reindexed all 708 items in the collection, the collection were back into normal with 708 items showing up.

### Rationale
@hjsyoo reported that there were some items push to EZID on Feb 4 and Feb 6, 2019. And Katherine observed some unexpected behavior: https://ucsdlibrary.slack.com/archives/C074RV85N/p1549908802018500

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by hjsyoo** [comment]
@lsitu I added a couple of dates to the Description above, and want to note here that the collection page, bb29737300, is still missing a lot of metadata in the UI (i.e., Roles, Dates, Notes).

**Comment by gamontoya** [comment]
Attaching the correct RDF file for the collection in case we need to refer to it.
[20775-bb29737300-0-rdf.txt](https://github.com/ucsdlib/damspas/files/2853137/20775-bb29737300-0-rdf.txt)

**Comment by lsitu** [comment]
@hjsyoo Thanks for all the extra information you provided. I think I've found the problem and create PR PR https://github.com/ucsdlib/damsrepo/pull/79 to fix it, which is caused by the redundant metadata update during the updating DOI process.
@mcritchlow I think the PR https://github.com/ucsdlib/damsrepo/pull/79 for the fixing is ready for review now.

**Comment by gamontoya** [comment]
Kamino cloned this issue to [ucsdlib/damspas](https://github.com/ucsdlib/damspas/issues/601)

**Comment by hjsyoo** [comment]
@lsitu Great to hear! Thanks for investigating so quickly. I'll wait to hear from @gamontoya before we resume updating those DOI records.

**Comment by gamontoya** [comment]
@hjsyoo We won't resume updating DOI records until this fix is in the production environment and after the CLR is fixed. @arwenhutt or I will give the go-ahead, but it might be a week or so.
