### ISSUE TITLE
Update the DOI mint function to prevent from updating DAMSPAS object/collection records

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#601]
From damspas created by [lsitu](https://github.com/lsitu) : ucsdlib/damspas#599  

### Descriptive summary
Update the DOI mint function to prevent it from potentially updating DAMSPAS object and collection records.

See ucsdlib/damspas#599

**Comment by lsitu** [comment]
@mcritchlow I've created PR https://github.com/ucsdlib/damsrepo/pull/80 to fix the potential issue in mint DOI, which may cause the missing metadata problem with full RDF/XML editing.

**Comment by gamontoya** [comment]
@lsitu @hjsyoo Is this ticket closeable?

**Comment by hjsyoo** [comment]
@gamontoya We haven't experienced any further problems with the Update DOI function causing edits to DAMS records, so yes, closing the ticket.
