### ISSUE TITLE
Recreate CLR for Scripps Research Expeditions

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#602]
### Descriptive summary

Reconstruct the CLR for the  [Scripps Research Expeditions](https://library.ucsd.edu/dc/object/bb29737300). Add missing data, fix data links, make sure CLR thumbnail appears, re-index, etc.

**Note:**
<dams:corporateName>
<mads:CorporateName rdf:about="http://library.ucsd.edu/ark:/20775/bb27660034">

... should be carried into all objects for this collection.

### Rationale

The collection level record for the [Scripps Research Expeditions](https://library.ucsd.edu/dc/object/bb29737300) was stripped of many data elements when Ho Jung's student was using the DOI update function. Since then Longshou has updated the code and pushed through a PR. 

The CLR needs to be reconstructed (data links and all) and fixed.
 
----------

Original RDF record attached here

[20775-bb29737300-0-rdf.txt](https://github.com/ucsdlib/damspas/files/2861552/20775-bb29737300-0-rdf.txt)

-------------
### Related work

#599 - Inspect the disappearing data from the Scripps Research Expeditions CLR

------

- Approved by @jessicahilt on 02/13/19

**Comment by lsitu** [comment]
@gamontoya I see corporate name bb27660034 is presenting as Relationship with different roles in the collection CLR . In each object, would you like it to be a subject or still a relationship with a role?
dams:corporateName
<mads:CorporateName rdf:about="[http://library.ucsd.edu/ark:/20775/bb27660034">](http://library.ucsd.edu/ark:/20775/bb27660034%22%3E)

**Comment by hjsyoo** [comment]
@lsitu The original CLR and OLR are still in staging:
\rdcp-0092-sio-explorer\CLR\sio-explorer_clr_20181215.xlsx
\rdcp-0092-sio-explorer\Final_Metadata\SIOx_cruise_reports_OLR_import.xlsx
Neither Geological Data Center nor Scripps Institution of Oceanography show up as Subjects, but they do show up in multiple Roles. And the Role for Scripps Institution of Oceanography varies between collection and object:

CLR - Corporate:Contributor, Corporate:Creator
OLR - Corporate:Contributor

**Comment by lsitu** [comment]
@gamontoya / @hjsyoo I've restored the collection CLR [Data from Scripps Research Expeditions](https://library.ucsd.edu/dc/object/bb29737300) , and added the corporate contributor [Scripps Institution of Oceanography](http://library.ucsd.edu/ark:/20775/bb27660034)  to all 708 objects in the collection. It's ready for review now. Thanks.

**Comment by hjsyoo** [comment]
@lsitu @gamontoya I've reviewed the collection page and spotchecked the objects. All look completely restored. Thank you!

**Comment by gamontoya** [comment]
@lsitu Thanks so much for you work on this!
