### ISSUE TITLE
Add topics to Pacific Basin Nautical Charts Objects

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damspas#617]
For all 1046 Objects in the Pacific Basin Nautical Charts (bb0786509m) Collection:
-  add topic "Maps" (bb4643132s)
- delete dams:genreForm "Nautical charts" (bb4301893z)
- add dams:topic "Nautical charts" (bb2151653q)

**Comment by gamontoya** [comment]
@lsitu Can you take this on for the Sprint that ends on the 26th?

**Comment by lsitu** [comment]
@gamontoya Sure. I'll take care of it.

**Comment by lsitu** [comment]
@gamontoya / @GregReser I've removed dams:genreForm "Nautical charts" (bb4301893z) and added topics "Maps" (bb4643132s) and "Nautical charts" (bb2151653q) to all 1046 objects in collection Pacific Basin Nautical Charts. The changes are ready on on prod for review now. Thanks.

**Comment by gamontoya** [comment]
@GregReser Please review.

**Comment by GregReser** [comment]
@lsitu @gamontoya looks great.  Thanks!
