### ISSUE TITLE
Add component to dataMares object (bb3757060t)

### ISSUE THREAD

**Issue by abbypenn93** [ucsdlib/damspas#618]
### Descriptive summary

Add a new component to object (bb3757060t). And reorder to two existing components. 

### Tasks
Component (add as 1 of 3):
- Title: "Version 3, released April 2019"
- Filename: /rdcp-staging/rdcp-0041-dataMares/subjects/Batch 5/f_gc_trackers_fielddesc.xls
- File use: data-service 
- File type: data
 
 
New component order: 
2 - Fisheries Monitoring Program: Gulf of California artisanal fisheries data
3 - Version 1, released July 2017

**Comment by abbypenn93** [comment]
Hi Gabriela,
Do you need anything else from me to work on this revision?
Thanks,
Abby

**Comment by gamontoya** [comment]
@abbypenn93 Yes. You can tell me how it is that I missed this ticket!

**Comment by gamontoya** [comment]
@lsitu Can you take this ticket?

**Comment by lsitu** [comment]
@gamontoya Sure. I'll take care of it.

**Comment by lsitu** [comment]
@gamontoya / @abbypenn93 We may need to re-ingest the files for those two existing components. Do you have the original source files that I can use for re-ingest?
Also, the title for the first component is "Version 2, released July 2018" at this time. Are you going to change it to "Fisheries Monitoring Program: Gulf of California artisanal fisheries data" as presented above?
```
New component order:
2 - Fisheries Monitoring Program: Gulf of California artisanal fisheries data
3 - Version 1, released July 2017
```

**Comment by lsitu** [comment]
@abbypenn93 Also, I can't find the folder `/rdcp-staging/rdcp-0041-dataMares/subjects/Batch 5/`, and  the file under `/rdcp-staging/rdcp-0041-dataMares/subjects` is `subject_import_dataMares_batch3.xlsx`. Could you double check the location for file `f_gc_trackers_fielddesc.xls`? Thank you.

**Comment by abbypenn93** [comment]
**Original source files:**
Version 2:
/rdcp-staging/rdcp-0041-dataMares/Working_Files/Batch_4_FieldDescFilesforEmbargoes_2018-11/f_gc_trackers_v2_fielddesc.xls

Version 1 -
/rdcp-staging/rdcp-0041-dataMares/Working_Files/Batch_4_FieldDescFilesforEmbargoes_2018-11/f_gc_trackers_v1_fielddesc.xls

**Component names**
I'm glad you noticed the issue with the component names. Correction: the components should be:
Version 3, released April 2019
Version 2, released July 2018
Version 1, released July 2017

**Folder location**
Please remind me what you need the Subjects file for (I didn't create on for the Batch 5 update)

Thanks,
Abby

**Comment by lsitu** [comment]
@abbypenn93 I don't need the Subjects file but the file `f_gc_trackers_fielddesc.xls` you posted above in the description text `Filename: /rdcp-staging/rdcp-0041-dataMares/subjects/Batch 5/f_gc_trackers_fielddesc.xls`. I can't find it in that location. Could you double check what location it is?

**Comment by abbypenn93** [comment]
I must have been very confused on the day I created this ticket--anyway, please use this file for Version 3: /rdcp-staging/rdcp-0041-dataMares/Working_Files/Batch_5_2019-02-26/Updated/f_gc_trackers_fielddesc.xls

**Comment by lsitu** [comment]
Thanks @abbypenn93. I've found it.

**Comment by lsitu** [comment]
@gamontoya / @abbypenn93 I've made the change to reorganize the components to add the new component and re-ingest the existing files for object https://library.ucsd.edu/dc/object/bb3757060t. It's ready for review now.

**Comment by gamontoya** [comment]
@lsitu Thank you!

**Comment by abbypenn93** [comment]
I've been meaning to QA this all week! Looks good, thanks so much, Longshou and Gabriela.
