### ISSUE TITLE
Convert simple object to complex object (bb9355384v)

### ISSUE THREAD

**Issue by abbypenn93** [ucsdlib/damspas#619]
### Descriptive summary

 Convert simple object to complex object (bb9355384v). 

File names for both components are the same.

## Tasks

Component 1 of 2: 
- New file with creation date/time = February 27, 2019 at 8:13 AM
- Located at  /rdcp-staging/rdcp-0041-dataMares/subjects/Batch 5/f_me_anuarios_socioeconomicos.xls
- Title: "Version 2, released April 2019"
- File use: data-service
- File type: data

Component 2 of 2: 
- Old file (f_me_anuarios_socioeconomicos.xls) with creation date/time = 2018-07-13T03:45:45-0700
- Title: "Version 1, released July 2018"

**Comment by gamontoya** [comment]
@lsitu Can you take this ticket?

**Comment by lsitu** [comment]
@gamontoya Sure. I'll take care of it. Thanks.

**Comment by lsitu** [comment]
@gamontoya / @abbypenn93 We may need to re-ingest the `Old file (f_me_anuarios_socioeconomicos.xls) with creation date/time = 2018-07-13T03:45:45-0700`.  Where can I find the the source file? Thanks.

**Comment by lsitu** [comment]
Also, I can't find the file `f_me_anuarios_socioeconomicos.xls` for version 2. Folder `/rdcp-staging/rdcp-0041-dataMares/subjects/Batch 5/` doesn't seem to be there. Could you double check? Thank you.

Here is the list of files/folders I can see under folder `/rdcp-staging/rdcp-0041-dataMares/subjects/`:
```
drwxrwsr-x. 2 apennington lib-datamares   59 Apr 18 14:22 Batch 5 New
drwxrwsr-x. 2 apennington lib-datamares   54 Apr 16 12:18 Batch 5 Update
-rwxrwxr-x. 1 rejohnson   lib-datamares 7970 Jul 12  2018 subject_import_dataMares_batch3.xlsx
```

**Comment by abbypenn93** [comment]
I’ll look for the file and get back to you.

—Abby

On Apr 29, 2019, at 8:33 AM, lsitu <notifications@github.com<mailto:notifications@github.com>> wrote:

f_me_anuarios_socioeconomicos.xls

**Comment by abbypenn93** [comment]
Hi Longshou,


Apologies for adding the wrong file location. I’ll update the ticket. Here’s the path for the updated file:
smb://lib-storage.ucsd.edu/rdcp-staging/rdcp-0041-dataMares/Working_Files/Batch_5_2019-02-26/Updated/f_me_anuarios_socioeconomicos.xls


I searched in the dataMares directory on staging and the only version of ‘f_me_anuarios_socioeconomicos.xls’ that I can find is in the Batch 5 Update directory (shown above).

I got the timestamp for the old version of the file from the Tree View for the object. I’ll talk to Ryan and get back to you.

Thanks,
Abby


On Apr 29, 2019, at 10:01 AM, lsitu <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, I can't find the file f_me_anuarios_socioeconomicos.xls for version 2. Folder /rdcp-staging/rdcp-0041-dataMares/subjects/Batch 5/ doesn't seem to be there. Could you double check? Thank you.

Here is the list of files/folders I can see under folder /rdcp-staging/rdcp-0041-dataMares/subjects/:

drwxrwsr-x. 2 apennington lib-datamares   59 Apr 18 14:22 Batch 5 New
drwxrwsr-x. 2 apennington lib-datamares   54 Apr 16 12:18 Batch 5 Update
-rwxrwxr-x. 1 rejohnson   lib-datamares 7970 Jul 12  2018 subject_import_dataMares_batch3.xlsx

**Comment by lsitu** [comment]
@abbypenn93 I got `f_me_anuarios_socioeconomicos.xls` for version 2 now. Thanks.
Just let me know if we can download the source file for version 1 from dams and use it for re-ingest if can't find the original source file.

**Comment by abbypenn93** [comment]
Ryan is busy at the moment, so if it’s not too much trouble would you please download and re-ingest version 1 of the file?



On Apr 29, 2019, at 11:53 AM, lsitu <notifications@github.com<mailto:notifications@github.com>> wrote:


@abbypenn93<https://github.com/abbypenn93> I got f_me_anuarios_socioeconomicos.xls for version 2 now. Thanks.
Just let me know if we can download the source file for version 1 from dams and use it for re-ingest if can't find the original source file.

**Comment by lsitu** [comment]
@gamontoya / @abbypenn93 Object https://library.ucsd.edu/dc/object/bb9355384v has been converted to complex object on prod. I think it's ready for review now. Thanks.

**Comment by abbypenn93** [comment]
Thank you, I’ll check it out.

—Abby

On Apr 29, 2019, at 11:29 AM, Pennington, Abigail <apennington@UCSD.EDU<mailto:apennington@UCSD.EDU>> wrote:

Hi Longshou,


Apologies for adding the wrong file location. I’ll update the ticket. Here’s the path for the updated file:
smb://lib-storage.ucsd.edu/rdcp-staging/rdcp-0041-dataMares/Working_Files/Batch_5_2019-02-26/Updated/f_me_anuarios_socioeconomicos.xls


I searched in the dataMares directory on staging and the only version of ‘f_me_anuarios_socioeconomicos.xls’ that I can find is in the Batch 5 Update directory (shown above).

I got the timestamp for the old version of the file from the Tree View for the object. I’ll talk to Ryan and get back to you.

Thanks,
Abby


On Apr 29, 2019, at 10:01 AM, lsitu <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, I can't find the file f_me_anuarios_socioeconomicos.xls for version 2. Folder /rdcp-staging/rdcp-0041-dataMares/subjects/Batch 5/ doesn't seem to be there. Could you double check? Thank you.

Here is the list of files/folders I can see under folder /rdcp-staging/rdcp-0041-dataMares/subjects/:

drwxrwsr-x. 2 apennington lib-datamares   59 Apr 18 14:22 Batch 5 New
drwxrwsr-x. 2 apennington lib-datamares   54 Apr 16 12:18 Batch 5 Update
-rwxrwxr-x. 1 rejohnson   lib-datamares 7970 Jul 12  2018 subject_import_dataMares_batch3.xlsx

**Comment by abbypenn93** [comment]
Looks good (didn't mean to wait so long to give you feedback). 
Thanks,
Abby
