### ISSUE TITLE
VRR user with authorization to an object gets a 404 when trying to access

### ISSUE THREAD

**Issue by mdpeters** [ucsdlib/damspas#621]
### Descriptive summary

As a VRR user I've been given access to view a work and the work is listed in my Authorized Works list. In the past I've been able to view the object from the same authorization but now I get a 404 when clicking on the "view" link.

### Expected behavior

Clicking the view link from the Authorized Works list should always take the user to the object.

### Steps to reproduce the behavior

Behavior is hard to reproduce. Thus far seems random but authorization always seems to work in the first but 24-48 hours after authorization but later the user starts getting a 404.

**Comment by mcritchlow** [comment]
@mdpeters - is this still a thing?

**Comment by mdpeters** [comment]
@mcritchlow No, this was how we realized that the auths weren't saving to the database, this is fixed.

**Comment by mcritchlow** [comment]
Awesome, thanks!
