### ISSUE TITLE
Reorder components in Mexican Broadsides object (bb47828081)

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damspas#626]
### Descriptive summary

We need the components reordered for a Mexican Broadsides object [bb47828081](https://library.ucsd.edu/dc/object/bb47828081), as it currently says "Back" then "Front". 

Order should be "Front" then "Back".

**Comment by gamontoya** [comment]
@lsitu For when you have time.

**Comment by lsitu** [comment]
@gamontoya / @remerjohnson We may need to re-ingest the files. Where can I find the original source files? Thanks.

**Comment by remerjohnson** [comment]
@lsitu Sure, the two files are on staging at `//digital-staging/Mexican-Broadsides/batch1/Working_Files/b35582133/`

**Comment by lsitu** [comment]
@gamontoya / @remerjohnson I've reordered the components for object https://library.ucsd.edu/dc/object/bb47828081 on prod. It's ready fro review now.

**Comment by remerjohnson** [comment]
@lsitu Looks great, Longshou! Going to close out. Thanks
