### ISSUE TITLE
Delete Zambian Storytellers object bb2086394p

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damspas#629]
### Descriptive summary

Delete object https://library.ucsd.edu/dc/object/bb2086394p (Interview with Zambian woman) because the content duplicates another object.

Requested by content provider Robert Cancel.

**Comment by gamontoya** [comment]
@VivianChu Do you have time to make this deletion and re-index?

**Comment by VivianChu** [comment]
@gamontoya - Yes, I can do it later today or tomorrow.

**Comment by gamontoya** [comment]
@VivianChu Perfect. Thank you.

**Comment by VivianChu** [comment]
@gamontoya - The object has been deleted in production.
 https://library.ucsd.edu/dc/search?utf8=%E2%9C%93&q=bb2086394p

**Comment by GregReser** [comment]
@VivianChu thank you
