### ISSUE TITLE
Re-ordering of DAMS elements in the UI

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#632]
From dams-metadata created by [hjsyoo](https://github.com/hjsyoo): ucsdlib/dams-metadata#56  

### Summary
Proposing a re-ordering of DAMS elements, as listed in the second column of https://docs.google.com/spreadsheets/d/1n7REAqpt2vh_BQWXFhTbAyVQY5kI7JPOuBAhg8WYTmU/edit#gid=0.

Prior to re-ordering, a conditional placement for Cite This Work, is proposed: https://github.com/ucsdlib/damsmanager/issues/368

### Rationale
Currently, the various Note types in the ranking are broken up by the Subject types, into two rough groupings. This means that many of the notes that are important to Research Data Collections appear after Subjects, which can be extensive. This pushes important information such as Related Publications and Technical Details toward the bottom of the page. Subjects are more likely to be used in order to navigate away from the current page (i.e., to find similar objects), whereas note information can be critical to understanding the data that are available on the current landing page.

### Related Work
https://github.com/ucsdlib/damsmanager/issues/368
https://github.com/ucsdlib/damspas/pull/720#

**Comment by hjsyoo** [comment]
@gamontoya I've met with @cgarciaspitz and @mdpeters , and we've agreed this needs more analysis and testing before we're ready to submit.

**Comment by hjsyoo** [comment]
Possible to make ordering conditional on Unit/Repository?

**Comment by VivianChu** [comment]
@gamontoya - Some elements are missing from the spreadsheet like Subject:Common Name, Subject:Built Work Place, Subject:Function, Subject:Iconography, Subject:Style Period, Subject:Technique, Note:Publication Information, Note:Abstract, Note:General Physical Description, and Note:Dimensions.  
Current order for the missing subject elements - https://github.com/ucsdlib/damspas/blob/master/app/views/shared/fields/_show_raw.erb#L45-L49
Current order for the missing Note fields - https://github.com/ucsdlib/damspas/blob/master/app/views/shared/fields/_show_raw.erb#L75-L77
https://github.com/ucsdlib/damspas/blob/master/app/views/shared/fields/_show_raw.erb#L75-L77
Should I keep the same order for those missing elements?  Thanks

**Comment by hjsyoo** [comment]
@arwenhutt Do we use all those fields? I think we dropped use of Subject:Common Name, but Note:Publication Information is used by Special Collections? I'm fairly sure none of the missing elements above is used by RDCP.

**Comment by arwenhutt** [comment]
@hjsyoo some are in use (like abstract, general physical description, dimensions) but some are deprecated (the subjects Vivian listed) meaning we no longer use them when ingesting new collections.  But even the deprecated ones may have legacy values.

**Comment by hjsyoo** [comment]
Good point about legacy values, @arwenhutt! 

@VivianChu I've added those missing values to the spreadsheet and moved some of the Notes around to keep similar types together on the list. I've tried to highlight all the new changes in green.

**Comment by VivianChu** [comment]
Thanks @hjsyoo & @arwenhutt .  I'll update the order of these elements while waiting for the input of the ticket about Note:Cite This Work https://github.com/ucsdlib/damsmanager/issues/368.

**Comment by VivianChu** [comment]
@hjsyoo - Is there any other type for the date element beside creation, issued, event, and collected?  I updated the date order and here are the screen shot.
Before the update
![dateBeforeChange](https://user-images.githubusercontent.com/1864660/66957520-3e35b080-f01b-11e9-9159-ac72dfd137a6.png)

After the update
![dateAfterChange](https://user-images.githubusercontent.com/1864660/66957526-4261ce00-f01b-11e9-80c9-7999ac69b23f.png)

**Comment by VivianChu** [comment]
@gamontoya @hjsyoo - The changes have been deployed to qa.  Could you review them?
For example 
//example - rdc objects
http://libraryqa.ucsd.edu/dc/object/bb04139816
http://libraryqa.ucsd.edu/dc/object/bb2018464v

//non rdc objects
http://libraryqa.ucsd.edu/dc/object/bb5157099g
http://libraryqa.ucsd.edu/dc/object/bb1574705v

Thanks

**Comment by hjsyoo** [comment]
@VivianChu The only other date I'm aware of is Date:Copyright, which we've requested be placed right after Rights Holder.

I've looked at a number of RDC colls and objects on qa, and the ordering looks great (it'll take some getting used to, but it's much better!).

**Comment by VivianChu** [comment]
@hjsyoo - The copyright date has been added and deployed to qa.  Could you review it?  
https://libraryqa.ucsd.edu/dc/object/bb2083712b
Thanks

**Comment by hjsyoo** [comment]
@VivianChu Yes, it's in the right place.

**Comment by hjsyoo** [comment]
@VivianChu @gamontoya @arwenhutt I've updated https://github.com/ucsdlib/damsmanager/issues/368 to reflect the decision to apply a conditional rule for placement of Note:Preferred Citation. The re-ordered element list (https://docs.google.com/spreadsheets/d/1n7REAqpt2vh_BQWXFhTbAyVQY5kI7JPOuBAhg8WYTmU/edit#gid=0) has also been updated to improve clarity (no changes made to the proposed order).
