### ISSUE TITLE
Multiple value fields not sorting alphabetically

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#633]
From dams-metadata created by [GregReser](https://github.com/GregReser): ucsdlib/dams-metadata#43  

### Description
It appears that there is no sort logic for many fields in the DAMS 4 UI. Several project managers and data providers have requested that this be changed to default to alphabetic sort, if a specific order is not specified.

### Example of random sort:
![image](https://user-images.githubusercontent.com/5453716/32452446-65b8eaa4-c2ce-11e7-95f4-fb5396cfc149.png)

### Request
For all fields that allow multiple values, if the display order is not specified, display alphabetically

**Comment by GregReser** [comment]
@gamontoya the problem of random sorting applies to many fields, can we change the title of this ticket to: Multiple value fields not sorting alphabetically
The request is to default to alphabetic sort, if a specific order is not specified. The description in the ticket reflects this, but the title might make it seem like it's only for Geographics.

**Comment by mcritchlow** [comment]
@GregReser - I'm going to start on this today. Unfortunately the code for this is not very centralized.. so I'm going to have a touch a number of files. I'll try and make sure I get everything, but once I think I have it I'll deploy to QA and ask for you to take a peek if that works for you.

**Comment by hjsyoo** [comment]
Thanks, @mcritchlow. Geographics, Anatomy, Scientific Names, and Common Names are sorting alphabetically in staging.
