### ISSUE TITLE
Re-ordering of Role types in the UI

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#634]
From dams-metadata created by [hjsyoo](https://github.com/hjsyoo): ucsdlib/dams-metadata#55  

### Summary
Propose a re-ordering of Role types. The current D5 data dictionary is listed here: https://docs.google.com/spreadsheets/d/11B4lwD6qOHHvl3xmuU6aPTN_UMu-YMqBZ4XzwFDAKNE/edit#gid=1415126809.
The proposed new order for roles is listed in https://docs.google.com/spreadsheets/d/1sqdKcivHu36WnQweP-cslpsbpD26bwC1znvX52cQSHU/edit#gid=0.

### Rationale
Currently, Role types are ordered alphabetically for the most part, with an exception for Principal Investigator and Co-Principal Investigator. Like these exceptions, there are other roles that should appear higher in rank.

### Proposal
When these Roles are assigned for collections or objects, rank them in the UI in the following order:

- Creator
- Director
- Project Director
- Lead
- Author
- Principal Investigator
- Co-Principal Investigator
- Research Team Head
- Field Director
- Laboratory Director
- Researcher
- Research Team Member
- Analyst
- Data Contributor
- Data Manager
- Field Assistant
- Laboratory Assistant
- Photographer
- Advisor
- Thesis Advisor
- Contributor
- [All other Roles in alphabetical order]
- Other

**Comment by gamontoya** [comment]
@hjsyoo You need to meet with Cristela and Matt P. before we'll take action on this request.

**Comment by mcritchlow** [comment]
@hjsyoo - do you have any good example records that demonstrate some, or even most, of these? I'm going to get started on this, and mostly want to make sure we're checking metadata correctly (case, spelling, etc.). Thanks!

**Comment by hjsyoo** [comment]
@mcritchlow Do you mean examples where the current order doesn't work well?
https://library.ucsd.edu/dc/collection/bb22212199
https://library.ucsd.edu/dc/collection/bb96275693
Or the official spellings of Roles? I was working off of this sheet, although we should get confirmation from @arwenhutt on whether this is the most authoritative version:
https://docs.google.com/spreadsheets/d/11B4lwD6qOHHvl3xmuU6aPTN_UMu-YMqBZ4XzwFDAKNE/edit#gid=1415126809

**Comment by arwenhutt** [comment]
@lsitu the most authoritative list of roles would be in the [standard input template on github](https://github.com/ucsdlib/dams-metadata/blob/master/xls_standard_input_template.xlsx) 

@mcritchlow There are some examples where ordering doesn't work well in @hjsyoo 's [comment here](https://github.com/ucsdlib/dams-metadata/issues/55#issuecomment-351842760)
And there's [this tracer record](https://library.ucsd.edu/dc/object/bb2083712b) (curator only) in the DAMS which has almost all the roles.  A few were added after that was ingested.  Let me know if it would be helpful to have a more up to date tracer record and we can ingest one.

**Comment by hjsyoo** [comment]
@mcritchlow I'm reviewing the deploy on staging, and seeing duplicated Roles fields:

- https://librarytest.ucsd.edu/dc/collection/bb22212199 (second instance of Research Team Members)
- https://librarytest.ucsd.edu/dc/collection/bb5291666j (Creator)
- https://librarytest.ucsd.edu/dc/collection/bb0378352k (Field Directors)
- https://librarytest.ucsd.edu/dc/collection/bb62154893 (PI)

Otherwise, role order looks good.

**Comment by mcritchlow** [comment]
@hjsyoo - oh, i think i see the issue. We have an odd, or at least it seems odd to me, situation where sometimes the role values are capitalized and sometimes they're not. it looks like we have a gap there. I should have a patch up shortly.

**Comment by mcritchlow** [comment]
@arwenhutt this probably warrants a separate ticket, but i am curious about our spelling inconstency when it comes to roles. See the following from one the examples @hjsyoo mentioned:

https://librarytest.ucsd.edu/dc/collection/bb22212199

```
{\"research team head\":[\"Betha, Raghu\"],\"Research team member\":[\"Chen, Chia-Li\",\"Liu, Jun\",\"Price, Derek J.\",\"Sanchez, Kevin J.\"],\"contributor\":[\"Lee, Alex\",\"Scripps Institution of Oceanography\"],\"principal investigator\":[\"Russell, Lynn M.\"]}
```

Note how everything is lowercase, except `Research team member`. I noticed when working on this code that we already had code in place that was checking for capitalization (or not). I am going to get a patch up to fix a gap I missed that's causing these duplicate entries, but it does make me wonder if this is something we might be able to clean up/normalize?

**Comment by arwenhutt** [comment]
@mcritchlow thanks for the heads up! I can edit those role records to make the casing consistent.

**Comment by mcritchlow** [comment]
@arwenhutt - do you need a report of all instances for a more global cleanup? I ask because this seems like something that is likely a legacy issue and I believe our current create/edit interfaces wouldn't allow this. But there's probably quite a few records with these capitalized roles. There were enough, at least, for us to have source code testing for both :)

**Comment by arwenhutt** [comment]
@mcritchlow oh, yeah, that's probably a good idea.  a report with all unique role values (role ark, authoritative label value) would be great - thanks!

**Comment by mcritchlow** [comment]
@arwenhutt - sounds good, I've created #677 for that
