### ISSUE TITLE
Change "Browse by Topic" navigation menu

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#635]
### Descriptive summary

Replace << Previous | >> Next browse by buttons with page navigator used by "Browse by Collections"

----------------

- This ticket needs a bit of investigation to see if the navigator makes sense.
- Might have to re-write the pager.

**Comment by gamontoya** [comment]
This ticket needs a bit of investigation to see if the navigator makes sense.

**Comment by VivianChu** [comment]
@gamontoya -  When I change "Browse by Topic" navigation menu, other browse by option like format and creator will change too since they all use the same navigation menu.  Is it ok to do that?  Thanks

**Comment by gamontoya** [comment]
@VivianChu Let me check on that.

**Comment by gamontoya** [comment]
@VivianChu It doesn't make sense for _Format_ and _Creator_ has an A-Z navigator on top. Can you go ahead and implement on QA for us to review/see?

**Comment by VivianChu** [comment]
@gamontoya - Currently all browse by pages have A-Z navigator on top.  I'm not going to change anything.  For example from production Creator & Format - https://library.ucsd.edu/dc/search/facet/creator_sim?facet.prefix=A&facet.sort=index
https://library.ucsd.edu/dc/search/facet/object_type_sim?facet.sort=index

I'm asking about the Previous | next menu.  It will be same for all 3 pages.
Here's my change locally for Browse By Topic
![browseByTopic](https://user-images.githubusercontent.com/1864660/60991870-366dbe00-a300-11e9-8c7c-7f38c78d0f21.png)

**Comment by gamontoya** [comment]
@VivianChu I just spoke to Cristela and she thinks it's fine. But, she asked if you could remove the page and Sort navigators from the top and only leave them on the bottom.

![browse](https://user-images.githubusercontent.com/4314914/60992517-813c0580-a301-11e9-8268-b6e7347545d6.png)

**Comment by VivianChu** [comment]
@gamontoya - I could remove it.  I'll let you know when it's ready to review in QA.  I still need to write tests for it.

**Comment by VivianChu** [comment]
@gamontoya - The change has been deployed to qa.  Could you review it?  For example - http://libraryqa.ucsd.edu/dc/search/facet/subject_topic_sim?facet.prefix=A&facet.sort=index  
Thanks

**Comment by gamontoya** [comment]
@VivianChu Looks good. You purposely left out the page navigator for **format**, correct?

**Comment by VivianChu** [comment]
@gamontoya - No, I didn’t left out page navigator for format. The page navigator will display if there are more values than the limit which is 20. Format has only 12 values.

**Comment by gamontoya** [comment]
@VivianChu Sounds good. Thank you!

**Comment by VivianChu** [comment]
@gamontoya - The update has been deployed to qa.  Could you review it again?  Thanks

**Comment by gamontoya** [comment]
@VivianChu Looks fabulous!
