### ISSUE TITLE
Update Help Menu with info. on data deposit

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#637]
### Descriptive summary

An added option in the Help menu, "Deposit your Research Data". This link directs the user to https://library.ucsd.edu/research-and-collections/data-curation/index.html#Data_Deposit. 

### Rationale
Currently, visitors to the DAMS have no information on how to deposit data.

**Comment by hjsyoo** [comment]
Thanks! The link works properly in staging.
