### ISSUE TITLE
Add component to AWARE object (bb7068315z)

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damspas#641]
### Descriptive summary

Add a new component to the object [bb7068315z](https://library.ucsd.edu/dc/object/bb7068315z).  

### Tasks
The new component will be the 5th component, titled "FTIR Baselined Spectra". The file for this component is on staging at: `//rdcp-staging/rdcp-0109-aware/Working_Files/Data from Lynn 2019-05-23/Baselined_spectra_AWARE.txt`

The new component order then will be:  
1. FTIR Plot
2. Data
3. XRF Plot
4. Data
5. FTIR Baselined Spectra

### Related work

ucsdlib/dams-metadata/issues/132

**Comment by gamontoya** [comment]
@lsitu Can you take this ticket?

**Comment by lsitu** [comment]
@gamontoya Sure. I'll take care of it. Thank.

**Comment by lsitu** [comment]
@gamontoya / @remerjohnson I've added the new component to object https://library.ucsd.edu/dc/object/bb7068315z. It's ready for review now. Thanks.

**Comment by remerjohnson** [comment]
@lsitu Perfect Longshou. Thanks. Going to close this now
