### ISSUE TITLE
Create conditional copyright boilerplate, for objects with CC license

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damspas#642]
### Descriptive summary

Change display of "Copyright Constraint(s) on Use" boilerplate for Research Data Collections, wherever Rights holder is UC Regents and Creative Commons license is applied, to

"This work is protected by U.S. Copyright Law (Title 17, U.S.C.), and made available under a Creative Commons (CC) license. Use of this work beyond that allowed by "fair use" or the CC license requires written permission of UC San Diego. Responsibility for obtaining permissions and any use and distribution of this work rests exclusively with the user and not the UC San Diego Library. Inquiries can be made to the UC San Diego Library program having custody of the work." 

Where Rights holder is an individual(s) and CC is applied, use the variant:

"This work is protected by U.S. Copyright Law (Title 17, U.S.C.), and made available under a Creative Commons (CC) license. Use of this work beyond that allowed by "fair use" or the CC license requires written permission of the copyright holder(s). Responsibility for obtaining permissions and any use and distribution of this work rests exclusively with the user and not the UC San Diego Library. Inquiries can be made to the UC San Diego Library program having custody of the work."

### Rationale

The current text is confusing wherever CC has been applied. The revision above was suggested by Katie Fortney, UC Copyright Officer, to clarify the text for users. Aside from references to the Creative Commons license, the new text states that permission should be requested from UC San Diego. The current text for the UC authority lists "UC Regents". "UC San Diego" is almost equally vague, but it indicates that the authority is local. Library staff responding to inquiries should be aware that the current delegated authority is the UCSD Office of Innovation and Commercialization, formerly known as Tech Transfer.

-----------

- Effort is low for now unless conditional is more complicated.

**Comment by hweng** [comment]
@hjsyoo I want to clarify that this boilerplate is for RDCP collection only, and the DLP collection should not be changed, correct?

**Comment by hweng** [comment]
@hjsyoo Also can you send me a couple of sample records in case there is variations? so that i can decide if need to apply the conditional statements. Thanks!

**Comment by hjsyoo** [comment]
@hweng Right, this boilerplate is for RDCP only, because we regularly apply CC licenses. I don't think DLP does.
Here's an example that has Rights Holder=UC Regents and License=Creative Commons: https://library.ucsd.edu/dc/object/bb2391869d
And the other example, Rights Holder=third party and License=Creative Commons: https://library.ucsd.edu/dc/object/bb7886108t
The two boilerplates differ only in that the first references "UC San Diego" (where UC Regents is the Rights Holder) and the second references the "copyright holder" where it's a third party entity.

**Comment by hweng** [comment]
@hjsyoo Two questions to clarify:
For RDCP, is the Rights Holder either "UC Regents" or the third party such as in bb7886108t "DeFanti, Thomas A.; Saad, Adel; Wickham, Greg; Ainsworth, Richard A."? 
It doesn't have other variations, correct? 

2. For RDCP, all items are applied "Creative Commons Attribution 4.0 International Public License", correct?

**Comment by hjsyoo** [comment]
@hweng 1. Yes, up to this point, I believe that's correct. Public domain (e.g., https://library.ucsd.edu/dc/object/bb0753405q) is also possible, but we don't need to change the text for those cases.
2. No, there are 6 possible Creative Commons licenses: https://creativecommons.org/licenses/. I'm not sure what the wording looks like for each of those in the DAMS import tool, but we can ping DOMM for that information if needed.

**Comment by hweng** [comment]
@hjsyoo I've added conditional copyright boilerplate and deployed the code to QA. Could you take a look of QA to see if it looks good to you?

https://libraryqa.ucsd.edu/dc/object/bb2391869d
https://libraryqa.ucsd.edu/dc/object/bb7886108t

**Comment by hjsyoo** [comment]
@hweng The new text looks good in both examples, but in https://libraryqa.ucsd.edu/dc/object/bb7886108t, the Rights Holder field is missing.

**Comment by hweng** [comment]
@hjsyoo I will look into it. thanks!

**Comment by hweng** [comment]
@hjsyoo I've looked into bb7886108t record, the data is missing on QA for rights Holder ```rightsHolder_tesim: [
"DeFanti, Thomas A.; Saad, Adel; Wickham, Greg; Ainsworth, Richard A."
],``` 

But the rights holder data for bb7886108t exist on staging and production. 
Do you want me to deploy it to staging so that you can verify it?

**Comment by hjsyoo** [comment]
No worries, then! As long as the rights holder info won’t disappear in prod, we’re good! Please feel free to close this ticket any time.
