### ISSUE TITLE
Sort collections view by most recently added, by default

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damspas#644]
### Descriptive summary

Collections view for RDC (https://library.ucsd.edu/dc/rdcp/collections) should sort, by default, by most recently added collections, rather than the current alphabetic sort. 

### Rationale

This is a nearly ubiquitous practice in research data repositories, and emphasizes the most recently added collections rather than those beginning with "A". Alphabetic sort by title can remain an option under Sort.

### Note

- ONLY for RDCP collections.

**Comment by gamontoya** [comment]
Kamino cloned this issue to [ucsdlib/damspas](https://github.com/ucsdlib/damspas/issues/660)

**Comment by hjsyoo** [comment]
@mcritchlow Looking at https://librarytest.ucsd.edu/dc/rdcp/collections, collection sort order doesn't match my expectations. We haven't touched at least the first ~10 collections that show up in the display this year (as far as I know - we may need confirmation from @remerjohnson @arwenhutt @abbypenn93), yet we've published ~8 new colls in 2019, none of which show up at all. 
Also, how is system modified date determined? I wonder if non-intentional updates (like re-indexing) to a collection might push it up in ranking?

**Comment by mcritchlow** [comment]
@hjsyoo - Yes, this is the same system date in Solr we were discussing in the other ticket. To my knowledge, similar to our other discussion, we don't have a better, more reliable, date to key on for whether a record was modified. Reindexing a collection record, as you note, would definitely result in a more recent modified date in the Solr document.

**Comment by mcritchlow** [comment]
Reopening, as we need to take an alternative approach to solving this problem.

**Comment by hjsyoo** [comment]
@mcritchlow Thanks for reverting this fix for the release. I think what's different here from the date issue in #643 is that we're interested in when the collection was first ingested, and not really when updates are made anywhere in the collection. I wouldn't want a collection to sort first simply because we replaced a file or made a minor change to the metadata on one of its objects. We're just trying to showcase newly added collections and show that we're actively adding new collections to the DAMS. I wonder if we have a suitable date field for this, given our discussion in #643?

**Comment by mcritchlow** [comment]
@hjsyoo - sure thing, and i think the distinction you make is an important one that we need to clarify and be mindful of in a final solution. So this is similar to #643, but different in that what you want is the "created date" event for the record, not the "modified date", which can change over time. My understanding is that neither of these are readily, consistently available. But clearly, we need to make them so.

**Comment by mcritchlow** [comment]
@hjsyoo , @lsitu - i've created https://github.com/ucsdlib/damsrepo/issues/92 as a starting point for the technical discussion of how to ensure we're properly tracking these created/modified event dates.

@lsitu - If i mispoke in the description of that ticket, please feel free to correct/modify as needed :)

**Comment by gamontoya** [comment]
@mcritchlow Is this in this latest DAMPAS release 1.92.2?

**Comment by mcritchlow** [comment]
@gamontoya - it is not. it's on hold pending the full solr reindex in QA, and then subsequent testing of the work in this PR https://github.com/ucsdlib/damspas/pull/681

So this will hopefully be in the next release
