### ISSUE TITLE
Add 'text' as Type of Resource / Format to all Mexican Broadsides Batch 1 objects

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damspas#645]
### Descriptive summary

The Type of Resource / Format value of "text" needs to be added to all Batch 1 objects in Mexican Broadsides: https://library.ucsd.edu/dc/collection/bb8605360n. 

I'm attaching an edited version of the ARK report for Batch 1, let me know if that works, or if you need just the bare ARK report.

[arkReport-mexican-broadsides-b1.xlsx](https://github.com/ucsdlib/damspas/files/3258495/arkReport-mexican-broadsides-b1.xlsx)

**Comment by VivianChu** [comment]
@gamontoya - The text Type Of Resource has been added to all objects.  Do I also need to change the TypeOfResource value for the collection level object from "image" to "text"?

 Could you review them?
For example

https://library.ucsd.edu/dc/object/bb9117308p
https://library.ucsd.edu/dc/object/bb6694080n
https://library.ucsd.edu/dc/object/bb3144575f

Thanks

**Comment by gamontoya** [comment]
@VivianChu Yes, please update the collection level record to 'text'. Thank you!

**Comment by VivianChu** [comment]
@gamontoya - The typeOfResource has been updated for the collection level record.  https://library.ucsd.edu/dc/collection/bb8605360n

**Comment by remerjohnson** [comment]
Thanks all! It looks great 👍
