### ISSUE TITLE
Web accessibility: include Alt Text 

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#648]
### Descriptive summary

**Easy fix for improving accessiblity:**

WCAG 2.0 Guideline 1.1.1—"All non-text content that is presented to the user has a text alternative that serves the equivalent purpose."

ALT text refers to invisible description of images which are read aloud to blind users on a screen reader. Adding ALT text allows web creator to include images, but still provide the content in an alternative text based format. 

ALT tags are generally recommended to be concise (about 125 characters or 256?)

---------

**Pull text from "title" for all objects**

- Bootstrap and Rails should support this.
- Lay out all scenarios as a ticket.
- For all objects that have thumbnails.

**Comment by jessicahilt** [comment]
125 characters of the title will be the alt text.

**Comment by gamontoya** [comment]
@VivianChu How do I test this to see if it's working?

**Comment by VivianChu** [comment]
@gamontoya - You can do view source for any image object on staging and search for "img alt".
For example 
https://librarytest.ucsd.edu/dc/object/bd5891931g

<a href="/dc/object/bd5891931g/zoom/0"><img alt="65th College Art Association Conference, Los Angeles" src="/dc/object/bd5891931g/_3.jpg" /></a>

**Comment by gamontoya** [comment]
When you are viewing the object(s), when you hover over the image, do you see the text/title?

**Comment by VivianChu** [comment]
I don't see the text/title when hover over the image.  More info about it can be found here - https://www.computerhope.com/issues/ch001076.htm

**Comment by VivianChu** [comment]
@gamontoya - from that article, if we also put title value in  the attribute "title", then it would show.

**Comment by gamontoya** [comment]
@VivianChu Can you do that. This was the expected behavior.

**Comment by VivianChu** [comment]
@gamontoya - sure, I can do that.

**Comment by VivianChu** [comment]
@gamontoya - The title attribute has been added.  The changes have been deployed to qa.  Could you review it?  For example
//single object
http://libraryqa.ucsd.edu/dc/object/bb68628087

//complex object
http://libraryqa.ucsd.edu/dc/object/bb35511535

Thanks

**Comment by gamontoya** [comment]
@VivianChu You got it! Looks correct now. Thank you.

**Comment by gamontoya** [comment]
@VivianChu What is the dependency for this to get pushed to prod?

**Comment by VivianChu** [comment]
@gamontoya - I just checked production and it was already deployed 4 days ago.  https://github.com/ucsdlib/damspas/issues/693#issuecomment-515042552
For example
https://library.ucsd.edu/dc/object/bb4646166j

**Comment by gamontoya** [comment]
@VivianChu Thank you!
