### ISSUE TITLE
Disable download and embed buttons for authorized works view in VRR

### ISSUE THREAD

**Issue by mdpeters** [ucsdlib/damspas#654]
### Descriptive summary

In the authorized user view of a VRR object, remove the download and embed buttons from the object view so authorized VRR users cannot download files or try to generate embed links that won't work due to the restricted nature of the materials.

### Related work

- https://github.com/ucsdlib/damsmanager/issues/332
- https://github.com/ucsdlib/damsmanager/issues/331
- https://github.com/ucsdlib/damsmanager/issues/320

**Comment by gamontoya** [comment]
@hweng FYI, the hook will be

```<dams:note>
      <dams:Note>
        <dams:displayLabel>local</dams:displayLabel>
        <rdf:value>scarare</rdf:value>
        <dams:type>identifier</dams:type>
      </dams:Note>
    </dams:note>

**Comment by hweng** [comment]
@gamontoya Can you send me a vrr record? I would like to look into its solr data structure as damspas use solr index.  
And also can I get the test account for vrr so that I can test the code? Thanks!

**Comment by gamontoya** [comment]
@hweng I don't have a VRR record and I don't think one exists in the DAMS. @mcritchlow @mdpeters Can you confirm?

**Comment by gamontoya** [comment]
@hweng Note that the correct hook is:

```
      <dams:Note>
        <dams:displayLabel>local</dams:displayLabel>
        <rdf:value>vrr-sca</rdf:value>
        <dams:type>identifier</dams:type>
      </dams:Note>
    </dams:note>
```

**Comment by gamontoya** [comment]
@hweng I'll open a Service Desk ticket asking that you be added to the VRR group.

**Comment by hweng** [comment]
@gamontoya Thanks!  Can you make a VRR test record? The hook above is in RDF format, but damspas interface use solr index so it need to look into the solr index to see what the structure it is? Is it present in the solr index? Then I can decide how to incorporate the correct trigger into the code.

**Comment by gamontoya** [comment]
@hweng No, I can't. Maybe @mdpeters can?

**Comment by mdpeters** [comment]
@hweng I updated one of our VRR test records in staging to have the requisite note field: https://librarytest.ucsd.edu/dc/object/bd27178934 

Let me know if you need tests for any other variations.

**Comment by hweng** [comment]
@mdpeters 
 I don't find "vrr-sca" value from solr index for this record:
http://lib-hydratail-staging.ucsd.edu:8983/solr/blacklight/select?q=id:bd27178934
