### ISSUE TITLE
Edit preferred citation value of objects in Thurgood Marshall College. Office of the Provost Records

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damspas#656]
### Description
For all 767 objects in Thurgood Marshall College. Office of the Provost Records (bb7817150v)
- Replace the current value of dams:Note @type "preferred citation" with the new value:
"[TITLE]. Thurgood Marshall College. Office of the Provost Records. RSS 1130. Special Collections &amp; Archives, UC San Diego"

The current preferred citation values are all different.  The new value will be the same for all objects.

**Comment by hweng** [comment]
@gamontoya I've queried and edited notes for all 767 objects in Thurgood Marshall College based on the above requirements. And the solr index updating was done.

It looks good to me, for instance:
https://library.ucsd.edu/dc/object/bb90797993

Could you take a look if it looks good to you too?

**Comment by hweng** [comment]
@gamontoya The 767 objects have been updated and indexed. Does it look good to you now?

**Comment by gamontoya** [comment]
@hweng Yes, it looks good to go.
