### ISSUE TITLE
Ignore characters when sorting by default title

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#661]
### Descriptive summary

Currently in the default sort (by title), titles with apostrophes or quotes get sorted first. Is it possible to ignore initial characters and force the alpha sort?

### Example

![sort](https://user-images.githubusercontent.com/4314914/59793988-bc13c600-928c-11e9-934b-dfc8e24a8d8f.png)

**Comment by mcritchlow** [comment]
@gamontoya - I think this should be possible. We'll have to test for side-effects/regressions. But I'm fairly certain we can do this w/ Solr

**Comment by gamontoya** [comment]
@mcritchlow Awesome!

**Comment by gamontoya** [comment]
@mcritchlow What's the dependency for this ticket?

**Comment by mcritchlow** [comment]
https://github.com/ucsdlib/damsrepo/issues/92 - which is the QA reindexing to finish and those tickets reviewed. the reindexing has had to restart several times, which unfortunately has meant the ability to properly test has taken quite a while..

**Comment by gamontoya** [comment]
@mcritchlow Thank you!

**Comment by mcritchlow** [comment]
@gamontoya - OK, this is done and available to review QA:

https://libraryqa.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=Holocaust+Living+History+Workshop&id=bb4404992g&sort=title_ssi+asc

It looks like it's working to me, but of course want to double check with you to confirm :)

**Comment by arwenhutt** [comment]
@mcritchlow it looks like "quotes" are being ignored, but there are other characters that seem like they might be good to also leave out of the sorting:
[, !, ?, #, +, -, maybe $

I found these by searching for "a", sorting by title, and skimming through till I got to the first title that didn't have a character first (page 124 of search results.)  

I'm not sure if these are in scope for this ticket or not.

**Comment by mcritchlow** [comment]
@arwenhutt - thanks! yeah those weren't in scope, it was for apostraphes and quotes.

I can add them since you discovered an example, though we probably won't want to hold this ticket up for that to be completed, primarily because this change requires large scale solr reindexing. That said, I'll create a ticket to add those to the list of characters and create a reference to it here. Thanks again for reviewing this.

Ticket for additional characters: https://github.com/ucsdlib/dams4-solr/issues/6

**Comment by arwenhutt** [comment]
I figured they were probably out of scope, but thought I'd mention them just in case.  I agree that there's no reason to hold this ticket up for those.  

Also, I think it'd be good to get Gabriela and maybe others, to review additional characters - I think they make sense to ignore, (except maybe $?) but that's a little more than my 2c ;)

**Comment by mcritchlow** [comment]
@arwenhutt - yeah that's a great point, given the reindexing involved, it would be nice to get a comprehensive list put together before making any further changes. I'll note that in the ticket, thanks again!
