### ISSUE TITLE
Data Sync to Staging environment

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#680]
From damspas created by [gamontoya](https://github.com/gamontoya): ucsdlib/damspas#679  

### Descriptive summary

- Data sync needed from prod to QA. This should include everything (triplestore, solr, files, etc.)

### Needed for 

- [ ] Enforce _created_ and _modfied_ dates https://github.com/ucsdlib/damsrepo/issues/92

**Comment by gamontoya** [comment]
@rstanonik @jgorney Okay, requesting a data sync from prod to staging now.

**Comment by jgorney** [comment]
We are starting now.

**Comment by rstanonik** [comment]
I started the file sync from prod to staging.

I give an estimate of the time after it has run for a while.

In the meantime, I'll sync solr from prod to staging.

**Comment by rstanonik** [comment]
solr has been synced from prod to staging.
Hmm, since file sync takes so long, maybe should repeat solr sync after file sync finishes.

**Comment by jgorney** [comment]
The database triplestore table sync from prod to staging is complete.

**Comment by rstanonik** [comment]
file sync is 8% after  1 1/2 hours, so estimate about 18 hours.

**Comment by rstanonik** [comment]
9% after 5 1/2 hours.  Ran into the same 2.2T object as qa.  Current estimate is 61 hours.

**Comment by rstanonik** [comment]
70% after  22 1/2 hours, so estimate another 9 1/2 hours.  The percentage is not of data size, but of number of objects (ARKs) scanned for changes.  So, perhaps I should say 70% of ARKs scanned.

**Comment by rstanonik** [comment]
The file sync finished Fri Jul 12 19:53

**Comment by gamontoya** [comment]
@rstanonik @jgorney Thank you!
