### ISSUE TITLE
Navigation bar to jump from one object to the next missing on staging environment

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#691]
### Descriptive summary

On the [staging environment](http://librarytest.ucsd.edu/dc), the top navigation bar to click from one item to the next does not display.  

**Compare:**

![image](https://user-images.githubusercontent.com/4314914/61501164-09b24a00-a983-11e9-8d81-6d9a1f095a70.png)

**With:**

![image (1)](https://user-images.githubusercontent.com/4314914/61501169-0e76fe00-a983-11e9-98d0-4aad898d7fa7.png)

**Comment by VivianChu** [comment]
@gamontoya - The problem has been fixed on staging.  Could you review it?  Thanks

**Comment by gamontoya** [comment]
@VivianChu 👏 Yes, works nicely now!
