### ISSUE TITLE
Add image to empty NAAMES component (bb7512314s)

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damspas#694]
### Descriptive summary

The NAAMES component ([bb7512314s](https://library.ucsd.edu/dc/object/bb7512314s)) currently has an empty Component 17 ("SP2 number size distribution"), and needs a .png image added to it. 

The file is `naames-RUSSELL-SP2NumberSizeDistribution_Atlantis_20170830_R0_SummaryPlot.png` and is located at: 
`//rdcp-staging/rdcp-0112-naames/Working_Files/NAAMES3_processedfiles and summary plots/`

### Related work

ucsdlib/dams-metadata/issues/140

**Comment by gamontoya** [comment]
@lsitu Can you take this on? Seems pretty straight forward.

**Comment by lsitu** [comment]
@gamontoya Sure. I'll take care of it.

**Comment by lsitu** [comment]
@gamontoya / @remerjohnson The file is ingested and it's ready for review now: https://library.ucsd.edu/dc/object/bb7512314s. Thanks.

**Comment by gamontoya** [comment]
@lsitu Thank you!
