### ISSUE TITLE
SDHC Oral Histories - replace HTML service file with PDF

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#695]
### Descriptive summary

- Per the request of the San Diego History Center staff, we need to swap the HTML `service` file with a PDF version in the [San Diego History Center Oral Histories collection](https://library.ucsd.edu/dc/collection/bb20830477). The HTML file should be saved as a document-source (or text?) that can be downloaded by curators. 

- As a complex object (e.g. https://library.ucsd.edu/dc/object/bb2629146f), the PDF is the transcript component. Note that not all objects are complex in this collection set.

- The collection should show thumbnails derived from the PDFs.

- 52 objects in the collection

### Location of Files

- \\libstorage.ucsd.edu\digital-staging\San Diego History Center Oral Histories

**Comment by VivianChu** [comment]
@gamontoya - The HTML service file has been replaced with PDF for 30 complex and 22 simple objects for this collection.  The HTML file is saved as document-source and can be downloaded by curators.  Could you review them?  For example 
//simple
https://library.ucsd.edu/dc/object/bb25950187
https://library.ucsd.edu/dc/object/bb0001140k

//complex
https://library.ucsd.edu/dc/object/bb2629146f
https://library.ucsd.edu/dc/object/bb0035268x

Thanks

**Comment by gamontoya** [comment]
@VivianChu Looks great, Vivian!
