### ISSUE TITLE
Add research data images to the DC landing page image carousel

### ISSUE THREAD

**Issue by abbypenn93** [ucsdlib/damspas#696]
### Descriptive summary

Add four research data images to the Digital Collections landing page image carousel.

### Rationale

Currently, there are very few images associated with UC San Diego research data in the Digital Collections landing page image carousel. By adding selected images (shown below), we will increase users' exposure both to Digital Collections as a research data repository and to the tremendous work being done by our researchers and graduate students.

_Note: Two of the items listed below could replace the Santa Fe Light Cone Simulation and the SIO dredge images, already in the landing page carousel._

### Expected behavior
The content below will be added to the DC landing page image rotation:
1. dataMares (ecology/biodiversity)

Text to accompany image:

From the dataMares: Ecological Monitoring Collection
Tracking changes in the structure, function, and health of marine ecosystems in the Gulf of California through annual surveys of fishes and invertebrates at numerous island and coastal sites. 
Collection by Octavio Aburto-Oropeza, Alfredo Giron-Nava, Raquel Lopez

Image file:
/rdcp-staging/rdcp-0041-dataMares/Admin/coll images/promonitor.jpg

Pixels:
1000 × 662 (if needed, can trim on the bottom)

2. Catalhoyuk Glimpse (archeology)

Text to accompany image:

From the Data from: A Glimpse through Time and Space: Visualizing Social Memory and History-making at Çatalhöyük Collection
A 3-D reconstruction of 'Shrine' 10 (level VI phase A) in the South Area of the Neolithic site, Çatalhöyük, in Turkey.
Collection by Nicola Lercari, Grant Cox, Gesualdo Busacca, Arianna Campiani, Jad Aboulhosn, and Anaïs Guillem

Image file:
/rdcp-staging/rdcp-0140-catalhoyuk-glimpse/Working_Files/Version2_2019/Glimpse_Data_2019/S.VIA.10_SE_Render.png

Pixels:
3840 x 2160

3. Data from: Urbanization-induced habitat fragmentation erodes multiple components of temporal diversity in a Southern California native bee assemblage (ecology)

Text to accompany image:

From the Data from: Urbanization-Induced Habitat Fragmentation Erodes Multiple Components of Temporal Diversity in a Southern California Native Bee Assemblage Collection  
One of the bee species (Diadasia opuntiae) surveyed in the coastal sage scrub reserves and habitat fragments of coastal San Diego County.
Collection by Keng-Lou James Hung and David A. Holway

Image file:
/rdcp-staging/rdcp-0080-bee-plant-samples-hung/CLR/Diadasia_opuntiae.JPG

Pixels:
1332 × 1067

4. Data from: Climate change intensification of horizontal water vapor transport in CMIP5 (atmospheric chemistry)

Text to accompany image:

From the Data from: Climate Change Intensification of Horizontal Water Vapor Transport in CMIP5 Collection
Representation of projected changes to global atmospheric water vapor transport (integrated vapor transport (IVT)), the key link between water source and sink regions.
Collection by David A. Lavers, F. Martin Ralph, Duane E. Waliser, Alexander Gershunov, and Michael D. Dettinger

Image file:
/rdcp-staging/rdcp-0117-cmip5/CLR/Fig3a.JPG

Pixels:
987 × 452

**Comment by gamontoya** [comment]
@abbypenn93 This is going to need to get approval by the DAMS Working Group. I'll keep you posted.

**Comment by gamontoya** [comment]
@dt-ucsd Assigning to you. Let me know where you want me to put the images for you.

**Comment by gamontoya** [comment]
Images sent to David via RDL-Share.

**Comment by dt-ucsd** [comment]
@gamontoya -- The new background are live.

**Comment by gamontoya** [comment]
@abbypenn93 See David's comment above. Yay!

@dt-ucsd Thank you David.

**Comment by abbypenn93** [comment]
Hi! I refreshed the DC landing page many times but I didn't see any of the four new research data images, were they added?

**Comment by dt-ucsd** [comment]
Hi @abbypenn93 -- The three new images and their data are live on the site.

Since the background is pulled randomly from a set of ~35 pictures, it may take you a few refreshes to come across one.

Also, you may have an old version of the JS data file cached. Perform a hard reload of the page and you should be able to eventually come across one.

**Comment by abbypenn93** [comment]
@dt-ucsd Thanks. I'm assuming rebooting my computer counts as a hard reload? I saw a lot of new images but after repeated refreshing over a period of 5 minutes I didn't see any of the research data images that I submitted.
