### ISSUE TITLE
SCWMP Usage Statistics

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#703]
### Descriptive summary

Cristela would like `usage` statistics for the Spanish Civil War Memory Project since we started capturing these statistics. The collection ARK is `bb8602294g`

**Comment by gamontoya** [comment]
@lsitu Cristela needs these by the end of the month.

**Comment by lsitu** [comment]
@gamontoya What fields we need to count for the collection statistics, object views only?

**Comment by gamontoya** [comment]
@cgarciaspitz What usage stats do you want pulled out? Just objects views or?

**Comment by cgarciaspitz** [comment]
Oh thank you!  yes, I think having the number of object views by month since the collection was first made available online would be useful.

Do we have data like where the users are coming from? e.g. this many from the U.S. this many from Spain?

**Comment by gamontoya** [comment]
@lsitu So looks like just object views by month. I told Cristela that I don't think we capture where are users are coming from. Please proceed.

**Comment by lsitu** [comment]
@gamontoya / @cgarciaspitz Sure. Yes, we don't capture where are users are coming from.

**Comment by lsitu** [comment]
@jgorney Could we run the following SQL on prod Postgres for the statistics report?
```
SELECT TO_CHAR(s.STAT_DATE, 'yyyy/MM') AS period, SUM(a.NUM_VIEW) as num_view FROM WEB_STATS s, STATS_DLP_OBJECT_ACCESS a WHERE s.ID=a.STAT_ID AND s.APP_NAME='pas' AND a.col_id='bb8602294g' GROUP BY TO_CHAR(s.STAT_DATE, 'yyyy/MM') ORDER BY period
```
This will generate the statistics for collection `bb8602294g` by month with two columns like:

| period | num_view |
| ------------- | ------------- |
| ... | ... |
| 2019/07  | 999 |
| 2019/08  | 1001 |

Thank you.

**Comment by jgorney** [comment]
Yes – here’s the output:

dams=> SELECT TO_CHAR(s.STAT_DATE, 'yyyy/MM') AS period, SUM(a.NUM_VIEW) as num_view FROM WEB_STATS s, STATS_DLP_OBJECT_ACCESS
a WHERE s.ID=a.STAT_ID AND s.APP_NAME='pas' AND a.col_id='bb8602294g' GROUP BY TO_CHAR(s.STAT_DATE, 'yyyy/MM') ORDER BY period; period  | num_view
---------+----------
2016/04 |       55
2016/05 |       40
2016/06 |       53
2016/07 |       17
2016/08 |       53
2016/09 |       20
2016/10 |       54
2016/11 |       41
2016/12 |      176
2017/01 |       41
2017/02 |       26
2017/03 |       18
2017/04 |       43
2017/05 |        9
2017/06 |       11
2017/07 |        6
2017/08 |       24
2017/09 |       44
2017/10 |       67
2017/11 |       77
2017/12 |       56
2018/01 |       45
2018/02 |      202
2018/03 |       72
2018/04 |       59
2018/05 |       76
2018/06 |       63
2018/07 |       44
2018/08 |       42
2018/09 |       64
2018/10 |      184
2018/11 |     1088
2018/12 |       92
2019/01 |      264
2019/02 |       98
2019/03 |      124
2019/04 |      644
2019/05 |      265
2019/06 |      133
2019/07 |      126
2019/08 |       99
(41 rows)

**Comment by lsitu** [comment]
Thanks @jgorney.
@gamontoya @cgarciaspitz I think that's the object view statistics (by month) for SCWMP Usage Statistics, which is starting from April, 2016.

**Comment by jessicahilt** [comment]
Per @cgarciaspitz, she would like to see this data prior to 2016. Can you pull this for her @lsitu?

**Comment by lsitu** [comment]
@jessicahilt Sure. I'll try to run the dams statistic process to generate the the data prior 2016, which will take some time to be done for a slow process. But we can only have it for dams4.

**Comment by lsitu** [comment]
@gamontoya / @cgarciaspitz We don't have weblog prior `httpd.2015-08-08`, and we only can generate dams statistics starting from `httpd.2015-08-08`. 

@jgorney I think the process to generate the dams statistics data between August 2015 and  Mar 2016 is done. Could we run the following SQL on prod Postgres for the statistics report again? Thanks. 
```
SELECT TO_CHAR(s.STAT_DATE, 'yyyy/MM') AS period, SUM(a.NUM_VIEW) as num_view FROM WEB_STATS s, STATS_DLP_OBJECT_ACCESS a WHERE s.ID=a.STAT_ID AND s.APP_NAME='pas' AND a.col_id='bb8602294g' GROUP BY TO_CHAR(s.STAT_DATE, 'yyyy/MM') ORDER BY period
```
Note that dams statistics data between April 2016 and Jun 30 2016 is regenerated, so the counts could be a little different for these three months now.

**Comment by jgorney** [comment]
Hi @lsitu - here you go:

dams=> SELECT TO_CHAR(s.STAT_DATE, 'yyyy/MM') AS period, SUM(a.NUM_VIEW) as num_view FROM WEB_STATS s, STATS_DLP_OBJECT_ACCESS a WHERE s.ID=a.STAT_ID AND s.APP_NAME='pas' AND a.col_id='bb8602294g' GROUP BY TO_CHAR(s.STAT_DATE, 'yyyy/MM') ORDER BY period;
 period  | num_view 
---------+----------
 2015/08 |       48
 2015/09 |       67
 2015/10 |       29
 2015/11 |        9
 2015/12 |       13
 2016/01 |       24
 2016/02 |       42
 2016/03 |      125
 2016/04 |      196
 2016/05 |       74
 2016/06 |      130
 2016/07 |       17
 2016/08 |       53
 2016/09 |       20
 2016/10 |       54
 2016/11 |       41
 2016/12 |      176
 2017/01 |       41
 2017/02 |       26
 2017/03 |       18
 2017/04 |       43
 2017/05 |        9
 2017/06 |       11
 2017/07 |        6
 2017/08 |       24
 2017/09 |       44
 2017/10 |       67
 2017/11 |       77
 2017/12 |       56
 2018/01 |       45
 2018/02 |      202
 2018/03 |       72
 2018/04 |       59
 2018/05 |       76
 2018/06 |       63
 2018/07 |       44
 2018/08 |       42
 2018/09 |       64
 2018/10 |      184
 2018/11 |     1088
 2018/12 |       92
 2019/01 |      264
 2019/02 |       98
 2019/03 |      124
 2019/04 |      644
 2019/05 |      265
 2019/06 |      133
 2019/07 |      126
 2019/08 |      145
 2019/09 |      110
(50 rows)

**Comment by lsitu** [comment]
Thanks @jgorney. 
@gamontoya / @cgarciaspitz That's all statistics we can have for SCWMP now. Note that the counting rules for SCWMP collection were changes over time and the statistics data is different if we regenerate it basing on the current counting rules. Would you like to regenerate the statistics data to comply with the current counting rules, or leave it as is? 

@rstanonik Is it still possible to have the weblogs prior August 8, 2015 for dams4? Thanks.

**Comment by rstanonik** [comment]
@lsitu Sorry, I can't find older logs.  I thought I had older logs, but haven't found any.

**Comment by lsitu** [comment]
Thanks for the update @rstanonik.

**Comment by gamontoya** [comment]
@lsitu I'm going to close this ticket for now since Cristela is out of town for a couple of weeks. 

@cgarciaspitz Feel free to re-open if you have further needs.
