### ISSUE TITLE
Delete 42 duplicate objects in Larcom-Skinner Jones

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damspas#704]
### Descriptive summary

Still unsure how this happened, as the ARK reports only contain 353 objects, yet 395 are in the [Larcom-Skinner Jones Collection](https://library.ucsd.edu/dc/collection/bb9663649f).  

So requesting those 42 duplicate objects for deletion. Attaching the ARKs to delete on spreadsheet.

[arks_to_delete.xlsx](https://github.com/ucsdlib/damsmanager/files/3527502/arks_to_delete.xlsx)

**Comment by VivianChu** [comment]
@remerjohnson @gamontoya - The duplicate objects have been deleted.  Could you review it?  Thanks
https://library.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=Ann+Skinner-Jones+and+Joan+Larcom+Photographs&id=bb9663649f&sort=title_ssi+asc

**Comment by remerjohnson** [comment]
@VivianChu These look great! Thanks
