### ISSUE TITLE
Data Sync to Staging/QA

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#709]
## Descriptive summary

- Please sync data from prod to staging and QA. This should include everything (triplestore, solr, files, etc.)
- Requested by Arwen.

### Notes

- Operations: @jgorney @rstanonik

**Comment by gamontoya** [comment]
@rstanonik It's helpful when you posted the status as comments. Also, should metadata folks be uploading collections to staging when the sync is happening?

**Comment by rstanonik** [comment]
@gamontoya No one should be updating data in QA or staging during the sync because I'll be overwriting the data.
We're ready to start the sync.
Should we wait for some testing to finish?

**Comment by gamontoya** [comment]
@rstanonik It's fine to start now.

**Comment by rstanonik** [comment]
Starting now.  I'll provide estimates of time to completion after it has run a while

**Comment by gamontoya** [comment]
Thank you!

**Comment by jgorney** [comment]
And the triplestore sync has been started too.

**Comment by gamontoya** [comment]
@jgorney Thank you Juliana! 🎉

**Comment by jgorney** [comment]
The triplestore sync from prod to to Staging/QA is complete.

**Comment by rstanonik** [comment]
QA and staging file syncs are both about 60% done.  Unless there is some very large ARK to sync, it should be done in about 3 hours, this time.

**Comment by gamontoya** [comment]
@rstanonik Wow, that's super fast!

**Comment by rstanonik** [comment]
QA and staging file syncs both about 85% done.  Maybe nothing large ingested since last sync.

QA and staging solr syncs are done.

**Comment by rstanonik** [comment]
QA and staging file sync finished.

QA and staging should be ready to use.

**Comment by gamontoya** [comment]
@rstanonik @jgorney Thank you very much 🏆
