### ISSUE TITLE
Deletion request for dataMares object

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damspas#713]
### Descriptive summary

Please delete https://library.ucsd.edu/dc/object/bb34157613, which is currently in Curator only view. Per depositor's email on 6/28/17, "it is very sensitive information that we just realized that can't be released yet (not even metadata)." As part of cleanup for this collection, let's remove this completely from the DAMS since there's minimal benefit to having it remain on the server and a non-trivial risk to having it accidentally exposed to public view.

### Related work

https://ucsdlibrary.atlassian.net/browse/DI-133
https://ucsdlibrary.atlassian.net/browse/CPP-41

**Comment by lsitu** [comment]
@gamontoya Sure. I'll take care of it.

**Comment by lsitu** [comment]
@hjsyoo @gamontoya The curator object https://library.ucsd.edu/dc/object/bb34157613 is removed from prod now.

**Comment by hjsyoo** [comment]
@lsitu Great, thank you!
