### ISSUE TITLE
Add additional parent collection for several collections

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damspas#714]
### Descriptive summary

The following collections already have parent collections, but will need to be additionally have the [UC San Diego History](https://library.ucsd.edu/dc/collection/bb2288090s) added as an additional parent collection: 
* [CME](https://library.ucsd.edu/dc/collection/bb10936072)
* [DMCA](https://library.ucsd.edu/dc/collection/bb91824453)
* [IDEAS](https://library.ucsd.edu/dc/collection/bb4029917n)
* [UCSD AudioVisual Theses and Dissertations](https://library.ucsd.edu/dc/collection/bb9253289t)

### Related work

#705

**Comment by gamontoya** [comment]
@hweng Assigning this one to you as well. Note that it's `high priority`.

**Comment by gamontoya** [comment]
@hweng This one too was assigned two weeks ago. Let me know if you don't have time to work on these tickets.

**Comment by hweng** [comment]
@gamontoya I have updated the metadata for the four children collections and one parent collection for their relationship:
https://library.ucsd.edu/dc/collection/bb2288090s/data
https://library.ucsd.edu/dc/collection/bb10936072/data
https://library.ucsd.edu/dc/collection/bb91824453/data
https://library.ucsd.edu/dc/collection/bb4029917n/data
https://library.ucsd.edu/dc/collection/bb9253289t/data

And has been waiting for solr index updating done.

**Comment by gamontoya** [comment]
@remerjohnson Please let us know if this work is approved.

**Comment by remerjohnson** [comment]
@gamontoya Yes, this looks perfect. A reminder that #725 is very similar. Thanks!
