### ISSUE TITLE
Change visibility of Data from: A Glimpse through Time and Space: Visualizing Social Memory...(2018)

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damspas#719]
### Descriptive summary

De-index all pages in the Catalhoyuk Glimpse (v1) collection: https://library.ucsd.edu/dc/collection/bb3485072m, so they stop turning up in a search (DAMS or Google).
- 1 collection page
- 8 object pages

The pages should continue to be accessible by URL.

### Related work

- https://ucsdlibrary.atlassian.net/browse/DI-266
- https://docs.google.com/spreadsheets/d/1M96UIFczSFOixH-qdqMKHeuIkY65NWAhRp4QixUKqok/edit#gid=1723491446

**Comment by gamontoya** [comment]
@arwenhutt Your discovery sounds like a separate issue. Can you create a new ticket for this bug?

**Comment by arwenhutt** [comment]
@gamontoya sure, damspas or damsmanager?

**Comment by lsitu** [comment]
@arwenhutt I think we can create the ticket on damsrepo to fix the behavior for CLR `suppressDiscovery`.

**Comment by arwenhutt** [comment]
@lsitu @gamontoya @hjsyoo I created a new ticket in damsrepo: https://github.com/ucsdlib/damsrepo/issues/99
It looks like I don't have permissions to add people/tags etc. so it doesn't have anything except the title and body, so it doesn't have anyone or any tags.

**Comment by lsitu** [comment]
@arwenhutt Thanks. I'll look into it.

**Comment by gamontoya** [comment]
@lsitu @arwenhutt What's the status on this ticket. Is it waiting for someone/something?

**Comment by lsitu** [comment]
@gamontoya I think should be done through ticket https://github.com/ucsdlib/damsrepo/issues/99 (PR https://github.com/ucsdlib/damsrepo/pull/100).

**Comment by hjsyoo** [comment]
Has the fix been deployed? Are we now able to suppress discovery of this collection page?

**Comment by lsitu** [comment]
@hjsyoo Yes. It was deployed to prod last month in Oct. 15.

**Comment by hjsyoo** [comment]
@arwenhutt Looks like we can give this a whirl!

**Comment by hjsyoo** [comment]
@arwenhutt I think we're okay to change this collection page to discovery-suppressed. Can you give it a try? If it works, then I'll write up some text to be added to the Description, so that even if the View Collection Items button doesn't pull up anything for non-Curators, there will at least be a series of DOIs that link to the 8 objects within the collection.

**Comment by arwenhutt** [comment]
@hjsyoo 
Done - but double check!  I searched for
["Data from: A Glimpse through Time and Space"](https://library.ucsd.edu/dc/search?utf8=%E2%9C%93&q=%22Data+from%3A+A+Glimpse+through+Time+and+Space%22) (not logged in, private firefox window) and it returns 9 things (8 objects, 1 clr)

A little more information for documentation's sake:
The visibility metadata had been updated before, but then when we were troubleshooting why the view objects in collection button didn't work, I tried re-releasing the collection.  I think that reset the visibility value.  [Slack conversation link](https://ucsdlibrary.slack.com/archives/C074RV85N/p1575670737086700)

**Comment by hjsyoo** [comment]
Awesome, thank you, it works for me, too with 9 returned things. So now, in https://library.ucsd.edu/dc/collection/bb3485072m, what do you think of adding this text to the Description, after the first short paragraph and before "This collection includes a set of 3-D models..."?

The 8 items in this collection can be accessed through the following Digital Object Identifier links:

https://doi.org/10.6075/J0WD3XWM
https://doi.org/10.6075/J0G44NMM
https://doi.org/10.6075/J0BC3WWW
https://doi.org/10.6075/J02Z13VJ
https://doi.org/10.6075/J0057D8C
https://doi.org/10.6075/J0VD6WT4
https://doi.org/10.6075/J0QN6536
https://doi.org/10.6075/J0KW5DCG

**Comment by arwenhutt** [comment]
@hjsyoo That sounds like a good option.  I've added it to the clr https://library.ucsd.edu/dc/collection/bb3485072m

**Comment by hjsyoo** [comment]
Thanks, @arwenhutt !
