### ISSUE TITLE
Add support for other HTML tags in objects

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#722]
### Descriptive summary

Currently, the only support for embedded HTML tags is for rendering links. 

Consider adding support for displaying/rendering other HTML tags within collection level records.

### Use case

Needed to display HTML formatted tables for CIL.

### Related

-  https://github.com/ucsdlib/damsmanager/issues/317#issuecomment-545499347

**Comment by gamontoya** [comment]
@jessicahilt Can you add the level of effort there after you talk to @lsitu

**Comment by lsitu** [comment]
@jessicahilt @gamontoya It looks like it may not need too much efforts but practice with the metadata with HTML tags to see how to make it work. Do we want to display HTML tags for all data fields or just the `Description` note for now?

**Comment by gamontoya** [comment]
Just `description` note for now @lsitu

**Comment by hjsyoo** [comment]
@lsitu @jessicahilt @gamontoya After discussion during the DAMS Working Group and with Arwen and Abby, I think the consensus is that rendering html tags in the metadata would not be a good idea. We push out our metadata to many other systems, and there's too much potential for things to break. I'll note in https://github.com/ucsdlib/damsmanager/issues/317 how we're planning to deal with the html tables in those CIL records.

**Comment by lsitu** [comment]
@hjsyoo Okay. I would stop working on the ticket now.

**Comment by lsitu** [comment]
Just a follow up note for reference: 
The table can be displayed in damspas for @abbypenn93 's test object: http://libraryqa.ucsd.edu/dc/object/bd3469143k:

<img width="943" alt="Screen Shot 2019-11-06 at 3 06 55 PM" src="https://user-images.githubusercontent.com/2430784/68345873-60b16b80-00a7-11ea-830a-e59a0c1086d4.png">
