### ISSUE TITLE
Add parent collections (and remove one) from Visual Arts and Architecture

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damspas#725]
### Descriptive summary

The [Visual Arts and Architecture Collection](https://library.ucsd.edu/dc/collection/bb5532785m) needs its subcollection membership to be updated, adding several collections to it, and _removing_ one.

Add to VA&A: 
- [History of the UC San Diego Visual Arts Department](https://library.ucsd.edu/dc/collection/bb5533548r)
- [Stuart Collection Photographs](https://library.ucsd.edu/dc/collection/bb9421444x)
- [Stuart Collection Records](https://library.ucsd.edu/dc/collection/bb86393740)
- [UAG Art Gallery Closure Events, 2016](https://library.ucsd.edu/dc/collection/bb88784417)
  
Remove from VA&A:  

- [Music Collection](https://library.ucsd.edu/dc/collection/bb4373297t)

### Related work

#705 
#714

**Comment by gamontoya** [comment]
@hweng Hi Huawei. Per Jessica, I'm assigning this ticket to you. Note that it's `high priority`.

**Comment by gamontoya** [comment]
@hweng Hi Huawei. This was assigned to you two weeks ago. Did it fall off your radar?

**Comment by gamontoya** [comment]
@hweng This one needs to be done too 👍

**Comment by hweng** [comment]
@gamontoya The 4 collections were added to VA&A collection, and solr index updates was done. Please take a look if it looks fine to you.

For music collection, Looking into its RDF data and solr index, it is actually not included in the VA&A collection:
metadata: https://library.ucsd.edu/dc/collection/bb5532785m/data
solr index: http://lib-hydratail-prod.ucsd.edu:8983/solr/blacklight/select?q=id:bb5532785m

I think the reason that it shows up is that there are some child collections such as  "UCSD Audio Visual Theses and Dissertations" https://library.ucsd.edu/dc/collection/bb9253289t has both parent collection of VA&A and music collection.
And in the damspas collection display it implemented rules to display all child collections and all child collection's parent collection. 
I would suggest you to open a ticket to investigate this issue and change the implementation rule if you don't like this behavior.

**Comment by gamontoya** [comment]
@remerjohnson Please review Huawei's work when you have a chance.

**Comment by remerjohnson** [comment]
@gamontoya @hweng Thanks, Huawei! It all looks good. I will relay that explanation about the Music collection to the stakeholder to see if they would pursue that change, but this issue is resolved. Thanks again

**Comment by hweng** [comment]
@remerjohnson @gamontoya Thank you for your reviewing. 

It has been so nice working with you for DAMS for the past years. Happy Holidays!

**Comment by gamontoya** [comment]
@hweng Thank you for your great work and for supporting our endeavors for over 10 years! Best of luck at your new job ☃️ 🤞 🎄
