### ISSUE TITLE
UCSD-GUEST users cannot connect to the Geisel Library streaming video/audio service

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/damspas#729]
### Descriptive summary

There two servers: lib-streaming.ucsd.edu (132.239.119.181) and lib-streaming-test.ucsd.edu (132.239.119.176), which provide streaming service on two ports, which should be accessible to anyone on campus of off (TCP 1935 and 1936)

### Expected behavior
User can connect to streaming video/audio service on UCSD-GUEST network.

### Actual behavior
User cannot connect to streaming video/audio service on UCSD-GUEST network.

### Related work
https://github.com/ucsdlib/dmr/issues/405
https://ucsdlibrary.zendesk.com/agent/tickets/123

**Comment by VivianChu** [comment]
@gamontoya - I updated Damspas and deployed it to qa. Could you try to see if they work for you using UCSD-Guest wireless network? Thanks

For example - 
http://libraryqa.ucsd.edu/dc/object/bb6728545w
http://libraryqa.ucsd.edu/dc/object/bb7615632n

Those worked for me and Ron on UCSD-Guest.

**Comment by gamontoya** [comment]
@VivianChu These both worked fine for me using UCSD-guest wireless.
