### ISSUE TITLE
Contextual display for Cite this Work enhancement

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#732]
### Descriptive summary

It looks like there's an issue with Batch Edit application of the recent Cite this Work enhancement. This is a newly ingested stub collection in Staging: [https://librarytest.ucsd.edu/dc/collection/bd2513535k](https://librarytest.ucsd.edu/dc/collection/bd2513535k). Both objects in the collection show "Digital Object made available by RDCP."  Both objects have had Batch Edit performed on them and instead of appearing at the top of the object landing page, the "Cite this Work" section appears near the bottom. 

Abby reproduced the bug in production.  Talking through it, this seems to be a bug with the contextual display enhancement. Editing metadata via the batch overlay or RDF edit tools shouldn't effect display order - unless, of course, a required field is modified.  The records we've seen this with have all of the correct required metadata to trigger the "RDCP placement" of the note (both before and after editing.)  Since this isn't a damsmanager bug, we'll turn it over to you for sheparding through a fix.  Let us know if you need more details or if anything comes up related to the metadata piece.

### Related work

- https://github.com/ucsdlib/damsmanager/issues/368

**Comment by gamontoya** [comment]
@lsitu Whenever you can get to this considering the holidays coming up.

**Comment by lsitu** [comment]
@gamontoya Sure.

**Comment by lsitu** [comment]
@arwenhutt I found that the `Unit` metadata is missing from both Batch Export and Batch Edit. Would you like to add column `unit` at the end following the descriptive metadata for copyright?

**Comment by lsitu** [comment]
@arwenhutt @abbypenn93 I've added MR https://github.com/ucsdlib/damsmanager/pull/380 and MR https://github.com/ucsdlib/private_config/pull/21 to add `unit` field to both the Batch Export tool and Batch Overlay/Edit tool, which will add the missing `Unit` field to the object and fix the contextual display order with Cite this Work. Should we can deploy it to staging so that you can test it to see how it goes? Happy Holidays!

**Comment by abbypenn93** [comment]
@lsitu Yes, please deploy to staging. Happy New Year, Longshou.

**Comment by lsitu** [comment]
@abbypenn93 Sure. I think we can make a new release for it so that you can review it  on staging once @mcritchlow is back and the PR is reviewed. I'll let you know if it's ready. Thanks. Happy New Year 2020!

**Comment by gamontoya** [comment]
@lsitu @jessicahilt Can Vivian review the PR and not have it have to wait for Matt's return? This is a blocker to DOMM being able to batch edit anything and all things.

**Comment by lsitu** [comment]
@gamontoya Sure. We'll have @VivianChu to review it once she's back.

**Comment by arwenhutt** [comment]
Wonderful!  Thanks @lmcphee @VivianChu and @gamontoya :)

**Comment by gamontoya** [comment]
@lsitu Do you need a release ticket for this?

**Comment by lsitu** [comment]
@gamontoya Yes. Please create one for it. I think there are several PRs will be merged release at the same time.

**Comment by arwenhutt** [comment]
@abbypenn93 My other bug ended up not requiring much testing, so I thought I'd do some testing for this one.

I exported the collection linked in the bug description, added the unit info to one object (https://librarytest.ucsd.edu/dc/object/bd9919746h), and overlaid the metadata.  The unit metadata appears in the rdf view and "cite this work" appears under the collection title.  I also verfied that the item with the unit added now shows up in searches using the "UCSD Research Data Collections" facet.

**Comment by arwenhutt** [comment]
reopening for testing

**Comment by abbypenn93** [comment]
I did a bunch of Batch Edits and the fix looks good: the "Cite This Work" section appears in the correct location and the objects are associated with UCSD Research Collections.

**Comment by arwenhutt** [comment]
@abbypenn93 @lsitu 
I've done a few more exports and some overlays, and it looks like <dams:unit> is exporting and overlaying as expected.  I think we can close this unless you've run into any problems with it @abbypenn93 ?
