### ISSUE TITLE
A section of note metadata fields are displaying twice in the UI

### ISSUE THREAD

**Issue by mdpeters** [ucsdlib/damspas#734]
### Descriptive summary

Note:bibliography, note:classification, note:custodial history, note:publication, note:series, and note:thesis all get repeated in the UI even though they only exist in the metadata once (from the metadata tracer: https://library.ucsd.edu/dc/object/bb2322475s):
![note_dups](https://user-images.githubusercontent.com/22665238/71192929-0f67d080-223e-11ea-8857-192b072e8127.png)

### Expected behavior
Notes should only display once (looking at the underlying metadata, it's only in there once, the UI is just displaying the notes twice)

**Comment by VivianChu** [comment]
@gamontoya @mdpeters - The fix has been deployed to staging.  Could you review it? Thanks

https://librarytest.ucsd.edu/dc/object/bb2322475s

//Before the fix
![beforeDuplicateFix](https://user-images.githubusercontent.com/1864660/71742050-598fab00-2e15-11ea-8d7b-1de8b0e4c976.png)

//After the fix
![afterFixDupNote](https://user-images.githubusercontent.com/1864660/71742057-5e545f00-2e15-11ea-80e7-25ad179e97d4.png)

**Comment by gamontoya** [comment]
@VivianChu This looks good. Do you need a release ticket for this one too?

**Comment by VivianChu** [comment]
@gamontoya - Yes, I need a release ticket for this one too. Thanks

**Comment by VivianChu** [comment]
@gamontoya @mdpeters - The fix has been deployed to production. 
https://library.ucsd.edu/dc/object/bb2322475s
