### ISSUE TITLE
Re-add "Edit" button to CLR pages

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#739]
### Descriptive summary

While the **"Edit"** button exists at the object level record, **edit** is missing from the collection level record page. Please re-add.

**Comment by VivianChu** [comment]
@gamontoya - The "Edit" button has been added and deployed to qa.  Could you review it?  Thanks
For example http://libraryqa.ucsd.edu/dc/collection/bd48684588

**Comment by gamontoya** [comment]
@VivianChu Looks good! Thank you for working on this so quickly.
