### ISSUE TITLE
Release 1.98.0

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#741]
# Descriptive summary

- Version: 1.98.0
- Release Manager: @VivianChu  
- Product Owner and Reviewer: @gamontoya 
- Operations: @rstanonik 
--------------
## To Verify

- [x] #739 
- [ ] ucsdlib/damsmanager#388

Release note:

https://github.com/ucsdlib/damspas/releases/tag/1.98.0

**Comment by gamontoya** [comment]
@VivianChu Please add what needs to be verified.

**Comment by VivianChu** [comment]
@gamontoya - The new release has been deployed to staging.  Could you review it?

Thanks

**Comment by gamontoya** [comment]
@VivianChu I can confirm that the Edit button is back on the CLRs.

Who is testing this? --> ucsdlib/damsmanager#388

**Comment by VivianChu** [comment]
@lsitu - How to test your change? Thanks

**Comment by lsitu** [comment]
@VivianChu I think we may need the damsorizer up and running on staging. I tried to update some collection but until now I am still not able to index any records. @rstanonik Could you take a look at damsolrizer on staging? Thank you.

**Comment by rstanonik** [comment]
[damsolrizer.log.gz](https://github.com/ucsdlib/damspas/files/4173906/damsolrizer.log.gz)
Here is the damsolrizer log.  There is an error at the end, but it doesn't mean anything to me.  You can also see the damsolrizer logs by ssh to lib-hydrahead-staging then look at /home/conan/log/damsolrizer.%Y-%m-%d.log

**Comment by lsitu** [comment]
@rstanonik It looks like something weird in SOLR. Could you restart it? Thank you.

**Comment by lsitu** [comment]
@gamontoya / @hjsyoo / @VivianChu I think ticket https://github.com/ucsdlib/damsmanager/issues/388 is ready for review now. Just review the objects in RCP collections to see whether they have the correct copyright note and we can start from there to see what need to adjust. Thank you.

**Comment by gamontoya** [comment]
@hjsyoo Awaiting your review.

**Comment by hjsyoo** [comment]
Thanks @lsitu. I'll work with @abbypenn93 to test this on a few new objects. Unfortunately, we don't currently have enough examples representing all the conditionals, so we can't test the full code on existing objects.

**Comment by lsitu** [comment]
@gamontoya @VivianChu Are we ready to move damspas release 1.98.0 to prod? I think damsmanager [release 2.77](https://github.com/ucsdlib/damsmanager/issues/399) has dependency on it for copyright boilerplate cleanup and we had better move them forward together. Thanks.

**Comment by VivianChu** [comment]
@lsitu - My change is ready. @gamontoya - is it ok to move it to prod?  Thanks

**Comment by gamontoya** [comment]
@VivianChu Yes, it's approved for prod.

**Comment by VivianChu** [comment]
@rstanonik - Could you deploy new damspas release to prod at your earliest convenient?  Thanks

**Comment by rstanonik** [comment]
Thor deployed damspas to prod this morning, along with damsmanager.
Include Thor (tnbrickman) in future deploy requests

**Comment by lsitu** [comment]
@rstanonik Sure. Just added @thorucsd in. Thank you both.

**Comment by VivianChu** [comment]
Thanks everyone
