### ISSUE TITLE
Delete duplicate LLNL COWC object

### ISSUE THREAD

**Issue by abbypenn93** [ucsdlib/damspas#749]
### Descriptive summary

Delete this duplicate COWC object: https://library.ucsd.edu/dc/object/bb1779796g. It's the first ingest of COWC, with the wrong copyright boilerplate (at time of second COWC ingest).

**Comment by gamontoya** [comment]
@lsitu Can you please delete in all relevant places?

**Comment by lsitu** [comment]
@gamontoya Sure.

**Comment by lsitu** [comment]
@gamontoya The duplicate COWC object https://library.ucsd.edu/dc/object/bb1779796g and its files are gone now.

**Comment by gamontoya** [comment]
@abbypenn93 ⬆️

**Comment by hjsyoo** [comment]
I've reviewed the deletion and the remaining collection. All is good - closing ticket!
