### ISSUE TITLE
Data request from HLHW collection, and deletion request 

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damspas#751]
### Descriptive summary
I am requesting a download of archival files in the Holocaust Living History Workshop collection, which I will then do file replacements on. The 11 objects and the files to download are in this spreadsheet (you can ignore the PDF column): 

[release_forms_work.xlsx](https://github.com/ucsdlib/damspas/files/4268845/release_forms_work.xlsx)

In addition, I am requesting that this duplicate object be deleted from production: 
https://library.ucsd.edu/dc/object/bb5397507j 

### Rationale

Kirk Wang, in his capacity as project manager for HLHW, has requested that for UCTV-filmed Holocaust Living History workshops, we include the release forms in the archival files present in those objects.

### Related work

#308

**Comment by VivianChu** [comment]
@gamontoya @remerjohnson - The duplicate object has been deleted.  The archival files can be downloaded here - https://drive.google.com/drive/folders/14DmBSMO_oqcXbSS4iD4mb3p5_sbE1use?usp=sharing

**Comment by remerjohnson** [comment]
@VivianChu Thanks so much, Vivian. Can confirm the object is deleted, and thanks for providing the files. Going to close this out

**Comment by VivianChu** [comment]
@remerjohnson - Are you able to access the files?  Thanks

**Comment by remerjohnson** [comment]
@VivianChu Yes. I am moving them to staging to work on now. Thanks
